In [64]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [65]:
# define file path and sheet names
file_path = "MAIN_Penetration and Value Drivers Template_raw data for Divyaa & Rinu v2.xlsx"
sheet1 = "Penetration Trends Template"
sheet2 = "KPIs - EU5 template"

# load both sheets skipping raw1 and assigning multi-row headers
# df1: skip first row then next 4 rows as headers
# df2: skip first row then next 2 rows as headers

df1 = pd.read_excel(
    file_path,
    sheet_name=sheet1,
   skiprows=1,
    header=[0,1,2,3]
)

df2 = pd.read_excel(
    file_path,
    sheet_name=sheet2,
    skiprows=1,
    header=[0,1]
)

# show some info
print("df1 shape:", df1.shape)
print("df1 columns:\n", df1.columns)
print("df2 shape:", df2.shape)
print("df2 columns:\n", df2.columns)

C:\Users\rdi5001\AppData\Roaming\Python\Python311\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Web Extension extension is not supported and will be removed
  warn(msg)

df1 shape: (3074, 31)
df1 columns:
 MultiIndex([(            'Unnamed: 0_level_0', 'Unnamed: 0_level_1', ...),
            (            'Unnamed: 1_level_0', 'Unnamed: 1_level_1', ...),
            (            'Unnamed: 2_level_0', 'Unnamed: 2_level_1', ...),
            (            'Unnamed: 3_level_0', 'Unnamed: 3_level_1', ...),
            (            'Unnamed: 4_level_0', 'Unnamed: 4_level_1', ...),
            (            'Unnamed: 5_level_0', 'Unnamed: 5_level_1', ...),
            (            'Unnamed: 6_level_0', 'Unnamed: 6_level_1', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...)],
           )
df2 shape: (5265, 18)
df2 columns:
 MultiIndex([(        'Unnamed: 0_level_0', ...),
            (        'Unnamed: 1_level_0', ...),
            (        'Unnamed: 2_level_0', ...),
            (        'Unnamed: 3_level_0', ...),
            (        'Unnamed: 4_level_0', ...),
            (        'Unnamed: 5_level_0', ...),
            (        'Unnamed: 6_level_0', ...),
            (        'Unnamed: 7_level_0', ...),
            ('Latest 52 Wks - w/e W4 Y26', ...),
            ('Latest 52 Wks - w/e W4 Y26', ...),
            ('Latest 52 Wks - w/e W4 Y26', ...),
            ('Latest 52 Wks - w/e W4 Y26', ...),
            ('Latest 52 Wks - w/e W4 Y26', ...),
            ('Latest 26 Wks - w/e W4 Y26', ...),
            ('Latest 26 Wks - w/e W4 Y26', ...),
            ('Latest 26 Wks - w/e W4 Y26', ...),
            ('Latest 26 Wks - w/e W4 Y26', ...),
            ('Latest 26 Wks - w/e W4 Y26', ...)],
           )

C:\Users\rdi5001\AppData\Roaming\Python\Python311\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Web Extension extension is not supported and will be removed
  warn(msg)

In [66]:
df1

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
     Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3069       People Group                EUR        Total Panel
3070       People Group                EUR        Total Panel
3071       People Group                EUR        Total Panel
3072       People Group                EUR        Total Panel
3073       People Group                EUR        Total Panel

     Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
     Unnamed: 3_level_1 Unnamed: 4_level_1    Unnamed: 5_level_1
     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3069      Total Outlets     SKIN CLEANSING                WELEDA
3070      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3071      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3072      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3073      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_0                Penetration  \
                   Unnamed: 6_level_1               Total Europe
                   Unnamed: 6_level_2         Unnamed: 7_level_2
                                BRAND Latest 52 Wks - w/e W4 Y26
0                        SCOTCH BRITE                      3.912
1                           ALL OTHER                     18.583
2            AJAX (COLGATE PALMOLIVE)                      0.193
3           BRAVO (COLGATE PALMOLIVE)                      0.825
4              MARIGOLD (FREUDENBERG)                      0.054
...                               ...                        ...
3069                           WELEDA                      0.106
3070                           FISSAN                      0.088
3071     PONDS (YELLOW WOOD PARTNERS)                      0.002
3072  ST. IVES (YELLOW WOOD PARTNERS)                      0.256
3073                DAISE (ZURU EDGE)                      0.087

                                                            \

             Unnamed: 8_level_2                     France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         2.304                      2.819
1                        11.894                     29.041
2                         0.104                        NaN
3                         0.502                        NaN
4                         0.028                        NaN
...                         ...                        ...
3069                      0.078                        NaN
3070                      0.048                        NaN
3071                      0.001                        NaN
3072                      0.160                        NaN
3073                      0.059                      0.005

                                                            \

                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         1.347                      0.578
1                        19.432                     25.447
2                           NaN                        NaN
3                           NaN                        NaN
4                           NaN                      0.279
...                         ...                        ...
3069                        NaN                      0.089
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                      1.327
3073                      0.005                      0.450

                                                            \

                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.328                      0.025
1                        16.651                      8.716
2                           NaN                        NaN
3                           NaN                        NaN
4                         0.145                        NaN
...                         ...                        ...
3069                      0.052                      0.207
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.832                        NaN
3073                      0.302                        NaN

                                                            \

                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                      6.966
1                         5.621                     24.480
2                           NaN                        NaN
3                           NaN                      3.350
4                           NaN                        NaN
...                         ...                        ...
3069                      0.162                      0.085
3070                        NaN                      0.523
3071                        NaN                        NaN
3072                        NaN                      0.008
3073                        NaN                        NaN

                                                            \

                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         4.423                     12.530
1                        15.143                     10.364
2                           NaN                      1.590
3                         2.184                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.034
3070                      0.289                        NaN
3071                        NaN                      0.011
3072                      0.005                        NaN
3073                        NaN                        NaN

                                Penetration vs YA (Abs Change)  \
                                                  Total Europe
                                           Unnamed: 19_level_2
     Latest 26 Wks - w/e W4 Y26     Latest 52 Wks - w/e W4 Y26
0                         7.331                         -0.216
1                         5.643                          1.210
2                         0.860                          0.016
3                           NaN                         -0.102
4                           NaN                         -0.001
...                         ...                            ...
3069                      0.002                         -0.048
3070                        NaN                         -0.025
3071                      0.002                          0.000
3072                        NaN                         -0.014
3073                        NaN                          0.087

                                                            \

            Unnamed: 20_level_2                     France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                     -0.251000                     -0.136
1                      0.627000                      3.909
2                     -0.001000                     -0.006
3                     -0.071000                        NaN
4                     -0.004000                        NaN
...                         ...                        ...
3069                  -0.004000                        NaN
3070                  -0.031000                        NaN
3071                   0.000071                        NaN
3072                   0.011000                        NaN
3073                   0.059000                      0.005

                                                            \

                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.365                     -0.170
1                         1.383                      1.192
2                        -0.006                        NaN
3                           NaN                        NaN
4                           NaN                     -0.006
...                         ...                        ...
3069                        NaN                      0.035
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                     -0.072
3073                      0.005                      0.450

                                                            \

                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.083                      0.000
1                         0.843                      0.877
2                           NaN                        NaN
3                           NaN                        NaN
4                        -0.022                        NaN
...                         ...                        ...
3069                      0.016                     -0.234
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.058                        NaN
3073                      0.302                        NaN

                                                            \

                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                     -1.439
1                         1.342                      1.566
2                           NaN                        NaN
3                           NaN                      0.180
4                           NaN                        NaN
...                         ...                        ...
3069                     -0.088                      0.053
3070                        NaN                     -0.147
3071                        NaN                        NaN
3072                        NaN                      0.000
3073                        NaN                        NaN

                                                            \

                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.775                      0.306
1                         0.724                     -1.347
2                           NaN                      0.139
3                         0.290                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.008
3070                     -0.185                        NaN
3071                        NaN                     -0.005
3072                     -0.004                        NaN
3073                        NaN                        NaN




     Latest 26 Wks - w/e W4 Y26
0                        -0.282
1                        -1.591
2                        -0.001
3                           NaN
4                           NaN
...                         ...
3069                      0.002
3070                        NaN
3071                     -0.008
3072                        NaN
3073                        NaN

[3074 rows x 31 columns]

In [67]:
df1

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
     Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3069       People Group                EUR        Total Panel
3070       People Group                EUR        Total Panel
3071       People Group                EUR        Total Panel
3072       People Group                EUR        Total Panel
3073       People Group                EUR        Total Panel

     Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
     Unnamed: 3_level_1 Unnamed: 4_level_1    Unnamed: 5_level_1
     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3069      Total Outlets     SKIN CLEANSING                WELEDA
3070      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3071      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3072      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3073      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_0                Penetration  \
                   Unnamed: 6_level_1               Total Europe
                   Unnamed: 6_level_2         Unnamed: 7_level_2
                                BRAND Latest 52 Wks - w/e W4 Y26
0                        SCOTCH BRITE                      3.912
1                           ALL OTHER                     18.583
2            AJAX (COLGATE PALMOLIVE)                      0.193
3           BRAVO (COLGATE PALMOLIVE)                      0.825
4              MARIGOLD (FREUDENBERG)                      0.054
...                               ...                        ...
3069                           WELEDA                      0.106
3070                           FISSAN                      0.088
3071     PONDS (YELLOW WOOD PARTNERS)                      0.002
3072  ST. IVES (YELLOW WOOD PARTNERS)                      0.256
3073                DAISE (ZURU EDGE)                      0.087

                                                            \

             Unnamed: 8_level_2                     France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         2.304                      2.819
1                        11.894                     29.041
2                         0.104                        NaN
3                         0.502                        NaN
4                         0.028                        NaN
...                         ...                        ...
3069                      0.078                        NaN
3070                      0.048                        NaN
3071                      0.001                        NaN
3072                      0.160                        NaN
3073                      0.059                      0.005

                                                            \

                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         1.347                      0.578
1                        19.432                     25.447
2                           NaN                        NaN
3                           NaN                        NaN
4                           NaN                      0.279
...                         ...                        ...
3069                        NaN                      0.089
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                      1.327
3073                      0.005                      0.450

                                                            \

                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.328                      0.025
1                        16.651                      8.716
2                           NaN                        NaN
3                           NaN                        NaN
4                         0.145                        NaN
...                         ...                        ...
3069                      0.052                      0.207
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.832                        NaN
3073                      0.302                        NaN

                                                            \

                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                      6.966
1                         5.621                     24.480
2                           NaN                        NaN
3                           NaN                      3.350
4                           NaN                        NaN
...                         ...                        ...
3069                      0.162                      0.085
3070                        NaN                      0.523
3071                        NaN                        NaN
3072                        NaN                      0.008
3073                        NaN                        NaN

                                                            \

                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         4.423                     12.530
1                        15.143                     10.364
2                           NaN                      1.590
3                         2.184                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.034
3070                      0.289                        NaN
3071                        NaN                      0.011
3072                      0.005                        NaN
3073                        NaN                        NaN

                                Penetration vs YA (Abs Change)  \
                                                  Total Europe
                                           Unnamed: 19_level_2
     Latest 26 Wks - w/e W4 Y26     Latest 52 Wks - w/e W4 Y26
0                         7.331                         -0.216
1                         5.643                          1.210
2                         0.860                          0.016
3                           NaN                         -0.102
4                           NaN                         -0.001
...                         ...                            ...
3069                      0.002                         -0.048
3070                        NaN                         -0.025
3071                      0.002                          0.000
3072                        NaN                         -0.014
3073                        NaN                          0.087

                                                            \

            Unnamed: 20_level_2                     France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                     -0.251000                     -0.136
1                      0.627000                      3.909
2                     -0.001000                     -0.006
3                     -0.071000                        NaN
4                     -0.004000                        NaN
...                         ...                        ...
3069                  -0.004000                        NaN
3070                  -0.031000                        NaN
3071                   0.000071                        NaN
3072                   0.011000                        NaN
3073                   0.059000                      0.005

                                                            \

                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.365                     -0.170
1                         1.383                      1.192
2                        -0.006                        NaN
3                           NaN                        NaN
4                           NaN                     -0.006
...                         ...                        ...
3069                        NaN                      0.035
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                     -0.072
3073                      0.005                      0.450

                                                            \

                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.083                      0.000
1                         0.843                      0.877
2                           NaN                        NaN
3                           NaN                        NaN
4                        -0.022                        NaN
...                         ...                        ...
3069                      0.016                     -0.234
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.058                        NaN
3073                      0.302                        NaN

                                                            \

                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                     -1.439
1                         1.342                      1.566
2                           NaN                        NaN
3                           NaN                      0.180
4                           NaN                        NaN
...                         ...                        ...
3069                     -0.088                      0.053
3070                        NaN                     -0.147
3071                        NaN                        NaN
3072                        NaN                      0.000
3073                        NaN                        NaN

                                                            \

                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.775                      0.306
1                         0.724                     -1.347
2                           NaN                      0.139
3                         0.290                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.008
3070                     -0.185                        NaN
3071                        NaN                     -0.005
3072                     -0.004                        NaN
3073                        NaN                        NaN




     Latest 26 Wks - w/e W4 Y26
0                        -0.282
1                        -1.591
2                        -0.001
3                           NaN
4                           NaN
...                         ...
3069                      0.002
3070                        NaN
3071                     -0.008
3072                        NaN
3073                        NaN

[3074 rows x 31 columns]

In [68]:
# Replace Unnamed columns in the 3rd header level (level index 2) after column 7 with 'Total Europe'
if isinstance(df1.columns, pd.MultiIndex):
    cols = list(df1.columns)
    new_cols = []
    for i, col in enumerate(cols):
        col_list = list(col)
        if i >= 7 and len(col_list) > 2 and isinstance(col_list[2], str) and col_list[2].startswith('Unnamed'):
            col_list[2] = col_list[1]
        new_cols.append(tuple(col_list))
    df1.columns = pd.MultiIndex.from_tuples(new_cols)

# display updated dataframe
df1

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
     Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3069       People Group                EUR        Total Panel
3070       People Group                EUR        Total Panel
3071       People Group                EUR        Total Panel
3072       People Group                EUR        Total Panel
3073       People Group                EUR        Total Panel

     Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
     Unnamed: 3_level_1 Unnamed: 4_level_1    Unnamed: 5_level_1
     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3069      Total Outlets     SKIN CLEANSING                WELEDA
3070      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3071      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3072      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3073      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_0                Penetration  \
                   Unnamed: 6_level_1               Total Europe
                   Unnamed: 6_level_2               Total Europe
                                BRAND Latest 52 Wks - w/e W4 Y26
0                        SCOTCH BRITE                      3.912
1                           ALL OTHER                     18.583
2            AJAX (COLGATE PALMOLIVE)                      0.193
3           BRAVO (COLGATE PALMOLIVE)                      0.825
4              MARIGOLD (FREUDENBERG)                      0.054
...                               ...                        ...
3069                           WELEDA                      0.106
3070                           FISSAN                      0.088
3071     PONDS (YELLOW WOOD PARTNERS)                      0.002
3072  ST. IVES (YELLOW WOOD PARTNERS)                      0.256
3073                DAISE (ZURU EDGE)                      0.087

                                                            \

                                                    France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         2.304                      2.819
1                        11.894                     29.041
2                         0.104                        NaN
3                         0.502                        NaN
4                         0.028                        NaN
...                         ...                        ...
3069                      0.078                        NaN
3070                      0.048                        NaN
3071                      0.001                        NaN
3072                      0.160                        NaN
3073                      0.059                      0.005

                                                            \

                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         1.347                      0.578
1                        19.432                     25.447
2                           NaN                        NaN
3                           NaN                        NaN
4                           NaN                      0.279
...                         ...                        ...
3069                        NaN                      0.089
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                      1.327
3073                      0.005                      0.450

                                                            \

                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.328                      0.025
1                        16.651                      8.716
2                           NaN                        NaN
3                           NaN                        NaN
4                         0.145                        NaN
...                         ...                        ...
3069                      0.052                      0.207
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.832                        NaN
3073                      0.302                        NaN

                                                            \

                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                      6.966
1                         5.621                     24.480
2                           NaN                        NaN
3                           NaN                      3.350
4                           NaN                        NaN
...                         ...                        ...
3069                      0.162                      0.085
3070                        NaN                      0.523
3071                        NaN                        NaN
3072                        NaN                      0.008
3073                        NaN                        NaN

                                                            \

                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         4.423                     12.530
1                        15.143                     10.364
2                           NaN                      1.590
3                         2.184                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.034
3070                      0.289                        NaN
3071                        NaN                      0.011
3072                      0.005                        NaN
3073                        NaN                        NaN

                                Penetration vs YA (Abs Change)  \
                                                  Total Europe
                                                  Total Europe
     Latest 26 Wks - w/e W4 Y26     Latest 52 Wks - w/e W4 Y26
0                         7.331                         -0.216
1                         5.643                          1.210
2                         0.860                          0.016
3                           NaN                         -0.102
4                           NaN                         -0.001
...                         ...                            ...
3069                      0.002                         -0.048
3070                        NaN                         -0.025
3071                      0.002                          0.000
3072                        NaN                         -0.014
3073                        NaN                          0.087

                                                            \

                                                    France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                     -0.251000                     -0.136
1                      0.627000                      3.909
2                     -0.001000                     -0.006
3                     -0.071000                        NaN
4                     -0.004000                        NaN
...                         ...                        ...
3069                  -0.004000                        NaN
3070                  -0.031000                        NaN
3071                   0.000071                        NaN
3072                   0.011000                        NaN
3073                   0.059000                      0.005

                                                            \

                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.365                     -0.170
1                         1.383                      1.192
2                        -0.006                        NaN
3                           NaN                        NaN
4                           NaN                     -0.006
...                         ...                        ...
3069                        NaN                      0.035
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                     -0.072
3073                      0.005                      0.450

                                                            \

                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.083                      0.000
1                         0.843                      0.877
2                           NaN                        NaN
3                           NaN                        NaN
4                        -0.022                        NaN
...                         ...                        ...
3069                      0.016                     -0.234
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.058                        NaN
3073                      0.302                        NaN

                                                            \

                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                     -1.439
1                         1.342                      1.566
2                           NaN                        NaN
3                           NaN                      0.180
4                           NaN                        NaN
...                         ...                        ...
3069                     -0.088                      0.053
3070                        NaN                     -0.147
3071                        NaN                        NaN
3072                        NaN                      0.000
3073                        NaN                        NaN

                                                            \

                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.775                      0.306
1                         0.724                     -1.347
2                           NaN                      0.139
3                         0.290                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.008
3070                     -0.185                        NaN
3071                        NaN                     -0.005
3072                     -0.004                        NaN
3073                        NaN                        NaN




     Latest 26 Wks - w/e W4 Y26
0                        -0.282
1                        -1.591
2                        -0.001
3                           NaN
4                           NaN
...                         ...
3069                      0.002
3070                        NaN
3071                     -0.008
3072                        NaN
3073                        NaN

[3074 rows x 31 columns]

In [69]:
# Create a new view of df1 keeping header levels 1, 3, and 4 (human numbering)
# -> which are 0-based levels 0, 2, and 3 in pandas
if isinstance(df1.columns, pd.MultiIndex) and df1.columns.nlevels >= 1:
    nlevels = df1.columns.nlevels
 
    # Desired keep-levels (0-based): keep 1st, 3rd, 4th -> [0, 2, 3]
    keep_levels = [lvl for lvl in [0, 2, 3] if lvl < nlevels]
 
    # If nothing to drop (e.g., not enough levels), just copy
    if len(keep_levels) == nlevels:
        df1_trimmed = df1.copy()
    else:
        drop_levels = [lvl for lvl in range(nlevels) if lvl not in keep_levels]
        df1_trimmed = df1.copy()
        df1_trimmed.columns = df1_trimmed.columns.droplevel(drop_levels)
else:
    df1_trimmed = df1.copy()
 
df1_trimmed

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3069       People Group                EUR        Total Panel
3070       People Group                EUR        Total Panel
3071       People Group                EUR        Total Panel
3072       People Group                EUR        Total Panel
3073       People Group                EUR        Total Panel

     Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3069      Total Outlets     SKIN CLEANSING                WELEDA
3070      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3071      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3072      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3073      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_0                Penetration  \
                   Unnamed: 6_level_2               Total Europe
                                BRAND Latest 52 Wks - w/e W4 Y26
0                        SCOTCH BRITE                      3.912
1                           ALL OTHER                     18.583
2            AJAX (COLGATE PALMOLIVE)                      0.193
3           BRAVO (COLGATE PALMOLIVE)                      0.825
4              MARIGOLD (FREUDENBERG)                      0.054
...                               ...                        ...
3069                           WELEDA                      0.106
3070                           FISSAN                      0.088
3071     PONDS (YELLOW WOOD PARTNERS)                      0.002
3072  ST. IVES (YELLOW WOOD PARTNERS)                      0.256
3073                DAISE (ZURU EDGE)                      0.087

                                                            \
                                                    France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         2.304                      2.819
1                        11.894                     29.041
2                         0.104                        NaN
3                         0.502                        NaN
4                         0.028                        NaN
...                         ...                        ...
3069                      0.078                        NaN
3070                      0.048                        NaN
3071                      0.001                        NaN
3072                      0.160                        NaN
3073                      0.059                      0.005

                                                            \
                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         1.347                      0.578
1                        19.432                     25.447
2                           NaN                        NaN
3                           NaN                        NaN
4                           NaN                      0.279
...                         ...                        ...
3069                        NaN                      0.089
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                      1.327
3073                      0.005                      0.450

                                                            \
                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.328                      0.025
1                        16.651                      8.716
2                           NaN                        NaN
3                           NaN                        NaN
4                         0.145                        NaN
...                         ...                        ...
3069                      0.052                      0.207
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.832                        NaN
3073                      0.302                        NaN

                                                            \
                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                      6.966
1                         5.621                     24.480
2                           NaN                        NaN
3                           NaN                      3.350
4                           NaN                        NaN
...                         ...                        ...
3069                      0.162                      0.085
3070                        NaN                      0.523
3071                        NaN                        NaN
3072                        NaN                      0.008
3073                        NaN                        NaN

                                                            \
                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         4.423                     12.530
1                        15.143                     10.364
2                           NaN                      1.590
3                         2.184                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.034
3070                      0.289                        NaN
3071                        NaN                      0.011
3072                      0.005                        NaN
3073                        NaN                        NaN

                                Penetration vs YA (Abs Change)  \
                                                  Total Europe
     Latest 26 Wks - w/e W4 Y26     Latest 52 Wks - w/e W4 Y26
0                         7.331                         -0.216
1                         5.643                          1.210
2                         0.860                          0.016
3                           NaN                         -0.102
4                           NaN                         -0.001
...                         ...                            ...
3069                      0.002                         -0.048
3070                        NaN                         -0.025
3071                      0.002                          0.000
3072                        NaN                         -0.014
3073                        NaN                          0.087

                                                            \
                                                    France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                     -0.251000                     -0.136
1                      0.627000                      3.909
2                     -0.001000                     -0.006
3                     -0.071000                        NaN
4                     -0.004000                        NaN
...                         ...                        ...
3069                  -0.004000                        NaN
3070                  -0.031000                        NaN
3071                   0.000071                        NaN
3072                   0.011000                        NaN
3073                   0.059000                      0.005

                                                            \
                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.365                     -0.170
1                         1.383                      1.192
2                        -0.006                        NaN
3                           NaN                        NaN
4                           NaN                     -0.006
...                         ...                        ...
3069                        NaN                      0.035
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                     -0.072
3073                      0.005                      0.450

                                                            \
                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.083                      0.000
1                         0.843                      0.877
2                           NaN                        NaN
3                           NaN                        NaN
4                        -0.022                        NaN
...                         ...                        ...
3069                      0.016                     -0.234
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.058                        NaN
3073                      0.302                        NaN

                                                            \
                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                     -1.439
1                         1.342                      1.566
2                           NaN                        NaN
3                           NaN                      0.180
4                           NaN                        NaN
...                         ...                        ...
3069                     -0.088                      0.053
3070                        NaN                     -0.147
3071                        NaN                        NaN
3072                        NaN                      0.000
3073                        NaN                        NaN

                                                            \
                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.775                      0.306
1                         0.724                     -1.347
2                           NaN                      0.139
3                         0.290                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.008
3070                     -0.185                        NaN
3071                        NaN                     -0.005
3072                     -0.004                        NaN
3073                        NaN                        NaN



     Latest 26 Wks - w/e W4 Y26
0                        -0.282
1                        -1.591
2                        -0.001
3                           NaN
4                           NaN
...                         ...
3069                      0.002
3070                        NaN
3071                     -0.008
3072                        NaN
3073                        NaN

[3074 rows x 31 columns]

In [70]:
# alternative transformation using melt, treating first 7 columns as metadata
# use df_base from earlier steps

df_base = df1_trimmed

 
# determine metadata and data columns by position
metadata_cols = list(df_base.columns[:7])
# we'll slice by position for data rather than by labels
data_cols_raw = list(df_base.columns[7:])
 
print("Metadata cols:", metadata_cols)
print("First few raw data cols:", data_cols_raw[:5])
 
# --- RENAMING RULE (updated) ---
# Rename the header2 (metric) by appending " vs YA" **iff** the string "YA" is present in header0 (Header0).
# Works for 2- or 3-level MultiIndex columns; your case is 3-level: (Header0, Header1/Country, Header2/Metric).
nlevels = getattr(df_base.columns, "nlevels", 1)
 
renamed_data = []
for col in data_cols_raw:
    if isinstance(col, tuple):
        if nlevels >= 3 and len(col) >= 3:
            head0, country, metric = col[0], col[1], col[2]
        elif len(col) == 2:
            head0, country, metric = col[0], col[0], col[1]
        else:
            head0 = col[0] if len(col) >= 1 else ""
            country = col[-2] if len(col) >= 2 else ""
            metric = col[-1] if len(col) >= 1 else col
    else:
        head0, country, metric = "", "", col
 
    # If header0 contains "YA", append " vs YA" to the metric name
    if "YA" in str(head0).upper():
        metric = f"{metric} vs YA"
 
    renamed_data.append((country, metric))
 
# slice the data portion of df_base and then rename its columns
df_data = df_base.iloc[:, 7:].copy()
df_data.columns = pd.MultiIndex.from_tuples(renamed_data)
 
# also extract df_meta for later use
df_meta = df_base.iloc[:, :7].copy()
 
# ---- IMPORTANT CHANGE: use the LAST LEVEL for meta names (Header2) ----
# This yields: People, Currency, Total Panel, Total Outlets, CATEGORY, BRAND OWNER, BRAND
def _last_level_name(col):
    if isinstance(col, tuple):
        return col[-1]
    return col
 
meta_display_names = [_last_level_name(col) for col in metadata_cols]
 
# flatten df_data columns
flat_cols = [f"{c0}|||{c1}" for c0, c1 in renamed_data]
df_flat = df_data.copy()
df_flat.columns = flat_cols
 
# add meta columns to flat using LAST LEVEL names
for col, disp in zip(metadata_cols, meta_display_names):
    df_flat[f"meta|||{disp}"] = df_meta[col].squeeze().values
 
# preserve row identifier
df_flat = df_flat.reset_index(drop=True)
df_flat['row_id'] = df_flat.index
 
# melt on metric columns
id_vars = ['row_id'] + [f"meta|||{disp}" for disp in meta_display_names]
df_melt = df_flat.melt(id_vars=id_vars, var_name='combined', value_name='value')
 
# split combined into country and metric
split_cols = df_melt['combined'].str.split('\\|\\|\\|', expand=True)
df_melt['country'] = split_cols[0]
df_melt['metric'] = split_cols[1]
 
# pivot back
df_final = df_melt.pivot_table(
    index=id_vars + ['country'],
    columns='metric',
    values='value',
    aggfunc='first'
).reset_index()
 
# clean metadata column names: remove the "meta|||" prefix using the same display names
for disp in meta_display_names:
    df_final = df_final.rename(columns={f"meta|||{disp}": disp})
 
print("Transformed final shape:", df_final.shape)
df_final

Metadata cols: [('Unnamed: 0_level_0', 'Unnamed: 0_level_2', 'People'), ('Unnamed: 1_level_0', 'Unnamed: 1_level_2', 'Currency'), ('Unnamed: 2_level_0', 'Unnamed: 2_level_2', 'Total Panel'), ('Unnamed: 3_level_0', 'Unnamed: 3_level_2', 'Total Outlets'), ('Unnamed: 4_level_0', 'Unnamed: 4_level_2', 'CATEGORY'), ('Unnamed: 5_level_0', 'Unnamed: 5_level_2', 'BRAND OWNER'), ('Unnamed: 6_level_0', 'Unnamed: 6_level_2', 'BRAND')]
First few raw data cols: [('Penetration', 'Total Europe', 'Latest 52 Wks - w/e W4 Y26'), ('Penetration', 'Total Europe', 'Latest 26 Wks - w/e W4 Y26'), ('Penetration', 'France', 'Latest 52 Wks - w/e W4 Y26'), ('Penetration', 'France', 'Latest 26 Wks - w/e W4 Y26'), ('Penetration', 'GB', 'Latest 52 Wks - w/e W4 Y26')]
Transformed final shape: (8339, 13)

metric,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks - w/e W4 Y26,Latest 26 Wks - w/e W4 Y26 vs YA,Latest 52 Wks - w/e W4 Y26,Latest 52 Wks - w/e W4 Y26 vs YA
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,-0.365,2.819,-0.136
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,-0.083,0.578,-0.170
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.011,0.256,-0.014
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.005,0.005,0.005
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.302,0.450,0.450
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.059,0.087,0.087

In [71]:
df_final

metric,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks - w/e W4 Y26,Latest 26 Wks - w/e W4 Y26 vs YA,Latest 52 Wks - w/e W4 Y26,Latest 52 Wks - w/e W4 Y26 vs YA
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,-0.365,2.819,-0.136
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,-0.083,0.578,-0.170
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.011,0.256,-0.014
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.005,0.005,0.005
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.302,0.450,0.450
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.059,0.087,0.087

In [72]:
df_final.columns=['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country',
       'Latest 26 Wks', 'Latest 26 vs YA',
       'Latest 52 Wks', 'Latest 52 vs YA']

In [73]:
df_final = df_final.fillna(0)

print("NaN values after filling:")
print(df_final.isna().sum())

NaN values after filling:
row_id             0
People             0
Currency           0
Total Panel        0
Total Outlets      0
CATEGORY           0
BRAND OWNER        0
BRAND              0
country            0
Latest 26 Wks      0
Latest 26 vs YA    0
Latest 52 Wks      0
Latest 52 vs YA    0
dtype: int64

# >2pp

In [74]:
tangible_threshold = 2
df_final['Tangible Brands'] = df_final['Latest 52 Wks'].apply(lambda x: 'Yes' if x > tangible_threshold else 'No')

# display a sample
df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,-0.365,2.819,-0.136,Yes
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,-0.083,0.578,-0.170,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439,Yes
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000,No
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.011,0.256,-0.014,No
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.005,0.005,0.005,No
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.302,0.450,0.450,No
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.059,0.087,0.087,No

In [75]:
df_final.columns

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands'],
      dtype='object')

# Growing penetration, Latest 26w vs year ago should be greater than .2

In [76]:
growing_threshold = 0.2
df_final['Growing Penetration'] = df_final['Latest 26 vs YA'].apply(lambda x: 'Yes' if x > growing_threshold else 'No')

df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,-0.365,2.819,-0.136,Yes,No
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,-0.083,0.578,-0.170,No,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000,No,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439,Yes,No
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000,No,No
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.011,0.256,-0.014,No,No
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.005,0.005,0.005,No,No
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.302,0.450,0.450,No,Yes
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.059,0.087,0.087,No,No

In [77]:
df_final['Growing Penetration'].value_counts()

Growing Penetration
No     7636
Yes     703
Name: count, dtype: int64

# Accelerating Penetration
- Penetration growth in latest 26 weeks vs YA  is greater than penetration change in latest 52. Consider only YA.

In [78]:
df_final['Accelerating Penetration'] = (df_final['Latest 26 vs YA'] > df_final['Latest 52 vs YA']).apply(lambda x: 'Yes' if x else 'No')

df_final[['BRAND', 'country', 'Latest 26 vs YA', 'Latest 52 vs YA', 'Accelerating Penetration']].head(10)

,BRAND,country,Latest 26 vs YA,Latest 52 vs YA,Accelerating Penetration
0,SCOTCH BRITE,France,-0.365,-0.136,No
1,SCOTCH BRITE,GB,-0.083,-0.170,Yes
2,SCOTCH BRITE,Germany,0.025,0.000,Yes
3,SCOTCH BRITE,Italy,-0.775,-1.439,Yes
4,SCOTCH BRITE,Spain,-0.282,0.306,No
5,SCOTCH BRITE,Total Europe,-0.251,-0.216,No
6,ALL OTHER,France,1.383,3.909,No
7,ALL OTHER,GB,0.843,1.192,No
8,ALL OTHER,Germany,1.342,0.877,Yes
9,ALL OTHER,Italy,0.724,1.566,No

In [79]:
df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,-0.365,2.819,-0.136,Yes,No,No
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,-0.083,0.578,-0.170,No,No,Yes
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000,No,No,Yes
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439,Yes,No,Yes
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000,No,No,No
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.011,0.256,-0.014,No,No,Yes
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.005,0.005,0.005,No,No,No
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.302,0.450,0.450,No,Yes,No
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.059,0.087,0.087,No,No,No

In [80]:
df_final['Top Opportunity'] = (
    (df_final['Tangible Brands'] == 'Yes') & 
    (df_final['Growing Penetration'] == 'Yes') & 
    (df_final['Accelerating Penetration'] == 'Yes')
).apply(lambda x: 'Yes' if x else 'No')

# display sample with all columns
df_final[['BRAND', 'country', 'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration', 'Top Opportunity']].head(10)

,BRAND,country,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity
0,SCOTCH BRITE,France,Yes,No,No,No
1,SCOTCH BRITE,GB,No,No,Yes,No
2,SCOTCH BRITE,Germany,No,No,Yes,No
3,SCOTCH BRITE,Italy,Yes,No,Yes,No
4,SCOTCH BRITE,Spain,Yes,No,No,No
5,SCOTCH BRITE,Total Europe,Yes,No,No,No
6,ALL OTHER,France,Yes,Yes,No,No
7,ALL OTHER,GB,Yes,Yes,No,No
8,ALL OTHER,Germany,Yes,Yes,Yes,Yes
9,ALL OTHER,Italy,Yes,Yes,No,No

In [81]:
Top_Oppurtunity=df_final[df_final['Top Opportunity']=='Yes']
Top_Oppurtunity

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity
8,1,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,Germany,5.621,1.342,8.716,0.877,Yes,Yes,Yes,Yes
15,3,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,COLGATE PALMOLIVE,BRAVO (COLGATE PALMOLIVE),Italy,2.184,0.290,3.350,0.180,Yes,Yes,Yes,Yes
21,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,4.371,0.630,6.745,0.319,Yes,Yes,Yes,Yes
30,7,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,Italy,11.639,1.371,17.913,0.985,Yes,Yes,Yes,Yes
61,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),GB,10.823,1.357,12.955,0.586,Yes,Yes,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7815,2887,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ALL OTHER,ALL OTHER,GB,17.044,0.747,25.194,0.107,Yes,Yes,Yes,Yes
7866,2903,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,BOLTON GROUP,ACQUA ALLE ROSE,Italy,1.817,0.391,3.015,0.164,Yes,Yes,Yes,Yes
8055,2974,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,KIMBERLY CLARK,HUGGIES,Italy,1.356,0.337,2.063,0.259,Yes,Yes,Yes,Yes
8106,2988,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,MIXA (L'OREAL / L'OREAL),France,5.101,0.223,7.754,0.194,Yes,Yes,Yes,Yes
8133,2998,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,LEA NATURE,SO'BIO ETIC,France,1.536,0.252,2.637,0.177,Yes,Yes,Yes,Yes

# df2

In [82]:
# Process df2: Keep MultiIndex to properly extract header0 and header1
df2_copy = df2.copy()

print("df2 original columns (first 12):", df2_copy.columns[:12].tolist())
print("df2 MultiIndex nlevels:", df2_copy.columns.nlevels)

# Identify metadata columns (first 8 by position)
metadata_cols = list(df2_copy.columns[:8])
data_cols = list(df2_copy.columns[8:])

print("\nMetadata columns:", metadata_cols)
print("Data columns count:", len(data_cols))
print("Data columns sample (tuples):", data_cols[:5])

# Process the data columns: extract header0 (time period) + header1 (metric)
renamed_cols = []

for col in data_cols:
    h0, h1 = col[0], col[1]  # col is a tuple (header0, header1)
    
    # Split header0 at '-' and take the first part
    time_period = h0.split('-')[0].strip()
    
    # Combine metric + time period
    new_col = f"{h1} {time_period}"
    renamed_cols.append(new_col)

print("\nRenamed data columns (first 10):", renamed_cols[:10])

# Create new dataframe with renamed columns
df2_meta = df2_copy.iloc[:, :8].copy()
df2_data = df2_copy.iloc[:, 8:].copy()

# Flatten column names to single level
df2_meta.columns = [col[1] for col in df2_meta.columns]
df2_data.columns = renamed_cols

# Concatenate metadata and data
df2_processed = pd.concat([df2_meta, df2_data], axis=1)

print("\ndf2_processed shape:", df2_processed.shape)
print("df2_processed columns:", df2_processed.columns.tolist())
print("\nSample of df2_processed:")
df2_processed

df2 original columns (first 12): [('Unnamed: 0_level_0', 'People'), ('Unnamed: 1_level_0', 'Currency'), ('Unnamed: 2_level_0', 'Total Panel'), ('Unnamed: 3_level_0', 'Total Outlets'), ('Unnamed: 4_level_0', 'Countries'), ('Unnamed: 5_level_0', 'CATEGORY'), ('Unnamed: 6_level_0', 'BRAND OWNER'), ('Unnamed: 7_level_0', 'BRAND'), ('Latest 52 Wks - w/e W4 Y26', 'Penetration'), ('Latest 52 Wks - w/e W4 Y26', 'Value vs YA (Abs Change)'), ('Latest 52 Wks - w/e W4 Y26', 'Value due to Buyers YA'), ('Latest 52 Wks - w/e W4 Y26', 'Value due to Occasions per Buyer YA')]
df2 MultiIndex nlevels: 2

Metadata columns: [('Unnamed: 0_level_0', 'People'), ('Unnamed: 1_level_0', 'Currency'), ('Unnamed: 2_level_0', 'Total Panel'), ('Unnamed: 3_level_0', 'Total Outlets'), ('Unnamed: 4_level_0', 'Countries'), ('Unnamed: 5_level_0', 'CATEGORY'), ('Unnamed: 6_level_0', 'BRAND OWNER'), ('Unnamed: 7_level_0', 'BRAND')]
Data columns count: 10
Data columns sample (tuples): [('Latest 52 Wks - w/e W4 Y26', 'Penetration'), ('Latest 52 Wks - w/e W4 Y26', 'Value vs YA (Abs Change)'), ('Latest 52 Wks - w/e W4 Y26', 'Value due to Buyers YA'), ('Latest 52 Wks - w/e W4 Y26', 'Value due to Occasions per Buyer YA'), ('Latest 52 Wks - w/e W4 Y26', 'Value due to Value per Occasion YA')]

Renamed data columns (first 10): ['Penetration Latest 52 Wks', 'Value vs YA (Abs Change) Latest 52 Wks', 'Value due to Buyers YA Latest 52 Wks', 'Value due to Occasions per Buyer YA Latest 52 Wks', 'Value due to Value per Occasion YA Latest 52 Wks', 'Penetration Latest 26 Wks', 'Value vs YA (Abs Change) Latest 26 Wks', 'Value due to Buyers YA Latest 26 Wks', 'Value due to Occasions per Buyer YA Latest 26 Wks', 'Value due to Value per Occasion YA Latest 26 Wks']

df2_processed shape: (5265, 18)
df2_processed columns: ['People', 'Currency', 'Total Panel', 'Total Outlets', 'Countries', 'CATEGORY', 'BRAND OWNER', 'BRAND', 'Penetration Latest 52 Wks', 'Value vs YA (Abs Change) Latest 52 Wks', 'Value due to Buyers YA Latest 52 Wks', 'Value due to Occasions per Buyer YA Latest 52 Wks', 'Value due to Value per Occasion YA Latest 52 Wks', 'Penetration Latest 26 Wks', 'Value vs YA (Abs Change) Latest 26 Wks', 'Value due to Buyers YA Latest 26 Wks', 'Value due to Occasions per Buyer YA Latest 26 Wks', 'Value due to Value per Occasion YA Latest 26 Wks']

Sample of df2_processed:

,People,Currency,Total Panel,Total Outlets,Countries,CATEGORY,BRAND OWNER,BRAND,Penetration Latest 52 Wks,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Penetration Latest 26 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks
0,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,3M,SCOTCH BRITE,2.819,-2.816270e+05,-125211.791,-6940.783,-149477.240,1.347,-467747.807,-387638.647,92471.589,-172577.218
1,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,29.041,1.402825e+07,5187110.253,4381444.346,4459689.949,19.432,5185968.980,1594138.737,1249741.075,2342089.327
2,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,COLGATE PALMOLIVE,AJAX (COLGATE PALMOLIVE),NaN,-4.565028e+03,NaN,NaN,NaN,NaN,-4565.028,NaN,NaN,NaN
3,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,FREUDENBERG,VILEDA,0.488,2.342170e+05,310890.571,-2794.563,-73880.617,0.300,75419.427,91236.705,-150.418,-15666.805
4,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,37.546,1.144235e+06,-231956.527,-777751.959,2153942.130,26.582,362865.133,-515417.269,-508856.667,1387139.758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5260,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,SODALIS,VITESSE (SODALIS),1.049,-2.577675e+05,-654667.168,373307.212,23593.632,0.864,-63081.555,92476.682,-167001.323,11444.334
5261,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,DOVE (UNILEVER / UNILEVER),NaN,-2.836982e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5262,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,REN (UNILEVER / UNILEVER),0.005,1.886498e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5263,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,WELEDA,WELEDA,0.034,1.966220e+04,19322.068,161.330,181.241,0.002,4269.966,NaN,NaN,NaN
5264,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,YELLOW WOOD PARTNERS,PONDS (YELLOW WOOD PARTNERS),0.011,-2.534527e+03,-3278.416,0.000,745.103,0.002,-4066.432,-4573.227,44.810,466.165

In [83]:
df2_processed=df2_processed.fillna(0)
df2_processed

,People,Currency,Total Panel,Total Outlets,Countries,CATEGORY,BRAND OWNER,BRAND,Penetration Latest 52 Wks,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Penetration Latest 26 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks
0,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,3M,SCOTCH BRITE,2.819,-2.816270e+05,-125211.791,-6940.783,-149477.240,1.347,-467747.807,-387638.647,92471.589,-172577.218
1,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,29.041,1.402825e+07,5187110.253,4381444.346,4459689.949,19.432,5185968.980,1594138.737,1249741.075,2342089.327
2,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,COLGATE PALMOLIVE,AJAX (COLGATE PALMOLIVE),0.000,-4.565028e+03,0.000,0.000,0.000,0.000,-4565.028,0.000,0.000,0.000
3,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,FREUDENBERG,VILEDA,0.488,2.342170e+05,310890.571,-2794.563,-73880.617,0.300,75419.427,91236.705,-150.418,-15666.805
4,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,37.546,1.144235e+06,-231956.527,-777751.959,2153942.130,26.582,362865.133,-515417.269,-508856.667,1387139.758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5260,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,SODALIS,VITESSE (SODALIS),1.049,-2.577675e+05,-654667.168,373307.212,23593.632,0.864,-63081.555,92476.682,-167001.323,11444.334
5261,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,DOVE (UNILEVER / UNILEVER),0.000,-2.836982e+04,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5262,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,REN (UNILEVER / UNILEVER),0.005,1.886498e+04,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5263,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,WELEDA,WELEDA,0.034,1.966220e+04,19322.068,161.330,181.241,0.002,4269.966,0.000,0.000,0.000
5264,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,YELLOW WOOD PARTNERS,PONDS (YELLOW WOOD PARTNERS),0.011,-2.534527e+03,-3278.416,0.000,745.103,0.002,-4066.432,-4573.227,44.810,466.165

In [84]:
df2_processed.columns

Index(['People', 'Currency', 'Total Panel', 'Total Outlets', 'Countries',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'Penetration Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Penetration Latest 26 Wks', 'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks'],
      dtype='object')

In [85]:
Top_Oppurtunity

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity
8,1,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,Germany,5.621,1.342,8.716,0.877,Yes,Yes,Yes,Yes
15,3,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,COLGATE PALMOLIVE,BRAVO (COLGATE PALMOLIVE),Italy,2.184,0.290,3.350,0.180,Yes,Yes,Yes,Yes
21,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,4.371,0.630,6.745,0.319,Yes,Yes,Yes,Yes
30,7,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,Italy,11.639,1.371,17.913,0.985,Yes,Yes,Yes,Yes
61,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),GB,10.823,1.357,12.955,0.586,Yes,Yes,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7815,2887,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ALL OTHER,ALL OTHER,GB,17.044,0.747,25.194,0.107,Yes,Yes,Yes,Yes
7866,2903,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,BOLTON GROUP,ACQUA ALLE ROSE,Italy,1.817,0.391,3.015,0.164,Yes,Yes,Yes,Yes
8055,2974,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,KIMBERLY CLARK,HUGGIES,Italy,1.356,0.337,2.063,0.259,Yes,Yes,Yes,Yes
8106,2988,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,MIXA (L'OREAL / L'OREAL),France,5.101,0.223,7.754,0.194,Yes,Yes,Yes,Yes
8133,2998,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,LEA NATURE,SO'BIO ETIC,France,1.536,0.252,2.637,0.177,Yes,Yes,Yes,Yes

In [86]:
# merge procedure between Top_Oppurtunity (from df_final) and df2_processed
# assume df_final and df2_processed exist

# select necessary columns from df2_processed
right_cols = [
    'Countries','CATEGORY','BRAND',
    'Value vs YA (Abs Change) Latest 52 Wks',
    'Value due to Buyers YA Latest 52 Wks',
    'Value due to Occasions per Buyer YA Latest 52 Wks',
    'Value due to Value per Occasion YA Latest 52 Wks',
    'Value vs YA (Abs Change) Latest 26 Wks',
    'Value due to Buyers YA Latest 26 Wks',
    'Value due to Occasions per Buyer YA Latest 26 Wks',
    'Value due to Value per Occasion YA Latest 26 Wks',
]

# build small right table
df2_small = df2_processed[right_cols].copy()

# perform left merge
Top_Oppurtunity = df_final[df_final['Top Opportunity']=='Yes']

df_merged = Top_Oppurtunity.merge(
    df2_small,
    left_on=['country','CATEGORY','BRAND'],
    right_on=['Countries','CATEGORY','BRAND'],
    how='left'
)

# drop auxiliary column
if 'Countries' in df_merged.columns:
    df_merged = df_merged.drop(columns=['Countries'])

# show result
print(df_merged.columns)
df_merged.head()

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks'],
      dtype='object')

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks
0,1,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,Germany,5.621,1.342,8.716,0.877,Yes,Yes,Yes,Yes,791926.913,1110128.760,2.604244e+05,-578625.594,446782.207,1.470200e+06,1.684292e+05,-1191849.092
1,3,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,COLGATE PALMOLIVE,BRAVO (COLGATE PALMOLIVE),Italy,2.184,0.290,3.350,0.180,Yes,Yes,Yes,Yes,-42369.452,108660.475,-6.857022e+04,-82461.060,78686.554,1.437160e+05,-1.811871e+04,-46911.006
2,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,4.371,0.630,6.745,0.319,Yes,Yes,Yes,Yes,853160.781,444338.965,-4.208332e+05,829654.867,609011.228,7.507220e+05,-4.108906e+05,269179.707
3,7,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,Italy,11.639,1.371,17.913,0.985,Yes,Yes,Yes,Yes,1242617.725,687083.008,4.138990e+05,141636.099,978145.473,7.783581e+05,-4.755753e+04,247345.390
4,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),GB,10.823,1.357,12.955,0.586,Yes,Yes,Yes,Yes,-5688230.065,8701839.722,-1.457986e+07,189783.265,-4966937.546,1.294244e+07,-1.405289e+07,-3856464.571

In [87]:
df_merged.columns

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks'],
      dtype='object')

In [88]:
# calculate contribution percentages for each value component and week
weeks = ['52','26']
components = ['Value due to Buyers YA','Value due to Occasions per Buyer YA','Value due to Value per Occasion YA']

for wk in weeks:
    denom_col = f'Value vs YA (Abs Change) Latest {wk} Wks'
    for comp in components:
        num_col = f'{comp} Latest {wk} Wks'
        new_col = f'Contribution {comp} Latest {wk} Wks'
        df_merged[new_col] = df_merged[num_col] / df_merged[denom_col] * 100

# inspect new columns
df_merged.columns

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks',
       'Contribution Value due to Buyers YA Latest 52 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 52 Wks',
       'Contribution Value due to Value per Occasion YA Latest 52 Wks',
       'Contribution Value due to Buyers YA Latest 26 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 26 Wks',
       'Contribution Value due to Value per Occasion YA Latest 26 Wks'],
      dtype='object')

In [89]:
df_merged

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks,Contribution Value due to Buyers YA Latest 52 Wks,Contribution Value due to Occasions per Buyer YA Latest 52 Wks,Contribution Value due to Value per Occasion YA Latest 52 Wks,Contribution Value due to Buyers YA Latest 26 Wks,Contribution Value due to Occasions per Buyer YA Latest 26 Wks,Contribution Value due to Value per Occasion YA Latest 26 Wks
0,1,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,Germany,5.621,1.342,8.716,0.877,Yes,Yes,Yes,Yes,791926.913,1110128.760,2.604244e+05,-5.786256e+05,446782.207,1.470200e+06,1.684292e+05,-1191849.092,140.180709,32.884903,-73.065530,329.064162,37.698273,-266.762882
1,3,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,COLGATE PALMOLIVE,BRAVO (COLGATE PALMOLIVE),Italy,2.184,0.290,3.350,0.180,Yes,Yes,Yes,Yes,-42369.452,108660.475,-6.857022e+04,-8.246106e+04,78686.554,1.437160e+05,-1.811871e+04,-46911.006,-256.459477,161.838820,194.623853,182.643656,-23.026435,-59.617563
2,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,4.371,0.630,6.745,0.319,Yes,Yes,Yes,Yes,853160.781,444338.965,-4.208332e+05,8.296549e+05,609011.228,7.507220e+05,-4.108906e+05,269179.707,52.081504,-49.326359,97.244844,123.268986,-67.468472,44.199465
3,7,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,Italy,11.639,1.371,17.913,0.985,Yes,Yes,Yes,Yes,1242617.725,687083.008,4.138990e+05,1.416361e+05,978145.473,7.783581e+05,-4.755753e+04,247345.390,55.293192,33.308635,11.398204,79.574886,-4.862010,25.287178
4,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),GB,10.823,1.357,12.955,0.586,Yes,Yes,Yes,Yes,-5688230.065,8701839.722,-1.457986e+07,1.897833e+05,-4966937.546,1.294244e+07,-1.405289e+07,-3856464.571,-152.979743,256.316368,-3.336420,-260.571783,282.928720,77.642703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,2887,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ALL OTHER,ALL OTHER,GB,17.044,0.747,25.194,0.107,Yes,Yes,Yes,Yes,7525573.545,734697.575,-4.577374e+06,1.136824e+07,7419946.919,1.606775e+06,-1.160366e+06,6973537.944,9.762679,-60.824249,151.061502,21.654806,-15.638465,93.983663
206,2903,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,BOLTON GROUP,ACQUA ALLE ROSE,Italy,1.817,0.391,3.015,0.164,Yes,Yes,Yes,Yes,119001.492,354523.333,-4.231482e+04,-1.932129e+05,550176.846,7.255667e+05,7.277008e+04,-248162.122,297.915032,-35.558230,-162.361717,131.878814,13.226671,-45.105883
207,2974,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,KIMBERLY CLARK,HUGGIES,Italy,1.356,0.337,2.063,0.259,Yes,Yes,Yes,Yes,-3092.676,462796.947,1.597148e+05,-6.256044e+05,119924.810,4.884227e+05,-2.773019e+05,-91199.930,-14964.288112,-5164.292768,20228.579521,407.274097,-231.229829,-76.047592
208,2988,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,MIXA (L'OREAL / L'OREAL),France,5.101,0.223,7.754,0.194,Yes,Yes,Yes,Yes,408411.901,915429.142,9.547586e+05,-1.461771e+06,670911.345,6.583396e+05,3.832285e+05,-370656.080,224.143601,233.773440,-357.915885,98.126172,57.120583,-55.246656
209,2998,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,LEA NATURE,SO'BIO ETIC,France,1.536,0.252,2.637,0.177,Yes,Yes,Yes,Yes,-770343.269,632695.035,-5.920484e+05,-8.109819e+05,-135026.411,6.859965e+05,-3.715906e+05,-449430.496,-82.131572,76.855144,105.275388,-508.046181,275.198463,332.846361

In [90]:
# Sort df_merged by Value vs YA (Abs Change) Latest 13 Wks in descending order
df_priority = df_merged.sort_values(
    by='Value vs YA (Abs Change) Latest 26 Wks',
    ascending=False
).reset_index(drop=True)

df_priority

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks,Contribution Value due to Buyers YA Latest 52 Wks,Contribution Value due to Occasions per Buyer YA Latest 52 Wks,Contribution Value due to Value per Occasion YA Latest 52 Wks,Contribution Value due to Buyers YA Latest 26 Wks,Contribution Value due to Occasions per Buyer YA Latest 26 Wks,Contribution Value due to Value per Occasion YA Latest 26 Wks
0,52,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),France,9.842,2.698,13.809,1.781,Yes,Yes,Yes,Yes,2.405763e+07,1.377025e+07,1.780857e+06,8506531.224,2.801299e+07,1.615693e+07,7.763204e+04,1.177843e+07,57.238578,7.402460,35.358970,57.676559,0.277129,42.046306
1,2832,People Group,EUR,Total Panel,Total Outlets,VITAMIN SUPPLEMENTS,ALL OTHER,ALL OTHER,Germany,14.466,2.155,19.098,1.344,Yes,Yes,Yes,Yes,8.623709e+06,1.080711e+07,3.044560e+06,-5227967.820,1.123335e+07,1.237497e+07,-9.578544e+05,-1.837710e+05,125.318534,35.304530,-60.623195,110.162817,-8.526882,-1.635942
2,920,People Group,EUR,Total Panel,Total Outlets,FABRIC SOFT,PRIVATE LABEL,PRIVATE LABEL,Spain,55.363,0.493,63.894,0.339,Yes,Yes,Yes,Yes,1.675381e+07,2.521797e+06,1.522746e+07,-995450.501,1.028623e+07,1.631086e+06,1.135142e+07,-2.696273e+06,15.052075,90.889486,-5.941635,15.856980,110.355447,-26.212446
3,2699,People Group,EUR,Total Panel,Total Outlets,TOILET PAPER,ESSITY,ZEWA,Germany,11.586,1.591,16.281,1.298,Yes,Yes,Yes,Yes,6.528892e+06,9.307322e+06,-8.080408e+06,5301963.615,9.308653e+06,8.524028e+06,-2.425330e+06,3.209952e+06,142.555909,-123.763842,81.207707,91.571016,-26.054576,34.483524
4,1940,People Group,EUR,Total Panel,Total Outlets,LAUNDRY DET,PROCTER & GAMBLE,ARIEL (PROCTER & GAMBLE / PROCTER & GAMBLE),GB,13.808,0.408,18.207,-0.199,Yes,Yes,Yes,Yes,1.335732e+07,-5.466577e+05,4.213361e+06,9690620.806,8.807401e+06,3.735037e+06,-1.096379e+06,6.168742e+06,-4.092570,31.543455,72.549129,42.407941,-12.448386,70.040437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,2759,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,COLGATE PALMOLIVE,COLGATE (COLGATE PALMOLIVE),Total Europe,30.231,0.733,39.029,0.404,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,2778,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,HALEON,AQUAFRESH (HALEON),Total Europe,6.062,0.391,9.059,0.084,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,2784,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,HALEON,ODOL MED 3 (HALEON),Total Europe,4.104,0.824,6.043,0.790,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,2809,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,PRIVATE LABEL,PRIVATE LABEL,Total Europe,17.133,0.689,24.078,0.298,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,2832,People Group,EUR,Total Panel,Total Outlets,VITAMIN SUPPLEMENTS,ALL OTHER,ALL OTHER,Total Europe,8.752,0.576,12.716,0.573,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,-0.365,2.819,-0.136,Yes,No,No,No
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,-0.083,0.578,-0.170,No,No,Yes,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000,No,No,Yes,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439,Yes,No,Yes,No
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306,Yes,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000,No,No,No,No
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.011,0.256,-0.014,No,No,Yes,No
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.005,0.005,0.005,No,No,No,No
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.302,0.450,0.450,No,Yes,No,No
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.059,0.087,0.087,No,No,No,No

# pg risk

In [92]:
# define a helper that applies the two rules only for P&G brands
# brand_owner is now a parameter with a default value; the result
# column name is constructed separately so we can reference it easily.
def calculate_pg_risk(row, brand_owner='PROCTER & GAMBLE'):
    if row['BRAND OWNER'] != brand_owner:
        return 'No'                       # keep others as “No”
    l52 = row['Latest 52 vs YA']
    l26 = row['Latest 26 vs YA']

    # declining‑growth
    if l52 > 0 and l26 < l52 :
        return 'Growth Deceleration'
    # declining‑deceleration
    if l52 < 0 and l26 < l52:
        return 'Decline Acceleration'
    return 'No'

# assign the column
brand_owner = 'PROCTER & GAMBLE'
colname = f"{brand_owner} risk"
# use a lambda to pass the brand_owner argument to the function
# (alternatively the default value in calculate_pg_risk could be used)
df_final[colname] = df_final.apply(lambda r: calculate_pg_risk(r, brand_owner), axis=1)

# quick check
print(df_final[colname].value_counts())
print(df_final[df_final['BRAND OWNER']==brand_owner][['BRAND','country',
      'Latest 52 vs YA','Latest 26 vs YA',colname]].head())

PROCTER & GAMBLE risk
No                      8063
Growth Deceleration      171
Decline Acceleration     105
Name: count, dtype: int64
                                            BRAND       country  \
39                                     DON LIMPIO         Spain
40                                     DON LIMPIO  Total Europe
41    FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE)            GB
42    FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE)  Total Europe
116  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE)        France

     Latest 52 vs YA  Latest 26 vs YA PROCTER & GAMBLE risk
39            -0.096           -0.078                    No
40            -0.012           -0.009                    No
41            -0.299           -0.045                    No
42            -0.057           -0.009                    No
116           -0.303            0.405                    No

In [62]:
# RECHECK: Full verification of P&G risk logic starting with P&G data
print("="*80)
print("FULL RECHECK: LOGIC VERIFICATION")
print("="*80)

# Step 1: Filter for PROCTER & GAMBLE brands
pg_brands = df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE'].copy()
print(f"\n✓ Total P&G rows in df_final: {len(pg_brands)}")
print(f"✓ Total rows in df_final: {len(df_final)}")

# Step 2: Check P&G risk column exists
if 'P&G risk' in df_final.columns:
    print(f"✓ P&G risk column exists in df_final")
else:
    print("✗ ERROR: P&G risk column NOT found in df_final")

# Step 3: Verify logic for each risk category
print("\n" + "="*80)
print("RISK CATEGORY VERIFICATION")
print("="*80)

# Declining growth: Latest 52 > 0 AND (Latest 26 < Latest 52 OR Latest 13 < Latest 52)
declining_growth = pg_brands[
    (pg_brands['Latest 52 vs YA'] > 0) & 
    (pg_brands['Latest 26 vs YA'] < pg_brands['Latest 52 vs YA']) 
]

declining_growth_marked = pg_brands[pg_brands['P&G risk'] == 'Growth Deceleration']

print(f"\n1. DECLINING GROWTH:")
print(f"   Expected logic count: {len(declining_growth)}")
print(f"   Marked as 'Declining growth': {len(declining_growth_marked)}")
print(f"   Match: {'✓ YES' if len(declining_growth) == len(declining_growth_marked) else '✗ NO'}")

# Declining Deceleration: Latest 52 < 0 AND (Latest 26 > Latest 52 OR Latest 13 > Latest 52)
declining_deceleration = pg_brands[
    (pg_brands['Latest 52 vs YA'] < 0) & 
    (pg_brands['Latest 26 vs YA'] < pg_brands['Latest 52 vs YA']) 
]

declining_deceleration_marked = pg_brands[pg_brands['P&G risk'] == 'Decline Acceleration']

print(f"\n2. DECLINING DECELERATION:")
print(f"   Expected logic count: {len(declining_deceleration)}")
print(f"   Marked as 'Declining Deceleration': {len(declining_deceleration_marked)}")
print(f"   Match: {'✓ YES' if len(declining_deceleration) == len(declining_deceleration_marked) else '✗ NO'}")

# No risk: Everything else (including non-P&G)
no_risk_pg = pg_brands[pg_brands['P&G risk'] == 'No']
print(f"\n3. NO RISK (P&G brands only):")
print(f"   Count: {len(no_risk_pg)}")

# Step 4: Overall distribution
print("\n" + "="*80)
print("OVERALL P&G RISK DISTRIBUTION")
print("="*80)
print(df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE']['P&G risk'].value_counts())

print("\n" + "="*80)
print("NON-P&G BRANDS - SHOULD ALL BE 'No'")
print("="*80)
non_pg = df_final[df_final['BRAND OWNER']!='PROCTER & GAMBLE']
non_pg_risk_dist = non_pg['P&G risk'].value_counts()
print(non_pg_risk_dist)
if len(non_pg_risk_dist) == 1 and non_pg_risk_dist.index[0] == 'No':
    print("✓ All non-P&G brands correctly marked as 'No'")
else:
    print("✗ ERROR: Some non-P&G brands have risk values other than 'No'")

# Step 5: Sample verification rows
print("\n" + "="*80)
print("SAMPLE ROWS - DETAILED VERIFICATION")
print("="*80)

print("\nSample DECLINING GROWTH rows:")
declining_growth_sample = declining_growth_marked[['BRAND', 'country', 'Latest 52 vs YA', 'Latest 26 vs YA',  'P&G risk']].head(5)
print(declining_growth_sample)
print("Logic check (for each row, Latest 52 > 0 and min(26,13) < 52):")
for idx, row in declining_growth_sample.iterrows():
    l52 = row['Latest 52 vs YA']
    l26 = row['Latest 26 vs YA']

    print(f"  {row['BRAND']}: 52={l52:.3f} (>0?{l52>0}), 26={l26:.3f}(<52?{l26<l52})")

print("\nSample DECLINING DECELERATION rows:")
declining_deceleration_sample = declining_deceleration_marked[['BRAND', 'country', 'Latest 52 vs YA', 'Latest 26 vs YA', 'P&G risk']].head(5)
print(declining_deceleration_sample)
print("Logic check (for each row, Latest 52 < 0 and max(26,13) > 52):")
for idx, row in declining_deceleration_sample.iterrows():
    l52 = row['Latest 52 vs YA']
    l26 = row['Latest 26 vs YA']
    print(f"  {row['BRAND']}: 52={l52:.3f} (<0?{l52<0}), 26={l26:.3f}(>52?{l26>l52})")

print("\n" + "="*80)
print("VERIFICATION COMPLETE")
print("="*80)

================================================================================
FULL RECHECK: LOGIC VERIFICATION
================================================================================

✓ Total P&G rows in df_final: 653
✓ Total rows in df_final: 8339
✗ ERROR: P&G risk column NOT found in df_final

================================================================================
RISK CATEGORY VERIFICATION
================================================================================

KeyError: 'P&G risk'

In [ ]:
df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,P&G risk
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,0.000,2.819,0.000,Yes,No,No,No,No
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,0.000,0.578,0.000,No,No,No,No,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000,No,No,Yes,No,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439,Yes,No,Yes,No,No
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306,Yes,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000,No,No,No,No,No
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.000,0.256,0.000,No,No,No,No,No
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.000,0.005,0.000,No,No,No,No,No
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.000,0.450,0.000,No,No,No,No,No
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.000,0.087,0.000,No,No,No,No,No

In [ ]:
df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE']['P&G risk'].value_counts()

P&G risk
No                      541
Growth Deceleration      68
Decline Acceleration     44
Name: count, dtype: int64

In [ ]:
pg_risk_final=df_final[df_final['P&G risk']!='No']
pg_risk_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,P&G risk
118,35,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,PROCTER & GAMBLE,ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE),Germany,3.480,-0.333,5.970,0.112,Yes,No,No,No,Growth Deceleration
166,52,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),Germany,0.006,-0.016,0.050,0.024,No,No,No,No,Growth Deceleration
168,52,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),Spain,11.064,0.875,18.017,3.325,Yes,Yes,No,No,Growth Deceleration
347,117,People Group,EUR,Total Panel,Total Outlets,AFTER SHAVE,PROCTER & GAMBLE,GILLETTE (PROCTER & GAMBLE / GILLETTE),Italy,0.020,-0.104,0.092,-0.086,No,No,No,No,Decline Acceleration
353,119,People Group,EUR,Total Panel,Total Outlets,AFTER SHAVE,PROCTER & GAMBLE,GILLETTE SERIES,Spain,0.000,-0.063,0.061,-0.019,No,No,No,No,Decline Acceleration
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7786,2873,People Group,EUR,Total Panel,Total Outlets,VITAMIN SUPPLEMENTS,PROCTER & GAMBLE,VIGANTOLVIT,Germany,0.281,0.024,0.446,0.094,No,No,No,No,Growth Deceleration
8221,3030,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,GILLETTE SATIN CARE,Italy,0.059,0.059,0.329,0.329,No,No,No,No,Growth Deceleration
8222,3030,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,GILLETTE SATIN CARE,Spain,0.071,0.056,0.177,0.135,No,No,No,No,Growth Deceleration
8231,3033,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,KING C. GILLETTE,Italy,0.000,-0.026,0.024,-0.002,No,No,No,No,Decline Acceleration
8244,3037,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,PAMPERS,Germany,1.214,-0.398,2.165,0.022,Yes,No,No,No,Growth Deceleration

In [ ]:
df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE'].shape

(653, 18)

In [ ]:
df_final['P&G risk'].value_counts()

P&G risk
No                      8227
Growth Deceleration       68
Decline Acceleration      44
Name: count, dtype: int64

In [ ]:
pg_risk_final.to_excel('pg_risk3.xlsx')

In [ ]:
pg_risk_final.columns

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'P&G risk'],
      dtype='object')

In [ ]:
pg_risk_final1=pg_risk_final[[ 'Currency',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'P&G risk']]
pg_risk_final1.to_excel('pg_risk_output.xlsx',index=False)

In [63]:
df_priority1=df_priority[[ 'Currency', 
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks',
       'Contribution Value due to Buyers YA Latest 52 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 52 Wks',
       'Contribution Value due to Value per Occasion YA Latest 52 Wks',
       'Contribution Value due to Buyers YA Latest 26 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 26 Wks',
       'Contribution Value due to Value per Occasion YA Latest 26 Wks']]

df_priority1.to_excel('priority_brands_output.xlsx', index=False)

NameError: name 'df_priority' is not defined