In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
# define file path and sheet names
file_path = r"c:\Users\jari5003\Desktop\Selen  P&G\MAIN_Penetration and Value Drivers Template_raw data for Divyaa & Rinu.xlsx"
sheet1 = "Penetration Trends Template"
sheet2 = "KPIs - EU5 template"

# load both sheets skipping raw1 and assigning multi-row headers
# df1: skip first row then next 4 rows as headers
# df2: skip first row then next 2 rows as headers

df1 = pd.read_excel(
    file_path,
    sheet_name=sheet1,
    skiprows=1,
    header=[0,1,2,3]
)

df2 = pd.read_excel(
    file_path,
    sheet_name=sheet2,
    skiprows=1,
    header=[0,1]
)

# show some info
print("df1 shape:", df1.shape)
print("df1 columns:\n", df1.columns)
print("df2 shape:", df2.shape)
print("df2 columns:\n", df2.columns)

C:\Users\jari5003\AppData\Roaming\Python\Python312\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Web Extension extension is not supported and will be removed
  warn(msg)

df1 shape: (3078, 43)
df1 columns:
 MultiIndex([(            'Unnamed: 0_level_0', 'Unnamed: 0_level_1', ...),
            (            'Unnamed: 1_level_0', 'Unnamed: 1_level_1', ...),
            (            'Unnamed: 2_level_0', 'Unnamed: 2_level_1', ...),
            (            'Unnamed: 3_level_0', 'Unnamed: 3_level_1', ...),
            (            'Unnamed: 4_level_0', 'Unnamed: 4_level_1', ...),
            (            'Unnamed: 5_level_0', 'Unnamed: 5_level_1', ...),
            (            'Unnamed: 6_level_0', 'Unnamed: 6_level_1', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...)],
           )
df2 shape: (5275, 23)
df2 columns:
 MultiIndex([(         'Unnamed: 0_level_0', ...),
            (         'Unnamed: 1_level_0', ...),
            (         'Unnamed: 2_level_0', ...),
            (         'Unnamed: 3_level_0', ...),
            (         'Unnamed: 4_level_0', ...),
            (         'Unnamed: 5_level_0', ...),
            (         'Unnamed: 6_level_0', ...),
            (         'Unnamed: 7_level_0', ...),
            ('Latest 52 Wks - w/e W52 Y25', ...),
            ('Latest 52 Wks - w/e W52 Y25', ...),
            ('Latest 52 Wks - w/e W52 Y25', ...),
            ('Latest 52 Wks - w/e W52 Y25', ...),
            ('Latest 52 Wks - w/e W52 Y25', ...),
            ('Latest 26 Wks - w/e W52 Y25', ...),
            ('Latest 26 Wks - w/e W52 Y25', ...),
            ('Latest 26 Wks - w/e W52 Y25', ...),
            ('Latest 26 Wks - w/e W52 Y25', ...),
            ('Latest 26 Wks - w/e W52 Y25', ...),
            ('Latest 13 Wks - w/e W52 Y25', ...),
            ('Latest 13 Wks - w/e W52 Y25', ...),
            ('Latest 13 Wks - w/e W52 Y25', ...),
            ('Latest 13 Wks - w/e W52 Y25', ...),
            ('Latest 13 Wks - w/e W52 Y25', ...)],
           )

C:\Users\jari5003\AppData\Roaming\Python\Python312\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Web Extension extension is not supported and will be removed
  warn(msg)

In [3]:
df1

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
     Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3073       People Group                EUR        Total Panel
3074       People Group                EUR        Total Panel
3075       People Group                EUR        Total Panel
3076       People Group                EUR        Total Panel
3077       People Group                EUR        Total Panel

     Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
     Unnamed: 3_level_1 Unnamed: 4_level_1    Unnamed: 5_level_1
     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3073      Total Outlets     SKIN CLEANSING                WELEDA
3074      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3075      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3076      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3077      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_0                 Penetration  \
                   Unnamed: 6_level_1                Total Europe
                   Unnamed: 6_level_2          Unnamed: 7_level_2
                                BRAND Latest 52 Wks - w/e W52 Y25
0                        SCOTCH BRITE                       3.985
1                           ALL OTHER                      18.477
2            AJAX (COLGATE PALMOLIVE)                       0.197
3           BRAVO (COLGATE PALMOLIVE)                       0.841
4              MARIGOLD (FREUDENBERG)                       0.056
...                               ...                         ...
3073                           WELEDA                       0.103
3074                           FISSAN                       0.090
3075     PONDS (YELLOW WOOD PARTNERS)                       0.002
3076  ST. IVES (YELLOW WOOD PARTNERS)                       0.249
3077                DAISE (ZURU EDGE)                       0.076

                                                              \

              Unnamed: 8_level_2          Unnamed: 9_level_2
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          2.255                       1.309
1                         11.460                       6.331
2                          0.122                       0.062
3                          0.451                       0.265
4                          0.034                       0.015
...                          ...                         ...
3073                       0.073                       0.039
3074                       0.038                       0.024
3075                       0.001                         NaN
3076                       0.162                       0.110
3077                       0.055                       0.044

                                                              \

                          France
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          2.917                       1.295
1                         28.570                      18.232
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                         NaN                         NaN
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                       0.002                       0.002

                                                              \

                                                          GB
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          0.868                       0.583
1                         10.511                      25.665
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                       0.290
...                          ...                         ...
3073                         NaN                       0.085
3074                         NaN                         NaN
3075                         NaN                       0.005
3076                         NaN                       1.291
3077                       0.002                       0.395

                                                              \


     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          0.303                       0.081
1                         16.654                       9.372
2                            NaN                         NaN
3                            NaN                         NaN
4                          0.177                       0.080
...                          ...                         ...
3073                       0.049                       0.030
3074                         NaN                         NaN
3075                       0.005                         NaN
3076                       0.838                       0.574
3077                       0.285                       0.225

                                                              \

                         Germany
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                            NaN                         NaN
1                          8.387                       4.996
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.220                       0.152
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                              \

                                                       Italy
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                            NaN                       7.297
1                          2.467                      24.851
2                            NaN                         NaN
3                            NaN                       3.279
4                            NaN                         NaN
...                          ...                         ...
3073                       0.068                       0.068
3074                         NaN                       0.539
3075                         NaN                         NaN
3076                         NaN                       0.009
3077                         NaN                         NaN

                                                              \


     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          4.391                       2.500
1                         15.038                       8.195
2                            NaN                         NaN
3                          1.881                       1.078
4                            NaN                         NaN
...                          ...                         ...
3073                       0.059                       0.059
3074                       0.228                       0.146
3075                         NaN                         NaN
3076                       0.008                         NaN
3077                         NaN                         NaN

                                                              \

                           Spain
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                         12.594                       7.250
1                         10.108                       5.758
2                          1.624                       1.007
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.034                       0.002
3074                         NaN                         NaN
3075                       0.009                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                 Penetration vs YA (Abs Change)  \
                                                   Total Europe
                                            Unnamed: 25_level_2
     Latest 13 Wks - w/e W52 Y25    Latest 52 Wks - w/e W52 Y25
0                          4.323                      -0.126000
1                          3.129                       1.316000
2                          0.508                       0.021000
3                            NaN                      -0.061000
4                            NaN                       0.000000
...                          ...                            ...
3073                       0.002                      -0.051000
3074                         NaN                      -0.016000
3075                         NaN                       0.000091
3076                         NaN                      -0.015000
3077                         NaN                       0.076000

                                                              \

             Unnamed: 26_level_2         Unnamed: 27_level_2
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.333                      -0.095
1                          0.552                       0.053
2                          0.017                      -0.009
3                         -0.076                      -0.070
4                          0.001                      -0.006
...                          ...                         ...
3073                      -0.045                      -0.035
3074                      -0.030                      -0.031
3075                       0.000                      -0.001
3076                       0.023                       0.008
3077                       0.055                       0.044

                                                              \

                          France
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          0.106                      -0.482
1                          3.783                       0.593
2                         -0.006                      -0.006
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                         NaN                         NaN
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                       0.002                       0.002

                                                              \

                                                          GB
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          0.082                      -0.146
1                          0.362                       1.565
2                         -0.006                         NaN
3                            NaN                         NaN
4                            NaN                      -0.002
...                          ...                         ...
3073                         NaN                       0.028
3074                         NaN                         NaN
3075                         NaN                       0.005
3076                         NaN                      -0.080
3077                       0.002                       0.395

                                                              \


     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.098                      -0.092
1                          1.630                       0.838
2                            NaN                         NaN
3                            NaN                         NaN
4                          0.007                      -0.031
...                          ...                         ...
3073                       0.013                       0.023
3074                         NaN                         NaN
3075                       0.005                         NaN
3076                       0.120                       0.051
3077                       0.285                       0.225

                                                              \

                         Germany
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                         -0.050                      -0.002
1                          0.787                       1.174
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                      -0.229                      -0.227
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                              \

                                                       Italy
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                            NaN                      -0.974
1                          0.397                       2.345
2                            NaN                         NaN
3                            NaN                       0.177
4                            NaN                         NaN
...                          ...                         ...
3073                      -0.186                       0.037
3074                         NaN                      -0.092
3075                         NaN                         NaN
3076                         NaN                       0.001
3077                         NaN                         NaN

                                                              \


     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.735                      -0.414
1                          0.631                      -0.400
2                            NaN                         NaN
3                          0.260                       0.028
4                            NaN                         NaN
...                          ...                         ...
3073                       0.059                       0.059
3074                      -0.178                      -0.186
3075                         NaN                         NaN
3076                      -0.001                      -0.008
3077                         NaN                         NaN

                                                              \

                           Spain
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          0.082                      -0.730
1                         -1.977                      -1.607
2                          0.182                       0.148
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.009                      -0.010
3074                         NaN                         NaN
3075                      -0.008                      -0.010
3076                         NaN                         NaN
3077                         NaN                         NaN




     Latest 13 Wks - w/e W52 Y25
0                         -0.164
1                         -1.058
2                         -0.068
3                            NaN
4                            NaN
...                          ...
3073                       0.002
3074                         NaN
3075                      -0.007
3076                         NaN
3077                         NaN

[3078 rows x 43 columns]

In [4]:
# Replace Unnamed columns in the 3rd header level (level index 2) after column 7 with 'Total Europe'
if isinstance(df1.columns, pd.MultiIndex):
    cols = list(df1.columns)
    new_cols = []
    for i, col in enumerate(cols):
        col_list = list(col)
        if i >= 7 and len(col_list) > 2 and isinstance(col_list[2], str) and col_list[2].startswith('Unnamed'):
            col_list[2] = 'Total Europe'
        new_cols.append(tuple(col_list))
    df1.columns = pd.MultiIndex.from_tuples(new_cols)
else:
    cols = df1.columns.tolist()
    for i in range(7, len(cols)):
        if isinstance(cols[i], str) and cols[i].startswith('Unnamed'):
            cols[i] = 'Total Europe'
    df1.columns = cols
# display updated dataframe
df1

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
     Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3073       People Group                EUR        Total Panel
3074       People Group                EUR        Total Panel
3075       People Group                EUR        Total Panel
3076       People Group                EUR        Total Panel
3077       People Group                EUR        Total Panel

     Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
     Unnamed: 3_level_1 Unnamed: 4_level_1    Unnamed: 5_level_1
     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3073      Total Outlets     SKIN CLEANSING                WELEDA
3074      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3075      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3076      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3077      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_0                 Penetration  \
                   Unnamed: 6_level_1                Total Europe
                   Unnamed: 6_level_2                Total Europe
                                BRAND Latest 52 Wks - w/e W52 Y25
0                        SCOTCH BRITE                       3.985
1                           ALL OTHER                      18.477
2            AJAX (COLGATE PALMOLIVE)                       0.197
3           BRAVO (COLGATE PALMOLIVE)                       0.841
4              MARIGOLD (FREUDENBERG)                       0.056
...                               ...                         ...
3073                           WELEDA                       0.103
3074                           FISSAN                       0.090
3075     PONDS (YELLOW WOOD PARTNERS)                       0.002
3076  ST. IVES (YELLOW WOOD PARTNERS)                       0.249
3077                DAISE (ZURU EDGE)                       0.076

                                                              \


     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          2.255                       1.309
1                         11.460                       6.331
2                          0.122                       0.062
3                          0.451                       0.265
4                          0.034                       0.015
...                          ...                         ...
3073                       0.073                       0.039
3074                       0.038                       0.024
3075                       0.001                         NaN
3076                       0.162                       0.110
3077                       0.055                       0.044

                                                              \

                          France
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          2.917                       1.295
1                         28.570                      18.232
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                         NaN                         NaN
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                       0.002                       0.002

                                                              \

                                                          GB
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          0.868                       0.583
1                         10.511                      25.665
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                       0.290
...                          ...                         ...
3073                         NaN                       0.085
3074                         NaN                         NaN
3075                         NaN                       0.005
3076                         NaN                       1.291
3077                       0.002                       0.395

                                                              \


     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          0.303                       0.081
1                         16.654                       9.372
2                            NaN                         NaN
3                            NaN                         NaN
4                          0.177                       0.080
...                          ...                         ...
3073                       0.049                       0.030
3074                         NaN                         NaN
3075                       0.005                         NaN
3076                       0.838                       0.574
3077                       0.285                       0.225

                                                              \

                         Germany
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                            NaN                         NaN
1                          8.387                       4.996
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.220                       0.152
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                              \

                                                       Italy
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                            NaN                       7.297
1                          2.467                      24.851
2                            NaN                         NaN
3                            NaN                       3.279
4                            NaN                         NaN
...                          ...                         ...
3073                       0.068                       0.068
3074                         NaN                       0.539
3075                         NaN                         NaN
3076                         NaN                       0.009
3077                         NaN                         NaN

                                                              \


     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          4.391                       2.500
1                         15.038                       8.195
2                            NaN                         NaN
3                          1.881                       1.078
4                            NaN                         NaN
...                          ...                         ...
3073                       0.059                       0.059
3074                       0.228                       0.146
3075                         NaN                         NaN
3076                       0.008                         NaN
3077                         NaN                         NaN

                                                              \

                           Spain
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                         12.594                       7.250
1                         10.108                       5.758
2                          1.624                       1.007
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.034                       0.002
3074                         NaN                         NaN
3075                       0.009                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                 Penetration vs YA (Abs Change)  \
                                                   Total Europe
                                                   Total Europe
     Latest 13 Wks - w/e W52 Y25    Latest 52 Wks - w/e W52 Y25
0                          4.323                      -0.126000
1                          3.129                       1.316000
2                          0.508                       0.021000
3                            NaN                      -0.061000
4                            NaN                       0.000000
...                          ...                            ...
3073                       0.002                      -0.051000
3074                         NaN                      -0.016000
3075                         NaN                       0.000091
3076                         NaN                      -0.015000
3077                         NaN                       0.076000

                                                              \


     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.333                      -0.095
1                          0.552                       0.053
2                          0.017                      -0.009
3                         -0.076                      -0.070
4                          0.001                      -0.006
...                          ...                         ...
3073                      -0.045                      -0.035
3074                      -0.030                      -0.031
3075                       0.000                      -0.001
3076                       0.023                       0.008
3077                       0.055                       0.044

                                                              \

                          France
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          0.106                      -0.482
1                          3.783                       0.593
2                         -0.006                      -0.006
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                         NaN                         NaN
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                       0.002                       0.002

                                                              \

                                                          GB
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          0.082                      -0.146
1                          0.362                       1.565
2                         -0.006                         NaN
3                            NaN                         NaN
4                            NaN                      -0.002
...                          ...                         ...
3073                         NaN                       0.028
3074                         NaN                         NaN
3075                         NaN                       0.005
3076                         NaN                      -0.080
3077                       0.002                       0.395

                                                              \


     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.098                      -0.092
1                          1.630                       0.838
2                            NaN                         NaN
3                            NaN                         NaN
4                          0.007                      -0.031
...                          ...                         ...
3073                       0.013                       0.023
3074                         NaN                         NaN
3075                       0.005                         NaN
3076                       0.120                       0.051
3077                       0.285                       0.225

                                                              \

                         Germany
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                         -0.050                      -0.002
1                          0.787                       1.174
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                      -0.229                      -0.227
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                              \

                                                       Italy
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                            NaN                      -0.974
1                          0.397                       2.345
2                            NaN                         NaN
3                            NaN                       0.177
4                            NaN                         NaN
...                          ...                         ...
3073                      -0.186                       0.037
3074                         NaN                      -0.092
3075                         NaN                         NaN
3076                         NaN                       0.001
3077                         NaN                         NaN

                                                              \


     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.735                      -0.414
1                          0.631                      -0.400
2                            NaN                         NaN
3                          0.260                       0.028
4                            NaN                         NaN
...                          ...                         ...
3073                       0.059                       0.059
3074                      -0.178                      -0.186
3075                         NaN                         NaN
3076                      -0.001                      -0.008
3077                         NaN                         NaN

                                                              \

                           Spain
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          0.082                      -0.730
1                         -1.977                      -1.607
2                          0.182                       0.148
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.009                      -0.010
3074                         NaN                         NaN
3075                      -0.008                      -0.010
3076                         NaN                         NaN
3077                         NaN                         NaN




     Latest 13 Wks - w/e W52 Y25
0                         -0.164
1                         -1.058
2                         -0.068
3                            NaN
4                            NaN
...                          ...
3073                       0.002
3074                         NaN
3075                      -0.007
3076                         NaN
3077                         NaN

[3078 rows x 43 columns]

In [5]:
# previously we modified headers; now drop the first two header levels for clarity
# this effectively removes the top two rows of the MultiIndex
if isinstance(df1.columns, pd.MultiIndex) and df1.columns.nlevels > 2:
    df1.columns = df1.columns.droplevel([0,1])

print("Columns after dropping first two levels:\n", df1.columns[:10])

Columns after dropping first two levels:
 MultiIndex([('Unnamed: 0_level_2',                      'People'),
            ('Unnamed: 1_level_2',                    'Currency'),
            ('Unnamed: 2_level_2',                 'Total Panel'),
            ('Unnamed: 3_level_2',               'Total Outlets'),
            ('Unnamed: 4_level_2',                    'CATEGORY'),
            ('Unnamed: 5_level_2',                 'BRAND OWNER'),
            ('Unnamed: 6_level_2',                       'BRAND'),
            (      'Total Europe', 'Latest 52 Wks - w/e W52 Y25'),
            (      'Total Europe', 'Latest 26 Wks - w/e W52 Y25'),
            (      'Total Europe', 'Latest 13 Wks - w/e W52 Y25')],
           )

In [6]:
df1

     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2  \
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3073       People Group                EUR        Total Panel
3074       People Group                EUR        Total Panel
3075       People Group                EUR        Total Panel
3076       People Group                EUR        Total Panel
3077       People Group                EUR        Total Panel

     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2  \
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3073      Total Outlets     SKIN CLEANSING                WELEDA
3074      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3075      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3076      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3077      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_2                Total Europe  \
                                BRAND Latest 52 Wks - w/e W52 Y25
0                        SCOTCH BRITE                       3.985
1                           ALL OTHER                      18.477
2            AJAX (COLGATE PALMOLIVE)                       0.197
3           BRAVO (COLGATE PALMOLIVE)                       0.841
4              MARIGOLD (FREUDENBERG)                       0.056
...                               ...                         ...
3073                           WELEDA                       0.103
3074                           FISSAN                       0.090
3075     PONDS (YELLOW WOOD PARTNERS)                       0.002
3076  ST. IVES (YELLOW WOOD PARTNERS)                       0.249
3077                DAISE (ZURU EDGE)                       0.076

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          2.255                       1.309
1                         11.460                       6.331
2                          0.122                       0.062
3                          0.451                       0.265
4                          0.034                       0.015
...                          ...                         ...
3073                       0.073                       0.039
3074                       0.038                       0.024
3075                       0.001                         NaN
3076                       0.162                       0.110
3077                       0.055                       0.044

                          France                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          2.917                       1.295
1                         28.570                      18.232
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                         NaN                         NaN
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                       0.002                       0.002

                                                          GB  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          0.868                       0.583
1                         10.511                      25.665
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                       0.290
...                          ...                         ...
3073                         NaN                       0.085
3074                         NaN                         NaN
3075                         NaN                       0.005
3076                         NaN                       1.291
3077                       0.002                       0.395

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          0.303                       0.081
1                         16.654                       9.372
2                            NaN                         NaN
3                            NaN                         NaN
4                          0.177                       0.080
...                          ...                         ...
3073                       0.049                       0.030
3074                         NaN                         NaN
3075                       0.005                         NaN
3076                       0.838                       0.574
3077                       0.285                       0.225

                         Germany                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                            NaN                         NaN
1                          8.387                       4.996
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.220                       0.152
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                       Italy  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                            NaN                       7.297
1                          2.467                      24.851
2                            NaN                         NaN
3                            NaN                       3.279
4                            NaN                         NaN
...                          ...                         ...
3073                       0.068                       0.068
3074                         NaN                       0.539
3075                         NaN                         NaN
3076                         NaN                       0.009
3077                         NaN                         NaN

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          4.391                       2.500
1                         15.038                       8.195
2                            NaN                         NaN
3                          1.881                       1.078
4                            NaN                         NaN
...                          ...                         ...
3073                       0.059                       0.059
3074                       0.228                       0.146
3075                         NaN                         NaN
3076                       0.008                         NaN
3077                         NaN                         NaN

                           Spain                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                         12.594                       7.250
1                         10.108                       5.758
2                          1.624                       1.007
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.034                       0.002
3074                         NaN                         NaN
3075                       0.009                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                Total Europe  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          4.323                   -0.126000
1                          3.129                    1.316000
2                          0.508                    0.021000
3                            NaN                   -0.061000
4                            NaN                    0.000000
...                          ...                         ...
3073                       0.002                   -0.051000
3074                         NaN                   -0.016000
3075                         NaN                    0.000091
3076                         NaN                   -0.015000
3077                         NaN                    0.076000

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.333                      -0.095
1                          0.552                       0.053
2                          0.017                      -0.009
3                         -0.076                      -0.070
4                          0.001                      -0.006
...                          ...                         ...
3073                      -0.045                      -0.035
3074                      -0.030                      -0.031
3075                       0.000                      -0.001
3076                       0.023                       0.008
3077                       0.055                       0.044

                          France                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          0.106                      -0.482
1                          3.783                       0.593
2                         -0.006                      -0.006
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                         NaN                         NaN
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                       0.002                       0.002

                                                          GB  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          0.082                      -0.146
1                          0.362                       1.565
2                         -0.006                         NaN
3                            NaN                         NaN
4                            NaN                      -0.002
...                          ...                         ...
3073                         NaN                       0.028
3074                         NaN                         NaN
3075                         NaN                       0.005
3076                         NaN                      -0.080
3077                       0.002                       0.395

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.098                      -0.092
1                          1.630                       0.838
2                            NaN                         NaN
3                            NaN                         NaN
4                          0.007                      -0.031
...                          ...                         ...
3073                       0.013                       0.023
3074                         NaN                         NaN
3075                       0.005                         NaN
3076                       0.120                       0.051
3077                       0.285                       0.225

                         Germany                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                         -0.050                      -0.002
1                          0.787                       1.174
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                      -0.229                      -0.227
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                       Italy  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                            NaN                      -0.974
1                          0.397                       2.345
2                            NaN                         NaN
3                            NaN                       0.177
4                            NaN                         NaN
...                          ...                         ...
3073                      -0.186                       0.037
3074                         NaN                      -0.092
3075                         NaN                         NaN
3076                         NaN                       0.001
3077                         NaN                         NaN

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.735                      -0.414
1                          0.631                      -0.400
2                            NaN                         NaN
3                          0.260                       0.028
4                            NaN                         NaN
...                          ...                         ...
3073                       0.059                       0.059
3074                      -0.178                      -0.186
3075                         NaN                         NaN
3076                      -0.001                      -0.008
3077                         NaN                         NaN

                           Spain                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          0.082                      -0.730
1                         -1.977                      -1.607
2                          0.182                       0.148
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.009                      -0.010
3074                         NaN                         NaN
3075                      -0.008                      -0.010
3076                         NaN                         NaN
3077                         NaN                         NaN


     Latest 13 Wks - w/e W52 Y25
0                         -0.164
1                         -1.058
2                         -0.068
3                            NaN
4                            NaN
...                          ...
3073                       0.002
3074                         NaN
3075                      -0.007
3076                         NaN
3077                         NaN

[3078 rows x 43 columns]

In [7]:
# create a new view of df1 with the first two header rows removed
if isinstance(df1.columns, pd.MultiIndex) and df1.columns.nlevels > 2:
    df1_trimmed = df1.copy()
    df1_trimmed.columns = df1_trimmed.columns.droplevel([0,1])
else:
    df1_trimmed = df1

# display trimmed dataframe
print("Trimmed df1 columns:", df1_trimmed.columns[:10])
df1_trimmed

Trimmed df1 columns: MultiIndex([('Unnamed: 0_level_2',                      'People'),
            ('Unnamed: 1_level_2',                    'Currency'),
            ('Unnamed: 2_level_2',                 'Total Panel'),
            ('Unnamed: 3_level_2',               'Total Outlets'),
            ('Unnamed: 4_level_2',                    'CATEGORY'),
            ('Unnamed: 5_level_2',                 'BRAND OWNER'),
            ('Unnamed: 6_level_2',                       'BRAND'),
            (      'Total Europe', 'Latest 52 Wks - w/e W52 Y25'),
            (      'Total Europe', 'Latest 26 Wks - w/e W52 Y25'),
            (      'Total Europe', 'Latest 13 Wks - w/e W52 Y25')],
           )

     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2  \
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3073       People Group                EUR        Total Panel
3074       People Group                EUR        Total Panel
3075       People Group                EUR        Total Panel
3076       People Group                EUR        Total Panel
3077       People Group                EUR        Total Panel

     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2  \
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3073      Total Outlets     SKIN CLEANSING                WELEDA
3074      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3075      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3076      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3077      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_2                Total Europe  \
                                BRAND Latest 52 Wks - w/e W52 Y25
0                        SCOTCH BRITE                       3.985
1                           ALL OTHER                      18.477
2            AJAX (COLGATE PALMOLIVE)                       0.197
3           BRAVO (COLGATE PALMOLIVE)                       0.841
4              MARIGOLD (FREUDENBERG)                       0.056
...                               ...                         ...
3073                           WELEDA                       0.103
3074                           FISSAN                       0.090
3075     PONDS (YELLOW WOOD PARTNERS)                       0.002
3076  ST. IVES (YELLOW WOOD PARTNERS)                       0.249
3077                DAISE (ZURU EDGE)                       0.076

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          2.255                       1.309
1                         11.460                       6.331
2                          0.122                       0.062
3                          0.451                       0.265
4                          0.034                       0.015
...                          ...                         ...
3073                       0.073                       0.039
3074                       0.038                       0.024
3075                       0.001                         NaN
3076                       0.162                       0.110
3077                       0.055                       0.044

                          France                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          2.917                       1.295
1                         28.570                      18.232
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                         NaN                         NaN
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                       0.002                       0.002

                                                          GB  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          0.868                       0.583
1                         10.511                      25.665
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                       0.290
...                          ...                         ...
3073                         NaN                       0.085
3074                         NaN                         NaN
3075                         NaN                       0.005
3076                         NaN                       1.291
3077                       0.002                       0.395

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          0.303                       0.081
1                         16.654                       9.372
2                            NaN                         NaN
3                            NaN                         NaN
4                          0.177                       0.080
...                          ...                         ...
3073                       0.049                       0.030
3074                         NaN                         NaN
3075                       0.005                         NaN
3076                       0.838                       0.574
3077                       0.285                       0.225

                         Germany                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                            NaN                         NaN
1                          8.387                       4.996
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.220                       0.152
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                       Italy  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                            NaN                       7.297
1                          2.467                      24.851
2                            NaN                         NaN
3                            NaN                       3.279
4                            NaN                         NaN
...                          ...                         ...
3073                       0.068                       0.068
3074                         NaN                       0.539
3075                         NaN                         NaN
3076                         NaN                       0.009
3077                         NaN                         NaN

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          4.391                       2.500
1                         15.038                       8.195
2                            NaN                         NaN
3                          1.881                       1.078
4                            NaN                         NaN
...                          ...                         ...
3073                       0.059                       0.059
3074                       0.228                       0.146
3075                         NaN                         NaN
3076                       0.008                         NaN
3077                         NaN                         NaN

                           Spain                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                         12.594                       7.250
1                         10.108                       5.758
2                          1.624                       1.007
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.034                       0.002
3074                         NaN                         NaN
3075                       0.009                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                Total Europe  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          4.323                   -0.126000
1                          3.129                    1.316000
2                          0.508                    0.021000
3                            NaN                   -0.061000
4                            NaN                    0.000000
...                          ...                         ...
3073                       0.002                   -0.051000
3074                         NaN                   -0.016000
3075                         NaN                    0.000091
3076                         NaN                   -0.015000
3077                         NaN                    0.076000

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.333                      -0.095
1                          0.552                       0.053
2                          0.017                      -0.009
3                         -0.076                      -0.070
4                          0.001                      -0.006
...                          ...                         ...
3073                      -0.045                      -0.035
3074                      -0.030                      -0.031
3075                       0.000                      -0.001
3076                       0.023                       0.008
3077                       0.055                       0.044

                          France                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          0.106                      -0.482
1                          3.783                       0.593
2                         -0.006                      -0.006
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                         NaN                         NaN
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                       0.002                       0.002

                                                          GB  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          0.082                      -0.146
1                          0.362                       1.565
2                         -0.006                         NaN
3                            NaN                         NaN
4                            NaN                      -0.002
...                          ...                         ...
3073                         NaN                       0.028
3074                         NaN                         NaN
3075                         NaN                       0.005
3076                         NaN                      -0.080
3077                       0.002                       0.395

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.098                      -0.092
1                          1.630                       0.838
2                            NaN                         NaN
3                            NaN                         NaN
4                          0.007                      -0.031
...                          ...                         ...
3073                       0.013                       0.023
3074                         NaN                         NaN
3075                       0.005                         NaN
3076                       0.120                       0.051
3077                       0.285                       0.225

                         Germany                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                         -0.050                      -0.002
1                          0.787                       1.174
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                      -0.229                      -0.227
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                       Italy  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                            NaN                      -0.974
1                          0.397                       2.345
2                            NaN                         NaN
3                            NaN                       0.177
4                            NaN                         NaN
...                          ...                         ...
3073                      -0.186                       0.037
3074                         NaN                      -0.092
3075                         NaN                         NaN
3076                         NaN                       0.001
3077                         NaN                         NaN

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.735                      -0.414
1                          0.631                      -0.400
2                            NaN                         NaN
3                          0.260                       0.028
4                            NaN                         NaN
...                          ...                         ...
3073                       0.059                       0.059
3074                      -0.178                      -0.186
3075                         NaN                         NaN
3076                      -0.001                      -0.008
3077                         NaN                         NaN

                           Spain                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          0.082                      -0.730
1                         -1.977                      -1.607
2                          0.182                       0.148
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.009                      -0.010
3074                         NaN                         NaN
3075                      -0.008                      -0.010
3076                         NaN                         NaN
3077                         NaN                         NaN


     Latest 13 Wks - w/e W52 Y25
0                         -0.164
1                         -1.058
2                         -0.068
3                            NaN
4                            NaN
...                          ...
3073                       0.002
3074                         NaN
3075                      -0.007
3076                         NaN
3077                         NaN

[3078 rows x 43 columns]

In [8]:
# recheck for columns to rename after correction
for idx, col in enumerate(df1.columns):
    if idx >= 7 and idx < 12:
        print(idx, col)

print('\nCheck level2 for renamed cols:')
for idx, col in enumerate(df1.columns[7:12], start=7):
    level2 = col[2] if isinstance(col, tuple) and len(col) > 2 else None
    print(idx, level2)

7 ('Total Europe', 'Latest 52 Wks - w/e W52 Y25')
8 ('Total Europe', 'Latest 26 Wks - w/e W52 Y25')
9 ('Total Europe', 'Latest 13 Wks - w/e W52 Y25')
10 ('France', 'Latest 52 Wks - w/e W52 Y25')
11 ('France', 'Latest 26 Wks - w/e W52 Y25')

Check level2 for renamed cols:
7 None
8 None
9 None
10 None
11 None

In [9]:
df1

     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2  \
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3073       People Group                EUR        Total Panel
3074       People Group                EUR        Total Panel
3075       People Group                EUR        Total Panel
3076       People Group                EUR        Total Panel
3077       People Group                EUR        Total Panel

     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2  \
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3073      Total Outlets     SKIN CLEANSING                WELEDA
3074      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3075      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3076      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3077      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_2                Total Europe  \
                                BRAND Latest 52 Wks - w/e W52 Y25
0                        SCOTCH BRITE                       3.985
1                           ALL OTHER                      18.477
2            AJAX (COLGATE PALMOLIVE)                       0.197
3           BRAVO (COLGATE PALMOLIVE)                       0.841
4              MARIGOLD (FREUDENBERG)                       0.056
...                               ...                         ...
3073                           WELEDA                       0.103
3074                           FISSAN                       0.090
3075     PONDS (YELLOW WOOD PARTNERS)                       0.002
3076  ST. IVES (YELLOW WOOD PARTNERS)                       0.249
3077                DAISE (ZURU EDGE)                       0.076

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          2.255                       1.309
1                         11.460                       6.331
2                          0.122                       0.062
3                          0.451                       0.265
4                          0.034                       0.015
...                          ...                         ...
3073                       0.073                       0.039
3074                       0.038                       0.024
3075                       0.001                         NaN
3076                       0.162                       0.110
3077                       0.055                       0.044

                          France                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          2.917                       1.295
1                         28.570                      18.232
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                         NaN                         NaN
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                       0.002                       0.002

                                                          GB  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          0.868                       0.583
1                         10.511                      25.665
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                       0.290
...                          ...                         ...
3073                         NaN                       0.085
3074                         NaN                         NaN
3075                         NaN                       0.005
3076                         NaN                       1.291
3077                       0.002                       0.395

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          0.303                       0.081
1                         16.654                       9.372
2                            NaN                         NaN
3                            NaN                         NaN
4                          0.177                       0.080
...                          ...                         ...
3073                       0.049                       0.030
3074                         NaN                         NaN
3075                       0.005                         NaN
3076                       0.838                       0.574
3077                       0.285                       0.225

                         Germany                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                            NaN                         NaN
1                          8.387                       4.996
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.220                       0.152
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                       Italy  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                            NaN                       7.297
1                          2.467                      24.851
2                            NaN                         NaN
3                            NaN                       3.279
4                            NaN                         NaN
...                          ...                         ...
3073                       0.068                       0.068
3074                         NaN                       0.539
3075                         NaN                         NaN
3076                         NaN                       0.009
3077                         NaN                         NaN

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                          4.391                       2.500
1                         15.038                       8.195
2                            NaN                         NaN
3                          1.881                       1.078
4                            NaN                         NaN
...                          ...                         ...
3073                       0.059                       0.059
3074                       0.228                       0.146
3075                         NaN                         NaN
3076                       0.008                         NaN
3077                         NaN                         NaN

                           Spain                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                         12.594                       7.250
1                         10.108                       5.758
2                          1.624                       1.007
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.034                       0.002
3074                         NaN                         NaN
3075                       0.009                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                Total Europe  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          4.323                   -0.126000
1                          3.129                    1.316000
2                          0.508                    0.021000
3                            NaN                   -0.061000
4                            NaN                    0.000000
...                          ...                         ...
3073                       0.002                   -0.051000
3074                         NaN                   -0.016000
3075                         NaN                    0.000091
3076                         NaN                   -0.015000
3077                         NaN                    0.076000

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.333                      -0.095
1                          0.552                       0.053
2                          0.017                      -0.009
3                         -0.076                      -0.070
4                          0.001                      -0.006
...                          ...                         ...
3073                      -0.045                      -0.035
3074                      -0.030                      -0.031
3075                       0.000                      -0.001
3076                       0.023                       0.008
3077                       0.055                       0.044

                          France                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          0.106                      -0.482
1                          3.783                       0.593
2                         -0.006                      -0.006
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                         NaN                         NaN
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                       0.002                       0.002

                                                          GB  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                          0.082                      -0.146
1                          0.362                       1.565
2                         -0.006                         NaN
3                            NaN                         NaN
4                            NaN                      -0.002
...                          ...                         ...
3073                         NaN                       0.028
3074                         NaN                         NaN
3075                         NaN                       0.005
3076                         NaN                      -0.080
3077                       0.002                       0.395

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.098                      -0.092
1                          1.630                       0.838
2                            NaN                         NaN
3                            NaN                         NaN
4                          0.007                      -0.031
...                          ...                         ...
3073                       0.013                       0.023
3074                         NaN                         NaN
3075                       0.005                         NaN
3076                       0.120                       0.051
3077                       0.285                       0.225

                         Germany                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                         -0.050                      -0.002
1                          0.787                       1.174
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                      -0.229                      -0.227
3074                         NaN                         NaN
3075                         NaN                         NaN
3076                         NaN                         NaN
3077                         NaN                         NaN

                                                       Italy  \
     Latest 13 Wks - w/e W52 Y25 Latest 52 Wks - w/e W52 Y25
0                            NaN                      -0.974
1                          0.397                       2.345
2                            NaN                         NaN
3                            NaN                       0.177
4                            NaN                         NaN
...                          ...                         ...
3073                      -0.186                       0.037
3074                         NaN                      -0.092
3075                         NaN                         NaN
3076                         NaN                       0.001
3077                         NaN                         NaN

                                                              \
     Latest 26 Wks - w/e W52 Y25 Latest 13 Wks - w/e W52 Y25
0                         -0.735                      -0.414
1                          0.631                      -0.400
2                            NaN                         NaN
3                          0.260                       0.028
4                            NaN                         NaN
...                          ...                         ...
3073                       0.059                       0.059
3074                      -0.178                      -0.186
3075                         NaN                         NaN
3076                      -0.001                      -0.008
3077                         NaN                         NaN

                           Spain                              \
     Latest 52 Wks - w/e W52 Y25 Latest 26 Wks - w/e W52 Y25
0                          0.082                      -0.730
1                         -1.977                      -1.607
2                          0.182                       0.148
3                            NaN                         NaN
4                            NaN                         NaN
...                          ...                         ...
3073                       0.009                      -0.010
3074                         NaN                         NaN
3075                      -0.008                      -0.010
3076                         NaN                         NaN
3077                         NaN                         NaN


     Latest 13 Wks - w/e W52 Y25
0                         -0.164
1                         -1.058
2                         -0.068
3                            NaN
4                            NaN
...                          ...
3073                       0.002
3074                         NaN
3075                      -0.007
3076                         NaN
3077                         NaN

[3078 rows x 43 columns]

In [10]:
# alternative transformation using melt, treating first 7 columns as metadata
# use df_base from earlier steps
try:
    df_base = df1_trimmed
except NameError:
    df_base = df1

# determine metadata and data columns by position
metadata_cols = list(df_base.columns[:7])
# we'll slice by position for data rather than by labels

data_cols_raw = list(df_base.columns[7:])

print("Metadata cols:", metadata_cols)
print("First few raw data cols:", data_cols_raw[:5])

# modify header2 (metric) names for data columns starting from original position 26 onwards
# original col index = 7 + idx in data_cols_raw
renamed_data = []
for idx, col in enumerate(data_cols_raw):
    c0, c1 = col
    if (7 + idx) >= 25:  # zero-based original
        c1 = f"{c1} vs YA"
    renamed_data.append((c0, c1))

# slice the data portion of df_base and then rename its columns

df_data = df_base.iloc[:, 7:].copy()
df_data.columns = pd.MultiIndex.from_tuples(renamed_data)

# also extract df_meta for later use

df_meta = df_base.iloc[:, :7].copy()

# flatten df_data columns
flat_cols = [f"{c0}|||{c1}" for c0, c1 in renamed_data]
df_flat = df_data.copy()
df_flat.columns = flat_cols

# add meta columns to flat
for col in metadata_cols:
    colname = col[1]
    df_flat[f"meta|||{colname}"] = df_meta[col].squeeze().values

# preserve row identifier
df_flat = df_flat.reset_index(drop=True)
df_flat['row_id'] = df_flat.index

# melt on metric columns
id_vars = ['row_id'] + [f"meta|||{col[1]}" for col in metadata_cols]
df_melt = df_flat.melt(id_vars=id_vars, var_name='combined', value_name='value')

# split combined
split_cols = df_melt['combined'].str.split('\\|\\|\\|', expand=True)
df_melt['country'] = split_cols[0]
df_melt['metric'] = split_cols[1]

# pivot back
df_final = df_melt.pivot_table(
    index=id_vars + ['country'],
    columns='metric',
    values='value',
    aggfunc='first'
).reset_index()

# clean metadata column names
for col in metadata_cols:
    df_final = df_final.rename(columns={f"meta|||{col[1]}": col[1]})

print("Transformed final shape:", df_final.shape)
print(df_final.head())

Metadata cols: [('Unnamed: 0_level_2', 'People'), ('Unnamed: 1_level_2', 'Currency'), ('Unnamed: 2_level_2', 'Total Panel'), ('Unnamed: 3_level_2', 'Total Outlets'), ('Unnamed: 4_level_2', 'CATEGORY'), ('Unnamed: 5_level_2', 'BRAND OWNER'), ('Unnamed: 6_level_2', 'BRAND')]
First few raw data cols: [('Total Europe', 'Latest 52 Wks - w/e W52 Y25'), ('Total Europe', 'Latest 26 Wks - w/e W52 Y25'), ('Total Europe', 'Latest 13 Wks - w/e W52 Y25'), ('France', 'Latest 52 Wks - w/e W52 Y25'), ('France', 'Latest 26 Wks - w/e W52 Y25')]
Transformed final shape: (8353, 15)
metric  row_id        People Currency  Total Panel  Total Outlets  \
0            0  People Group      EUR  Total Panel  Total Outlets
1            0  People Group      EUR  Total Panel  Total Outlets
2            0  People Group      EUR  Total Panel  Total Outlets
3            0  People Group      EUR  Total Panel  Total Outlets
4            0  People Group      EUR  Total Panel  Total Outlets

metric          CATEGORY BRAND OWNER         BRAND  country  \
0       ABRASIVE CL PADS          3M  SCOTCH BRITE   France
1       ABRASIVE CL PADS          3M  SCOTCH BRITE       GB
2       ABRASIVE CL PADS          3M  SCOTCH BRITE  Germany
3       ABRASIVE CL PADS          3M  SCOTCH BRITE    Italy
4       ABRASIVE CL PADS          3M  SCOTCH BRITE    Spain

metric  Latest 13 Wks - w/e W52 Y25  Latest 13 Wks - w/e W52 Y25 vs YA  \
0                             0.868                              0.082
1                             0.081                             -0.092
2                               NaN                                NaN
3                             2.500                             -0.414
4                             4.323                             -0.164

metric  Latest 26 Wks - w/e W52 Y25  Latest 26 Wks - w/e W52 Y25 vs YA  \
0                             1.295                             -0.482
1                             0.303                             -0.098
2                               NaN                             -0.002
3                             4.391                             -0.735
4                             7.250                             -0.730

metric  Latest 52 Wks - w/e W52 Y25  Latest 52 Wks - w/e W52 Y25 vs YA
0                             2.917                              0.106
1                             0.583                             -0.146
2                               NaN                             -0.050
3                             7.297                             -0.974
4                            12.594                              0.082

In [11]:

df_final

metric,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks - w/e W52 Y25,Latest 13 Wks - w/e W52 Y25 vs YA,Latest 26 Wks - w/e W52 Y25,Latest 26 Wks - w/e W52 Y25 vs YA,Latest 52 Wks - w/e W52 Y25,Latest 52 Wks - w/e W52 Y25 vs YA
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,0.868,0.082,1.295,-0.482,2.917,0.106
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.081,-0.092,0.303,-0.098,0.583,-0.146
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,NaN,NaN,NaN,-0.002,NaN,-0.050
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,2.500,-0.414,4.391,-0.735,7.297,-0.974
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,4.323,-0.164,7.250,-0.730,12.594,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8348,3076,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,NaN,-0.008,0.008,-0.001,0.009,0.001
8349,3076,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.110,0.008,0.162,0.023,0.249,-0.015
8350,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.002,0.002,0.002,0.002,0.002,0.002
8351,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.225,0.225,0.285,0.285,0.395,0.395
8352,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.044,0.044,0.055,0.055,0.076,0.076

In [15]:
df_final.columns=['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country',
       'Latest 13 Wks', 'Latest 13 vs YA',
       'Latest 26 Wks', 'Latest 26 vs YA',
       'Latest 52 Wks', 'Latest 52 vs YA']

In [96]:
df_final = df_final.fillna(0)

print("NaN values after filling:")
print(df_final.isna().sum())

NaN values after filling:
row_id                      0
People                      0
Currency                    0
Total Panel                 0
Total Outlets               0
CATEGORY                    0
BRAND OWNER                 0
BRAND                       0
country                     0
Latest 13 Wks               0
Latest 13 vs YA             0
Latest 26 Wks               0
Latest 26 vs YA             0
Latest 52 Wks               0
Latest 52 vs YA             0
Tangible Brands             0
Growing Penetration         0
Accelerating Penetration    0
dtype: int64

# >2pp

In [16]:
df_final['Tangible Brands'] = df_final['Latest 52 Wks'].apply(lambda x: 'Yes' if x > 2 else 'No')

# display a sample
df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks,Latest 13 vs YA,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,0.868,0.082,1.295,-0.482,2.917,0.106,Yes
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.081,-0.092,0.303,-0.098,0.583,-0.146,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,NaN,NaN,NaN,-0.002,NaN,-0.050,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,2.500,-0.414,4.391,-0.735,7.297,-0.974,Yes
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,4.323,-0.164,7.250,-0.730,12.594,0.082,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8348,3076,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,NaN,-0.008,0.008,-0.001,0.009,0.001,No
8349,3076,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.110,0.008,0.162,0.023,0.249,-0.015,No
8350,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.002,0.002,0.002,0.002,0.002,0.002,No
8351,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.225,0.225,0.285,0.285,0.395,0.395,No
8352,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.044,0.044,0.055,0.055,0.076,0.076,No

In [17]:
df_final.columns

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 13 Wks',
       'Latest 13 vs YA', 'Latest 26 Wks', 'Latest 26 vs YA', 'Latest 52 Wks',
       'Latest 52 vs YA', 'Tangible Brands'],
      dtype='object')

# Growing penetration, Latest 13w vs year ago should be greater than .2

In [18]:
df_final['Growing Penetration'] = df_final['Latest 13 vs YA'].apply(lambda x: 'Yes' if x > 0.2 else 'No')

df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks,Latest 13 vs YA,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,0.868,0.082,1.295,-0.482,2.917,0.106,Yes,No
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.081,-0.092,0.303,-0.098,0.583,-0.146,No,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,NaN,NaN,NaN,-0.002,NaN,-0.050,No,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,2.500,-0.414,4.391,-0.735,7.297,-0.974,Yes,No
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,4.323,-0.164,7.250,-0.730,12.594,0.082,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8348,3076,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,NaN,-0.008,0.008,-0.001,0.009,0.001,No,No
8349,3076,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.110,0.008,0.162,0.023,0.249,-0.015,No,No
8350,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.002,0.002,0.002,0.002,0.002,0.002,No,No
8351,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.225,0.225,0.285,0.285,0.395,0.395,No,Yes
8352,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.044,0.044,0.055,0.055,0.076,0.076,No,No

In [19]:
df_final['Growing Penetration'].value_counts()

Growing Penetration
No     7844
Yes     509
Name: count, dtype: int64

# Accelerating Penetration
- Penetration growth in latest 13 weeks vs YA  is greater than penetration change in latest 52 or 26. Consider only YA.

In [20]:
df_final['Accelerating Penetration'] = (
    (df_final['Latest 13 vs YA'] > df_final['Latest 26 vs YA']) | 
    (df_final['Latest 13 vs YA'] > df_final['Latest 52 vs YA'])
).apply(lambda x: 'Yes' if x else 'No')

df_final[['BRAND', 'country', 'Latest 13 vs YA', 'Latest 26 vs YA', 'Latest 52 vs YA', 'Accelerating Penetration']].head(10)

,BRAND,country,Latest 13 vs YA,Latest 26 vs YA,Latest 52 vs YA,Accelerating Penetration
0,SCOTCH BRITE,France,0.082,-0.482,0.106,Yes
1,SCOTCH BRITE,GB,-0.092,-0.098,-0.146,Yes
2,SCOTCH BRITE,Germany,NaN,-0.002,-0.050,No
3,SCOTCH BRITE,Italy,-0.414,-0.735,-0.974,Yes
4,SCOTCH BRITE,Spain,-0.164,-0.730,0.082,Yes
5,SCOTCH BRITE,Total Europe,-0.095,-0.333,-0.126,Yes
6,ALL OTHER,France,0.362,0.593,3.783,No
7,ALL OTHER,GB,0.838,1.630,1.565,No
8,ALL OTHER,Germany,0.397,1.174,0.787,No
9,ALL OTHER,Italy,-0.400,0.631,2.345,No

In [21]:
df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks,Latest 13 vs YA,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,0.868,0.082,1.295,-0.482,2.917,0.106,Yes,No,Yes
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.081,-0.092,0.303,-0.098,0.583,-0.146,No,No,Yes
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,NaN,NaN,NaN,-0.002,NaN,-0.050,No,No,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,2.500,-0.414,4.391,-0.735,7.297,-0.974,Yes,No,Yes
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,4.323,-0.164,7.250,-0.730,12.594,0.082,Yes,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8348,3076,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,NaN,-0.008,0.008,-0.001,0.009,0.001,No,No,No
8349,3076,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.110,0.008,0.162,0.023,0.249,-0.015,No,No,Yes
8350,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.002,0.002,0.002,0.002,0.002,0.002,No,No,No
8351,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.225,0.225,0.285,0.285,0.395,0.395,No,Yes,No
8352,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.044,0.044,0.055,0.055,0.076,0.076,No,No,No

In [22]:
df_final['Top Opportunity'] = (
    (df_final['Tangible Brands'] == 'Yes') & 
    (df_final['Growing Penetration'] == 'Yes') & 
    (df_final['Accelerating Penetration'] == 'Yes')
).apply(lambda x: 'Yes' if x else 'No')

# display sample with all columns
df_final[['BRAND', 'country', 'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration', 'Top Opportunity']].head(10)

,BRAND,country,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity
0,SCOTCH BRITE,France,Yes,No,Yes,No
1,SCOTCH BRITE,GB,No,No,Yes,No
2,SCOTCH BRITE,Germany,No,No,No,No
3,SCOTCH BRITE,Italy,Yes,No,Yes,No
4,SCOTCH BRITE,Spain,Yes,No,Yes,No
5,SCOTCH BRITE,Total Europe,Yes,No,Yes,No
6,ALL OTHER,France,Yes,Yes,No,No
7,ALL OTHER,GB,Yes,Yes,No,No
8,ALL OTHER,Germany,Yes,Yes,No,No
9,ALL OTHER,Italy,Yes,No,No,No

In [24]:
Top_Oppurtunity=df_final[df_final['Top Opportunity']=='Yes']
Top_Oppurtunity

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks,Latest 13 vs YA,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity
21,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,2.408,0.329,4.088,0.397,6.471,-0.118,Yes,Yes,Yes,Yes
62,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),Germany,4.452,0.685,5.862,0.604,8.721,0.994,Yes,Yes,Yes,Yes
114,34,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,PRIVATE LABEL,PRIVATE LABEL,Spain,5.510,0.961,6.816,0.645,9.154,0.106,Yes,Yes,Yes,Yes
135,41,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,BLUESUN,FIT (BLUESUN),Germany,0.573,0.324,0.938,0.209,2.664,1.724,Yes,Yes,Yes,Yes
164,52,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),France,4.613,0.690,7.880,0.866,12.222,-0.262,Yes,Yes,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8017,2961,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,HIPP,HIPP (HIPP),Germany,1.030,0.347,1.592,0.217,2.977,0.584,Yes,Yes,Yes,Yes
8083,2983,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,CERAVE,GB,1.355,0.206,2.115,0.291,2.904,0.103,Yes,Yes,Yes,Yes
8090,2984,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,GARNIER (L'OREAL / GARNIER),Germany,4.513,0.272,6.871,-0.121,10.268,0.283,Yes,Yes,Yes,Yes
8092,2984,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,GARNIER (L'OREAL / GARNIER),Spain,3.726,0.356,5.401,0.013,8.173,-0.264,Yes,Yes,Yes,Yes
8222,3030,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PRIVATE LABEL,PRIVATE LABEL,Germany,26.536,0.617,36.266,0.597,46.052,1.412,Yes,Yes,Yes,Yes

# df2

In [25]:
# Process df2: Keep MultiIndex to properly extract header0 and header1
df2_copy = df2.copy()

print("df2 original columns (first 12):", df2_copy.columns[:12].tolist())
print("df2 MultiIndex nlevels:", df2_copy.columns.nlevels)

# Identify metadata columns (first 8 by position)
metadata_cols = list(df2_copy.columns[:8])
data_cols = list(df2_copy.columns[8:])

print("\nMetadata columns:", metadata_cols)
print("Data columns count:", len(data_cols))
print("Data columns sample (tuples):", data_cols[:5])

# Process the data columns: extract header0 (time period) + header1 (metric)
renamed_cols = []

for col in data_cols:
    h0, h1 = col[0], col[1]  # col is a tuple (header0, header1)
    
    # Split header0 at '-' and take the first part
    time_period = h0.split('-')[0].strip()
    
    # Combine metric + time period
    new_col = f"{h1} {time_period}"
    renamed_cols.append(new_col)

print("\nRenamed data columns (first 10):", renamed_cols[:10])

# Create new dataframe with renamed columns
df2_meta = df2_copy.iloc[:, :8].copy()
df2_data = df2_copy.iloc[:, 8:].copy()

# Flatten column names to single level
df2_meta.columns = [col[1] for col in df2_meta.columns]
df2_data.columns = renamed_cols

# Concatenate metadata and data
df2_processed = pd.concat([df2_meta, df2_data], axis=1)

print("\ndf2_processed shape:", df2_processed.shape)
print("df2_processed columns:", df2_processed.columns.tolist())
print("\nSample of df2_processed:")
df2_processed

df2 original columns (first 12): [('Unnamed: 0_level_0', 'People'), ('Unnamed: 1_level_0', 'Currency'), ('Unnamed: 2_level_0', 'Total Panel'), ('Unnamed: 3_level_0', 'Total Outlets'), ('Unnamed: 4_level_0', 'Countries'), ('Unnamed: 5_level_0', 'CATEGORY'), ('Unnamed: 6_level_0', 'BRAND OWNER'), ('Unnamed: 7_level_0', 'BRAND'), ('Latest 52 Wks - w/e W52 Y25', 'Penetration'), ('Latest 52 Wks - w/e W52 Y25', 'Value vs YA (Abs Change)'), ('Latest 52 Wks - w/e W52 Y25', 'Value due to Buyers YA'), ('Latest 52 Wks - w/e W52 Y25', 'Value due to Occasions per Buyer YA')]
df2 MultiIndex nlevels: 2

Metadata columns: [('Unnamed: 0_level_0', 'People'), ('Unnamed: 1_level_0', 'Currency'), ('Unnamed: 2_level_0', 'Total Panel'), ('Unnamed: 3_level_0', 'Total Outlets'), ('Unnamed: 4_level_0', 'Countries'), ('Unnamed: 5_level_0', 'CATEGORY'), ('Unnamed: 6_level_0', 'BRAND OWNER'), ('Unnamed: 7_level_0', 'BRAND')]
Data columns count: 15
Data columns sample (tuples): [('Latest 52 Wks - w/e W52 Y25', 'Penetration'), ('Latest 52 Wks - w/e W52 Y25', 'Value vs YA (Abs Change)'), ('Latest 52 Wks - w/e W52 Y25', 'Value due to Buyers YA'), ('Latest 52 Wks - w/e W52 Y25', 'Value due to Occasions per Buyer YA'), ('Latest 52 Wks - w/e W52 Y25', 'Value due to Value per Occasion YA')]

Renamed data columns (first 10): ['Penetration Latest 52 Wks', 'Value vs YA (Abs Change) Latest 52 Wks', 'Value due to Buyers YA Latest 52 Wks', 'Value due to Occasions per Buyer YA Latest 52 Wks', 'Value due to Value per Occasion YA Latest 52 Wks', 'Penetration Latest 26 Wks', 'Value vs YA (Abs Change) Latest 26 Wks', 'Value due to Buyers YA Latest 26 Wks', 'Value due to Occasions per Buyer YA Latest 26 Wks', 'Value due to Value per Occasion YA Latest 26 Wks']

df2_processed shape: (5275, 23)
df2_processed columns: ['People', 'Currency', 'Total Panel', 'Total Outlets', 'Countries', 'CATEGORY', 'BRAND OWNER', 'BRAND', 'Penetration Latest 52 Wks', 'Value vs YA (Abs Change) Latest 52 Wks', 'Value due to Buyers YA Latest 52 Wks', 'Value due to Occasions per Buyer YA Latest 52 Wks', 'Value due to Value per Occasion YA Latest 52 Wks', 'Penetration Latest 26 Wks', 'Value vs YA (Abs Change) Latest 26 Wks', 'Value due to Buyers YA Latest 26 Wks', 'Value due to Occasions per Buyer YA Latest 26 Wks', 'Value due to Value per Occasion YA Latest 26 Wks', 'Penetration Latest 13 Wks', 'Value vs YA (Abs Change) Latest 13 Wks', 'Value due to Buyers YA Latest 13 Wks', 'Value due to Occasions per Buyer YA Latest 13 Wks', 'Value due to Value per Occasion YA Latest 13 Wks']

Sample of df2_processed:

,People,Currency,Total Panel,Total Outlets,Countries,CATEGORY,BRAND OWNER,BRAND,Penetration Latest 52 Wks,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Penetration Latest 26 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks,Penetration Latest 13 Wks,Value vs YA (Abs Change) Latest 13 Wks,Value due to Buyers YA Latest 13 Wks,Value due to Occasions per Buyer YA Latest 13 Wks,Value due to Value per Occasion YA Latest 13 Wks
0,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,3M,SCOTCH BRITE,2.917,-8.626902e+04,186488.915,-131896.012,-140859.767,1.295,-569194.610,-519473.159,11797.373,-61517.648,0.868,133377.965,86566.996,32031.319,14779.383
1,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,28.570,1.410961e+07,4948873.542,4462344.688,4698392.571,18.232,4748573.319,823746.660,945618.108,2979208.919,10.511,1914877.449,409567.533,428261.216,1077049.310
2,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,COLGATE PALMOLIVE,AJAX (COLGATE PALMOLIVE),NaN,-4.565028e+03,NaN,NaN,NaN,NaN,-4565.028,NaN,NaN,NaN,NaN,-4565.028,NaN,NaN,NaN
3,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,FREUDENBERG,VILEDA,0.336,1.735790e+05,219474.932,12507.205,-58403.137,0.114,-23472.482,-94807.539,-153.352,71486.549,0.005,1150.840,-3289.076,-0.954,4440.397
4,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,37.258,6.271289e+04,-1962354.466,686316.661,1338753.146,26.723,270629.190,-634659.697,-206739.902,1112029.824,16.826,1041557.519,272208.736,200450.227,568901.143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5270,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,SODALIS,VITESSE (SODALIS),1.053,-4.512181e+05,-662271.275,195793.682,15257.659,0.859,-84614.385,129262.405,-265193.617,51315.928,0.686,-81250.764,94332.984,-193051.302,17468.350
5271,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,DOVE (UNILEVER / UNILEVER),NaN,-2.836982e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5272,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,REN (UNILEVER / UNILEVER),0.005,1.886498e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5273,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,WELEDA,WELEDA,0.034,1.966220e+04,19332.399,154.974,181.241,0.002,-27378.280,-24399.752,-18.353,-2928.023,0.002,4269.966,NaN,NaN,NaN
5274,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,YELLOW WOOD PARTNERS,PONDS (YELLOW WOOD PARTNERS),0.009,-3.959854e+03,-4630.998,0.000,670.214,NaN,-5491.759,NaN,NaN,NaN,NaN,-3925.257,NaN,NaN,NaN

In [26]:
df2_processed=df2_processed.fillna(0)
df2_processed

,People,Currency,Total Panel,Total Outlets,Countries,CATEGORY,BRAND OWNER,BRAND,Penetration Latest 52 Wks,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Penetration Latest 26 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks,Penetration Latest 13 Wks,Value vs YA (Abs Change) Latest 13 Wks,Value due to Buyers YA Latest 13 Wks,Value due to Occasions per Buyer YA Latest 13 Wks,Value due to Value per Occasion YA Latest 13 Wks
0,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,3M,SCOTCH BRITE,2.917,-8.626902e+04,186488.915,-131896.012,-140859.767,1.295,-569194.610,-519473.159,11797.373,-61517.648,0.868,133377.965,86566.996,32031.319,14779.383
1,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,28.570,1.410961e+07,4948873.542,4462344.688,4698392.571,18.232,4748573.319,823746.660,945618.108,2979208.919,10.511,1914877.449,409567.533,428261.216,1077049.310
2,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,COLGATE PALMOLIVE,AJAX (COLGATE PALMOLIVE),0.000,-4.565028e+03,0.000,0.000,0.000,0.000,-4565.028,0.000,0.000,0.000,0.000,-4565.028,0.000,0.000,0.000
3,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,FREUDENBERG,VILEDA,0.336,1.735790e+05,219474.932,12507.205,-58403.137,0.114,-23472.482,-94807.539,-153.352,71486.549,0.005,1150.840,-3289.076,-0.954,4440.397
4,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,37.258,6.271289e+04,-1962354.466,686316.661,1338753.146,26.723,270629.190,-634659.697,-206739.902,1112029.824,16.826,1041557.519,272208.736,200450.227,568901.143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5270,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,SODALIS,VITESSE (SODALIS),1.053,-4.512181e+05,-662271.275,195793.682,15257.659,0.859,-84614.385,129262.405,-265193.617,51315.928,0.686,-81250.764,94332.984,-193051.302,17468.350
5271,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,DOVE (UNILEVER / UNILEVER),0.000,-2.836982e+04,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5272,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,REN (UNILEVER / UNILEVER),0.005,1.886498e+04,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5273,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,WELEDA,WELEDA,0.034,1.966220e+04,19332.399,154.974,181.241,0.002,-27378.280,-24399.752,-18.353,-2928.023,0.002,4269.966,0.000,0.000,0.000
5274,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,YELLOW WOOD PARTNERS,PONDS (YELLOW WOOD PARTNERS),0.009,-3.959854e+03,-4630.998,0.000,670.214,0.000,-5491.759,0.000,0.000,0.000,0.000,-3925.257,0.000,0.000,0.000

In [27]:
df2_processed.columns

Index(['People', 'Currency', 'Total Panel', 'Total Outlets', 'Countries',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'Penetration Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Penetration Latest 26 Wks', 'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks',
       'Penetration Latest 13 Wks', 'Value vs YA (Abs Change) Latest 13 Wks',
       'Value due to Buyers YA Latest 13 Wks',
       'Value due to Occasions per Buyer YA Latest 13 Wks',
       'Value due to Value per Occasion YA Latest 13 Wks'],
      dtype='object')

In [28]:
df_merged

NameError: name 'df_merged' is not defined

In [29]:
Top_Oppurtunity

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks,Latest 13 vs YA,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity
21,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,2.408,0.329,4.088,0.397,6.471,-0.118,Yes,Yes,Yes,Yes
62,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),Germany,4.452,0.685,5.862,0.604,8.721,0.994,Yes,Yes,Yes,Yes
114,34,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,PRIVATE LABEL,PRIVATE LABEL,Spain,5.510,0.961,6.816,0.645,9.154,0.106,Yes,Yes,Yes,Yes
135,41,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,BLUESUN,FIT (BLUESUN),Germany,0.573,0.324,0.938,0.209,2.664,1.724,Yes,Yes,Yes,Yes
164,52,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),France,4.613,0.690,7.880,0.866,12.222,-0.262,Yes,Yes,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8017,2961,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,HIPP,HIPP (HIPP),Germany,1.030,0.347,1.592,0.217,2.977,0.584,Yes,Yes,Yes,Yes
8083,2983,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,CERAVE,GB,1.355,0.206,2.115,0.291,2.904,0.103,Yes,Yes,Yes,Yes
8090,2984,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,GARNIER (L'OREAL / GARNIER),Germany,4.513,0.272,6.871,-0.121,10.268,0.283,Yes,Yes,Yes,Yes
8092,2984,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,GARNIER (L'OREAL / GARNIER),Spain,3.726,0.356,5.401,0.013,8.173,-0.264,Yes,Yes,Yes,Yes
8222,3030,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PRIVATE LABEL,PRIVATE LABEL,Germany,26.536,0.617,36.266,0.597,46.052,1.412,Yes,Yes,Yes,Yes

In [31]:
# merge procedure between Top_Oppurtunity (from df_final) and df2_processed
# assume df_final and df2_processed exist

# select necessary columns from df2_processed
right_cols = [
    'Countries','CATEGORY','BRAND',
    'Value vs YA (Abs Change) Latest 52 Wks',
    'Value due to Buyers YA Latest 52 Wks',
    'Value due to Occasions per Buyer YA Latest 52 Wks',
    'Value due to Value per Occasion YA Latest 52 Wks',
    'Value vs YA (Abs Change) Latest 26 Wks',
    'Value due to Buyers YA Latest 26 Wks',
    'Value due to Occasions per Buyer YA Latest 26 Wks',
    'Value due to Value per Occasion YA Latest 26 Wks',
    'Value vs YA (Abs Change) Latest 13 Wks',
    'Value due to Buyers YA Latest 13 Wks',
    'Value due to Occasions per Buyer YA Latest 13 Wks',
    'Value due to Value per Occasion YA Latest 13 Wks'
]

# build small right table
df2_small = df2_processed[right_cols].copy()

# perform left merge
Top_Oppurtunity = df_final[df_final['Top Opportunity']=='Yes']

df_merged = Top_Oppurtunity.merge(
    df2_small,
    left_on=['country','CATEGORY','BRAND'],
    right_on=['Countries','CATEGORY','BRAND'],
    how='left'
)

# drop auxiliary column
if 'Countries' in df_merged.columns:
    df_merged = df_merged.drop(columns=['Countries'])

# show result
print(df_merged.columns)
df_merged.head()

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 13 Wks',
       'Latest 13 vs YA', 'Latest 26 Wks', 'Latest 26 vs YA', 'Latest 52 Wks',
       'Latest 52 vs YA', 'Tangible Brands', 'Growing Penetration',
       'Accelerating Penetration', 'Top Opportunity',
       'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks',
       'Value vs YA (Abs Change) Latest 13 Wks',
       'Value due to Buyers YA Latest 13 Wks',
       'Value due to Occasions per Buyer YA Latest 13 Wks',
       'Value due to Value per Occasion YA Latest 13 Wks'],
      dtype='object')

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks,Latest 13 vs YA,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks,Value vs YA (Abs Change) Latest 13 Wks,Value due to Buyers YA Latest 13 Wks,Value due to Occasions per Buyer YA Latest 13 Wks,Value due to Value per Occasion YA Latest 13 Wks
0,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,2.408,0.329,4.088,0.397,6.471,-0.118,Yes,Yes,Yes,Yes,573432.291,-1.623504e+05,-204188.821,939971.680,7.413010e+05,461393.497,-111508.894,391415.383,374039.448,338406.859,-175701.539,211333.130
1,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),Germany,4.452,0.685,5.862,0.604,8.721,0.994,Yes,Yes,Yes,Yes,5564507.308,1.462272e+07,-6580394.537,-2477823.485,2.611671e+06,6715569.393,-1248959.403,-2854942.543,4317724.147,4972905.236,-284972.102,-370209.842
2,34,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,PRIVATE LABEL,PRIVATE LABEL,Spain,5.510,0.961,6.816,0.645,9.154,0.106,Yes,Yes,Yes,Yes,1203883.013,1.037430e+06,-498957.209,665417.890,1.874661e+06,2904742.240,-2116774.234,1086704.131,2781291.740,2843513.326,-701616.229,639386.324
3,41,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,BLUESUN,FIT (BLUESUN),Germany,0.573,0.324,0.938,0.209,2.664,1.724,Yes,Yes,Yes,Yes,8113071.051,8.636910e+06,-2406019.763,1882164.261,8.539937e+05,766592.965,-159926.614,247329.249,1111612.552,1085381.580,-82128.524,108352.715
4,52,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),France,4.613,0.690,7.880,0.866,12.222,-0.262,Yes,Yes,Yes,Yes,-12023.511,-6.439092e+05,3112041.214,-2480172.989,1.080989e+07,5064231.064,189757.830,5555913.410,6107693.363,3391040.373,-77697.613,2794355.139

In [32]:
df_merged.columns

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 13 Wks',
       'Latest 13 vs YA', 'Latest 26 Wks', 'Latest 26 vs YA', 'Latest 52 Wks',
       'Latest 52 vs YA', 'Tangible Brands', 'Growing Penetration',
       'Accelerating Penetration', 'Top Opportunity',
       'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks',
       'Value vs YA (Abs Change) Latest 13 Wks',
       'Value due to Buyers YA Latest 13 Wks',
       'Value due to Occasions per Buyer YA Latest 13 Wks',
       'Value due to Value per Occasion YA Latest 13 Wks'],
      dtype='object')

In [33]:
# calculate contribution percentages for each value component and week
weeks = ['52','26','13']
components = ['Value due to Buyers YA','Value due to Occasions per Buyer YA','Value due to Value per Occasion YA']

for wk in weeks:
    denom_col = f'Value vs YA (Abs Change) Latest {wk} Wks'
    for comp in components:
        num_col = f'{comp} Latest {wk} Wks'
        new_col = f'Contribution {comp} Latest {wk} Wks'
        df_merged[new_col] = df_merged[num_col] / df_merged[denom_col] * 100

# inspect new columns
df_merged.columns[-9:]

Index(['Contribution Value due to Buyers YA Latest 52 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 52 Wks',
       'Contribution Value due to Value per Occasion YA Latest 52 Wks',
       'Contribution Value due to Buyers YA Latest 26 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 26 Wks',
       'Contribution Value due to Value per Occasion YA Latest 26 Wks',
       'Contribution Value due to Buyers YA Latest 13 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 13 Wks',
       'Contribution Value due to Value per Occasion YA Latest 13 Wks'],
      dtype='object')

In [34]:
df_merged

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks,Latest 13 vs YA,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks,Value vs YA (Abs Change) Latest 13 Wks,Value due to Buyers YA Latest 13 Wks,Value due to Occasions per Buyer YA Latest 13 Wks,Value due to Value per Occasion YA Latest 13 Wks,Contribution Value due to Buyers YA Latest 52 Wks,Contribution Value due to Occasions per Buyer YA Latest 52 Wks,Contribution Value due to Value per Occasion YA Latest 52 Wks,Contribution Value due to Buyers YA Latest 26 Wks,Contribution Value due to Occasions per Buyer YA Latest 26 Wks,Contribution Value due to Value per Occasion YA Latest 26 Wks,Contribution Value due to Buyers YA Latest 13 Wks,Contribution Value due to Occasions per Buyer YA Latest 13 Wks,Contribution Value due to Value per Occasion YA Latest 13 Wks
0,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,2.408,0.329,4.088,0.397,6.471,-0.118,Yes,Yes,Yes,Yes,5.734323e+05,-1.623504e+05,-204188.821,9.399717e+05,7.413010e+05,461393.497,-111508.894,391415.383,374039.448,338406.859,-175701.539,211333.130,-28.312050,-35.608183,163.920256,62.241042,-15.042323,52.801137,90.473575,-46.974066,56.500225
1,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),Germany,4.452,0.685,5.862,0.604,8.721,0.994,Yes,Yes,Yes,Yes,5.564507e+06,1.462272e+07,-6580394.537,-2.477823e+06,2.611671e+06,6715569.393,-1248959.403,-2854942.543,4317724.147,4972905.236,-284972.102,-370209.842,262.785442,-118.256553,-44.529072,257.136916,-47.822240,-109.314800,115.174223,-6.600053,-8.574189
2,34,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,PRIVATE LABEL,PRIVATE LABEL,Spain,5.510,0.961,6.816,0.645,9.154,0.106,Yes,Yes,Yes,Yes,1.203883e+06,1.037430e+06,-498957.209,6.654179e+05,1.874661e+06,2904742.240,-2116774.234,1086704.131,2781291.740,2843513.326,-701616.229,639386.324,86.173653,-41.445656,55.272637,154.947593,-112.915035,57.968031,102.237147,-25.226272,22.988826
3,41,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,BLUESUN,FIT (BLUESUN),Germany,0.573,0.324,0.938,0.209,2.664,1.724,Yes,Yes,Yes,Yes,8.113071e+06,8.636910e+06,-2406019.763,1.882164e+06,8.539937e+05,766592.965,-159926.614,247329.249,1111612.552,1085381.580,-82128.524,108352.715,106.456728,-29.656091,23.199159,89.765648,-18.726908,28.961485,97.640277,-7.388233,9.747345
4,52,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),France,4.613,0.690,7.880,0.866,12.222,-0.262,Yes,Yes,Yes,Yes,-1.202351e+04,-6.439092e+05,3112041.214,-2.480173e+06,1.080989e+07,5064231.064,189757.830,5555913.410,6107693.363,3391040.373,-77697.613,2794355.139,5355.417515,-25882.965583,20627.693433,46.848108,1.755409,51.396556,55.520803,-1.272127,45.751399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,2961,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,HIPP,HIPP (HIPP),Germany,1.030,0.347,1.592,0.217,2.977,0.584,Yes,Yes,Yes,Yes,2.919283e+05,2.214070e+06,320860.692,-2.243004e+06,9.228619e+05,734165.558,1735682.647,-1546982.068,317747.960,747590.073,-304610.135,-125232.185,758.429439,109.910786,-768.340669,79.553136,188.076104,-167.628778,235.277694,-95.865331,-39.412428
202,2983,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,CERAVE,GB,1.355,0.206,2.115,0.291,2.904,0.103,Yes,Yes,Yes,Yes,1.276738e+06,1.112891e+06,3596135.105,-3.432283e+06,3.085639e+05,2317528.238,337714.832,-2346695.994,597328.391,1323122.498,138345.702,-864137.545,87.166752,281.665908,-268.832230,751.069179,109.447297,-760.521924,221.506715,23.160744,-144.667081
203,2984,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,GARNIER (L'OREAL / GARNIER),Germany,4.513,0.272,6.871,-0.121,10.268,0.283,Yes,Yes,Yes,Yes,1.217804e+07,1.138668e+06,4668895.745,6.370477e+06,5.163675e+06,-355804.262,1371007.036,4148472.216,3215901.276,648025.619,469111.130,2098768.077,9.350175,38.338636,52.311174,-6.890524,26.550996,80.339535,20.150669,14.587237,65.262205
204,2984,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,L'OREAL,GARNIER (L'OREAL / GARNIER),Spain,3.726,0.356,5.401,0.013,8.173,-0.264,Yes,Yes,Yes,Yes,-3.020150e+05,-3.924810e+05,-57875.801,1.483404e+05,-7.844706e+04,81205.053,-96383.990,-63265.513,235014.627,445401.573,-566464.288,356073.681,129.954120,19.163220,-49.116902,-103.515739,122.865014,80.647399,189.520788,-241.033631,151.511285
205,3030,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PRIVATE LABEL,PRIVATE LABEL,Germany,26.536,0.617,36.266,0.597,46.052,1.412,Yes,Yes,Yes,Yes,1.189308e+07,8.331078e+06,-7192195.944,1.075419e+07,6.105877e+06,2191631.841,-1376506.152,5290756.061,2954125.508,1534054.039,379142.039,1040928.492,70.049811,-60.473802,90.423947,35.893807,-22.543953,86.650218,51.929210,12.834324,35.236434

In [35]:
# Sort df_merged by Value vs YA (Abs Change) Latest 13 Wks in descending order
df_priority = df_merged.sort_values(
    by='Value vs YA (Abs Change) Latest 13 Wks',
    ascending=False
).reset_index(drop=True)

df_priority

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks,Latest 13 vs YA,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks,Value vs YA (Abs Change) Latest 13 Wks,Value due to Buyers YA Latest 13 Wks,Value due to Occasions per Buyer YA Latest 13 Wks,Value due to Value per Occasion YA Latest 13 Wks,Contribution Value due to Buyers YA Latest 52 Wks,Contribution Value due to Occasions per Buyer YA Latest 52 Wks,Contribution Value due to Value per Occasion YA Latest 52 Wks,Contribution Value due to Buyers YA Latest 26 Wks,Contribution Value due to Occasions per Buyer YA Latest 26 Wks,Contribution Value due to Value per Occasion YA Latest 26 Wks,Contribution Value due to Buyers YA Latest 13 Wks,Contribution Value due to Occasions per Buyer YA Latest 13 Wks,Contribution Value due to Value per Occasion YA Latest 13 Wks
0,945,People Group,EUR,Total Panel,Total Outlets,FRAGRANCES,ALL OTHER,ALL OTHER,Germany,7.933,1.231,11.152,1.197,14.958,1.496,Yes,Yes,Yes,Yes,3.060578e+07,1.556521e+07,1.579449e+07,-753926.836,2.017368e+07,9874825.984,9627882.566,670968.489,1.163889e+07,8411001.484,2373145.467,854743.885,50.857096,51.606252,-2.463348,48.949063,47.724976,3.325960,72.266330,20.389785,7.343858
1,2704,People Group,EUR,Total Panel,Total Outlets,TOILET PAPER,ESSITY,ZEWA,Germany,7.653,1.332,10.194,-0.228,15.211,-0.173,Yes,Yes,Yes,Yes,1.098063e+06,-1.230273e+06,-3.302354e+06,5630704.642,4.640268e+06,-1233864.322,2202155.747,3671977.824,7.708975e+06,5205249.596,19624.210,2484103.913,-112.040317,-300.743520,512.785124,-26.590368,47.457512,79.132882,67.521941,0.254563,32.223530
2,2636,People Group,EUR,Total Panel,Total Outlets,SKIN CARE,WELEDA,WELEDA,Germany,2.795,0.538,3.588,0.179,5.124,0.551,Yes,Yes,Yes,Yes,1.223797e+07,5.385683e+06,-1.874638e+06,8726933.466,6.720554e+06,1262879.735,30536.562,5427136.736,7.084093e+06,2894778.166,258938.340,3930377.211,44.007984,-15.318209,71.310312,18.791304,0.454376,80.754305,40.863071,3.655208,55.481724
3,52,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),France,4.613,0.690,7.880,0.866,12.222,-0.262,Yes,Yes,Yes,Yes,-1.202351e+04,-6.439092e+05,3.112041e+06,-2480172.989,1.080989e+07,5064231.064,189757.830,5555913.410,6.107693e+06,3391040.373,-77697.613,2794355.139,5355.417515,-25882.965583,20627.693433,46.848108,1.755409,51.396556,55.520803,-1.272127,45.751399
4,2483,People Group,EUR,Total Panel,Total Outlets,SKIN CARE,L'OREAL,L'OREAL,GB,3.869,0.600,5.484,0.126,8.316,-0.549,Yes,Yes,Yes,Yes,2.934291e+06,-4.355903e+06,1.902233e+06,5387967.128,4.120311e+06,1242420.682,-521805.031,3399700.639,5.305297e+06,3588180.575,-1623257.286,3340367.448,-148.448223,64.827690,183.620743,30.153563,-12.664214,82.510770,67.633927,-30.596918,62.962876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,2664,People Group,EUR,Total Panel,Total Outlets,TOILET CLEANERS,HENKEL,WC FRISCH,Total Europe,4.515,0.357,6.927,0.524,8.768,-0.036,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,2704,People Group,EUR,Total Panel,Total Outlets,TOILET PAPER,ESSITY,ZEWA,Total Europe,2.084,0.343,2.783,-0.088,4.171,-0.071,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,2792,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,HALEON,SENSODYNE,Total Europe,8.826,0.245,12.649,0.064,17.307,0.385,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,2814,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,PRIVATE LABEL,PRIVATE LABEL,Total Europe,11.210,0.201,17.131,0.413,23.944,0.027,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,2891,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ALL OTHER,ALL OTHER,Total Europe,10.917,0.493,16.741,0.173,24.652,1.001,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# pg risk
- df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE'] if the Latest 52 vs YA is positive but if Latest 26 vs YA or Latest 13 vs YA is smaller than Latest 52 vs YA then it is declining growt

In [51]:
# define a helper that applies the two rules only for P&G brands
def calculate_pg_risk(row):
    if row['BRAND OWNER'] != 'PROCTER & GAMBLE':
        return 'No'                       # keep others as “No”
    l52 = row['Latest 52 vs YA']
    l26 = row['Latest 26 vs YA']
    l13 = row['Latest 13 vs YA']
    # declining‑growth
    if l52 > 0 and (l26 < l52 or l13 < l52):
        return 'Declining growth'
    # declining‑deceleration
    if l52 < 0 and (l26 > l52 or l13 > l52):
        return 'Declining Deceleration'
    return 'No'

# assign the column
df_final['P&G risk'] = df_final.apply(calculate_pg_risk, axis=1)

# quick check
print(df_final['P&G risk'].value_counts())
print(df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE'][['BRAND','country',
      'Latest 52 vs YA','Latest 26 vs YA','Latest 13 vs YA','P&G risk']].head())

P&G risk
No                        7870
Declining Deceleration     303
Declining growth           180
Name: count, dtype: int64
                                            BRAND       country  \
39                                     DON LIMPIO         Spain
40                                     DON LIMPIO  Total Europe
41    FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE)            GB
42    FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE)  Total Europe
116  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE)        France

     Latest 52 vs YA  Latest 26 vs YA  Latest 13 vs YA                P&G risk
39            -0.078           -0.074           -0.003  Declining Deceleration
40            -0.009           -0.009            0.000  Declining Deceleration
41            -0.285            0.144           -0.007  Declining Deceleration
42            -0.055            0.028           -0.001  Declining Deceleration
116           -0.624            0.032            0.123  Declining Deceleration

In [53]:
# RECHECK: Full verification of P&G risk logic starting with P&G data
print("="*80)
print("FULL RECHECK: LOGIC VERIFICATION")
print("="*80)

# Step 1: Filter for PROCTER & GAMBLE brands
pg_brands = df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE'].copy()
print(f"\n✓ Total P&G rows in df_final: {len(pg_brands)}")
print(f"✓ Total rows in df_final: {len(df_final)}")

# Step 2: Check P&G risk column exists
if 'P&G risk' in df_final.columns:
    print(f"✓ P&G risk column exists in df_final")
else:
    print("✗ ERROR: P&G risk column NOT found in df_final")

# Step 3: Verify logic for each risk category
print("\n" + "="*80)
print("RISK CATEGORY VERIFICATION")
print("="*80)

# Declining growth: Latest 52 > 0 AND (Latest 26 < Latest 52 OR Latest 13 < Latest 52)
declining_growth = pg_brands[
    (pg_brands['Latest 52 vs YA'] > 0) & 
    ((pg_brands['Latest 26 vs YA'] < pg_brands['Latest 52 vs YA']) | 
     (pg_brands['Latest 13 vs YA'] < pg_brands['Latest 52 vs YA']))
]

declining_growth_marked = pg_brands[pg_brands['P&G risk'] == 'Declining growth']

print(f"\n1. DECLINING GROWTH:")
print(f"   Expected logic count: {len(declining_growth)}")
print(f"   Marked as 'Declining growth': {len(declining_growth_marked)}")
print(f"   Match: {'✓ YES' if len(declining_growth) == len(declining_growth_marked) else '✗ NO'}")

# Declining Deceleration: Latest 52 < 0 AND (Latest 26 > Latest 52 OR Latest 13 > Latest 52)
declining_deceleration = pg_brands[
    (pg_brands['Latest 52 vs YA'] < 0) & 
    ((pg_brands['Latest 26 vs YA'] > pg_brands['Latest 52 vs YA']) | 
     (pg_brands['Latest 13 vs YA'] > pg_brands['Latest 52 vs YA']))
]

declining_deceleration_marked = pg_brands[pg_brands['P&G risk'] == 'Declining Deceleration']

print(f"\n2. DECLINING DECELERATION:")
print(f"   Expected logic count: {len(declining_deceleration)}")
print(f"   Marked as 'Declining Deceleration': {len(declining_deceleration_marked)}")
print(f"   Match: {'✓ YES' if len(declining_deceleration) == len(declining_deceleration_marked) else '✗ NO'}")

# No risk: Everything else (including non-P&G)
no_risk_pg = pg_brands[pg_brands['P&G risk'] == 'No']
print(f"\n3. NO RISK (P&G brands only):")
print(f"   Count: {len(no_risk_pg)}")

# Step 4: Overall distribution
print("\n" + "="*80)
print("OVERALL P&G RISK DISTRIBUTION")
print("="*80)
print(df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE']['P&G risk'].value_counts())

print("\n" + "="*80)
print("NON-P&G BRANDS - SHOULD ALL BE 'No'")
print("="*80)
non_pg = df_final[df_final['BRAND OWNER']!='PROCTER & GAMBLE']
non_pg_risk_dist = non_pg['P&G risk'].value_counts()
print(non_pg_risk_dist)
if len(non_pg_risk_dist) == 1 and non_pg_risk_dist.index[0] == 'No':
    print("✓ All non-P&G brands correctly marked as 'No'")
else:
    print("✗ ERROR: Some non-P&G brands have risk values other than 'No'")

# Step 5: Sample verification rows
print("\n" + "="*80)
print("SAMPLE ROWS - DETAILED VERIFICATION")
print("="*80)

print("\nSample DECLINING GROWTH rows:")
declining_growth_sample = declining_growth_marked[['BRAND', 'country', 'Latest 52 vs YA', 'Latest 26 vs YA', 'Latest 13 vs YA', 'P&G risk']].head(5)
print(declining_growth_sample)
print("Logic check (for each row, Latest 52 > 0 and min(26,13) < 52):")
for idx, row in declining_growth_sample.iterrows():
    l52 = row['Latest 52 vs YA']
    l26 = row['Latest 26 vs YA']
    l13 = row['Latest 13 vs YA']
    print(f"  {row['BRAND']}: 52={l52:.3f} (>0?{l52>0}), 26={l26:.3f}(<52?{l26<l52}), 13={l13:.3f}(<52?{l13<l52})")

print("\nSample DECLINING DECELERATION rows:")
declining_deceleration_sample = declining_deceleration_marked[['BRAND', 'country', 'Latest 52 vs YA', 'Latest 26 vs YA', 'Latest 13 vs YA', 'P&G risk']].head(5)
print(declining_deceleration_sample)
print("Logic check (for each row, Latest 52 < 0 and max(26,13) > 52):")
for idx, row in declining_deceleration_sample.iterrows():
    l52 = row['Latest 52 vs YA']
    l26 = row['Latest 26 vs YA']
    l13 = row['Latest 13 vs YA']
    print(f"  {row['BRAND']}: 52={l52:.3f} (<0?{l52<0}), 26={l26:.3f}(>52?{l26>l52}), 13={l13:.3f}(>52?{l13>l52})")

print("\n" + "="*80)
print("VERIFICATION COMPLETE")
print("="*80)

================================================================================
FULL RECHECK: LOGIC VERIFICATION
================================================================================

✓ Total P&G rows in df_final: 650
✓ Total rows in df_final: 8353
✓ P&G risk column exists in df_final

================================================================================
RISK CATEGORY VERIFICATION
================================================================================

1. DECLINING GROWTH:
   Expected logic count: 180
   Marked as 'Declining growth': 180
   Match: ✓ YES

2. DECLINING DECELERATION:
   Expected logic count: 303
   Marked as 'Declining Deceleration': 303
   Match: ✓ YES

3. NO RISK (P&G brands only):
   Count: 167

================================================================================
OVERALL P&G RISK DISTRIBUTION
================================================================================
P&G risk
Declining Deceleration    303
Declining growth          180
No                        167
Name: count, dtype: int64

================================================================================
NON-P&G BRANDS - SHOULD ALL BE 'No'
================================================================================
P&G risk
No    7703
Name: count, dtype: int64
✓ All non-P&G brands correctly marked as 'No'

================================================================================
SAMPLE ROWS - DETAILED VERIFICATION
================================================================================

Sample DECLINING GROWTH rows:
                                            BRAND       country  \
117  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE)            GB
118  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE)       Germany
119  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE)  Total Europe
162   DREFT (PROCTER & GAMBLE / PROCTER & GAMBLE)        France
163   DREFT (PROCTER & GAMBLE / PROCTER & GAMBLE)  Total Europe

     Latest 52 vs YA  Latest 26 vs YA  Latest 13 vs YA          P&G risk
117            1.375            0.507           -0.179  Declining growth
118            0.262            0.101           -0.046  Declining growth
119            0.202            0.121           -0.028  Declining growth
162            0.073            0.049              NaN  Declining growth
163            0.014            0.009              NaN  Declining growth
Logic check (for each row, Latest 52 > 0 and min(26,13) < 52):
  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=1.375 (>0?True), 26=0.507(<52?True), 13=-0.179(<52?True)
  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=0.262 (>0?True), 26=0.101(<52?True), 13=-0.046(<52?True)
  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=0.202 (>0?True), 26=0.121(<52?True), 13=-0.028(<52?True)
  DREFT (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=0.073 (>0?True), 26=0.049(<52?True), 13=nan(<52?False)
  DREFT (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=0.014 (>0?True), 26=0.009(<52?True), 13=nan(<52?False)

Sample DECLINING DECELERATION rows:
                                            BRAND       country  \
39                                     DON LIMPIO         Spain
40                                     DON LIMPIO  Total Europe
41    FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE)            GB
42    FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE)  Total Europe
116  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE)        France

     Latest 52 vs YA  Latest 26 vs YA  Latest 13 vs YA                P&G risk
39            -0.078           -0.074           -0.003  Declining Deceleration
40            -0.009           -0.009            0.000  Declining Deceleration
41            -0.285            0.144           -0.007  Declining Deceleration
42            -0.055            0.028           -0.001  Declining Deceleration
116           -0.624            0.032            0.123  Declining Deceleration
Logic check (for each row, Latest 52 < 0 and max(26,13) > 52):
  DON LIMPIO: 52=-0.078 (<0?True), 26=-0.074(>52?True), 13=-0.003(>52?True)
  DON LIMPIO: 52=-0.009 (<0?True), 26=-0.009(>52?False), 13=0.000(>52?True)
  FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=-0.285 (<0?True), 26=0.144(>52?True), 13=-0.007(>52?True)
  FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=-0.055 (<0?True), 26=0.028(>52?True), 13=-0.001(>52?True)
  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=-0.624 (<0?True), 26=0.032(>52?True), 13=0.123(>52?True)

================================================================================
VERIFICATION COMPLETE
================================================================================

In [56]:
df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks,Latest 13 vs YA,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,P&G risk
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,0.868,0.082,1.295,-0.482,2.917,0.106,Yes,No,Yes,No,No
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.081,-0.092,0.303,-0.098,0.583,-0.146,No,No,Yes,No,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,NaN,NaN,NaN,-0.002,NaN,-0.050,No,No,No,No,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,2.500,-0.414,4.391,-0.735,7.297,-0.974,Yes,No,Yes,No,No
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,4.323,-0.164,7.250,-0.730,12.594,0.082,Yes,No,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8348,3076,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,NaN,-0.008,0.008,-0.001,0.009,0.001,No,No,No,No,No
8349,3076,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.110,0.008,0.162,0.023,0.249,-0.015,No,No,Yes,No,No
8350,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.002,0.002,0.002,0.002,0.002,0.002,No,No,No,No,No
8351,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.225,0.225,0.285,0.285,0.395,0.395,No,Yes,No,No,No
8352,3077,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.044,0.044,0.055,0.055,0.076,0.076,No,No,No,No,No

In [57]:
df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE']['P&G risk'].value_counts()

P&G risk
Declining Deceleration    303
Declining growth          180
No                        167
Name: count, dtype: int64

In [58]:
pg_risk_final=df_final[df_final['P&G risk']!='No']
pg_risk_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 13 Wks,Latest 13 vs YA,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,P&G risk
39,9,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,PROCTER & GAMBLE,DON LIMPIO,Spain,0.084,-0.003,0.093,-0.074,0.169,-0.078,No,No,Yes,No,Declining Deceleration
40,9,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,PROCTER & GAMBLE,DON LIMPIO,Total Europe,0.010,0.000,0.011,-0.009,0.020,-0.009,No,No,Yes,No,Declining Deceleration
41,10,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),GB,0.205,-0.007,0.641,0.144,1.119,-0.285,No,No,Yes,No,Declining Deceleration
42,10,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),Total Europe,0.039,-0.001,0.123,0.028,0.215,-0.055,No,No,Yes,No,Declining Deceleration
116,35,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,PROCTER & GAMBLE,ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE),France,3.500,0.123,4.881,0.032,7.183,-0.624,Yes,No,Yes,No,Declining Deceleration
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8256,3041,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,PAMPERS,France,2.010,-0.073,2.994,-0.369,4.740,-1.301,Yes,No,Yes,No,Declining Deceleration
8257,3041,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,PAMPERS,GB,3.646,0.516,5.980,0.876,8.156,1.360,Yes,Yes,No,No,Declining growth
8258,3041,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,PAMPERS,Germany,0.751,-0.377,1.255,-0.140,2.317,0.181,Yes,No,No,No,Declining growth
8259,3041,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,PAMPERS,Italy,1.719,-0.457,2.685,-0.873,4.248,-0.930,Yes,No,Yes,No,Declining Deceleration
8260,3041,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,PAMPERS,Total Europe,1.601,-0.084,2.544,-0.085,3.884,-0.088,Yes,No,Yes,No,Declining Deceleration

In [59]:
df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE'].shape

(650, 20)

In [60]:
df_final['P&G risk'].value_counts()

P&G risk
No                        7870
Declining Deceleration     303
Declining growth           180
Name: count, dtype: int64