In [11]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [12]:
# define file path and sheet names
file_path = "MAIN_Penetration and Value Drivers Template_raw data for Divyaa & Rinu v2.xlsx"
sheet1 = "Penetration Trends Template"
sheet2 = "KPIs - EU5 template"

# load both sheets skipping raw1 and assigning multi-row headers
# df1: skip first row then next 4 rows as headers
# df2: skip first row then next 2 rows as headers

df1 = pd.read_excel(
    file_path,
    sheet_name=sheet1,
   skiprows=1,
    header=[0,1,2,3]
)

df2 = pd.read_excel(
    file_path,
    sheet_name=sheet2,
    skiprows=1,
    header=[0,1]
)

# show some info
print("df1 shape:", df1.shape)
print("df1 columns:\n", df1.columns)
print("df2 shape:", df2.shape)
print("df2 columns:\n", df2.columns)

C:\Users\rdi5001\AppData\Roaming\Python\Python311\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Web Extension extension is not supported and will be removed
  warn(msg)

df1 shape: (3074, 31)
df1 columns:
 MultiIndex([(            'Unnamed: 0_level_0', 'Unnamed: 0_level_1', ...),
            (            'Unnamed: 1_level_0', 'Unnamed: 1_level_1', ...),
            (            'Unnamed: 2_level_0', 'Unnamed: 2_level_1', ...),
            (            'Unnamed: 3_level_0', 'Unnamed: 3_level_1', ...),
            (            'Unnamed: 4_level_0', 'Unnamed: 4_level_1', ...),
            (            'Unnamed: 5_level_0', 'Unnamed: 5_level_1', ...),
            (            'Unnamed: 6_level_0', 'Unnamed: 6_level_1', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            (                   'Penetration',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...),
            ('Penetration vs YA (Abs Change)',       'Total Europe', ...)],
           )
df2 shape: (5265, 18)
df2 columns:
 MultiIndex([(        'Unnamed: 0_level_0', ...),
            (        'Unnamed: 1_level_0', ...),
            (        'Unnamed: 2_level_0', ...),
            (        'Unnamed: 3_level_0', ...),
            (        'Unnamed: 4_level_0', ...),
            (        'Unnamed: 5_level_0', ...),
            (        'Unnamed: 6_level_0', ...),
            (        'Unnamed: 7_level_0', ...),
            ('Latest 52 Wks - w/e W4 Y26', ...),
            ('Latest 52 Wks - w/e W4 Y26', ...),
            ('Latest 52 Wks - w/e W4 Y26', ...),
            ('Latest 52 Wks - w/e W4 Y26', ...),
            ('Latest 52 Wks - w/e W4 Y26', ...),
            ('Latest 26 Wks - w/e W4 Y26', ...),
            ('Latest 26 Wks - w/e W4 Y26', ...),
            ('Latest 26 Wks - w/e W4 Y26', ...),
            ('Latest 26 Wks - w/e W4 Y26', ...),
            ('Latest 26 Wks - w/e W4 Y26', ...)],
           )

C:\Users\rdi5001\AppData\Roaming\Python\Python311\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Web Extension extension is not supported and will be removed
  warn(msg)

In [13]:
df1

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
     Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3069       People Group                EUR        Total Panel
3070       People Group                EUR        Total Panel
3071       People Group                EUR        Total Panel
3072       People Group                EUR        Total Panel
3073       People Group                EUR        Total Panel

     Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
     Unnamed: 3_level_1 Unnamed: 4_level_1    Unnamed: 5_level_1
     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3069      Total Outlets     SKIN CLEANSING                WELEDA
3070      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3071      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3072      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3073      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_0                Penetration  \
                   Unnamed: 6_level_1               Total Europe
                   Unnamed: 6_level_2         Unnamed: 7_level_2
                                BRAND Latest 52 Wks - w/e W4 Y26
0                        SCOTCH BRITE                      3.912
1                           ALL OTHER                     18.583
2            AJAX (COLGATE PALMOLIVE)                      0.193
3           BRAVO (COLGATE PALMOLIVE)                      0.825
4              MARIGOLD (FREUDENBERG)                      0.054
...                               ...                        ...
3069                           WELEDA                      0.106
3070                           FISSAN                      0.088
3071     PONDS (YELLOW WOOD PARTNERS)                      0.002
3072  ST. IVES (YELLOW WOOD PARTNERS)                      0.256
3073                DAISE (ZURU EDGE)                      0.087

                                                            \

             Unnamed: 8_level_2                     France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         2.304                      2.819
1                        11.894                     29.041
2                         0.104                        NaN
3                         0.502                        NaN
4                         0.028                        NaN
...                         ...                        ...
3069                      0.078                        NaN
3070                      0.048                        NaN
3071                      0.001                        NaN
3072                      0.160                        NaN
3073                      0.059                      0.005

                                                            \

                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         1.347                      0.578
1                        19.432                     25.447
2                           NaN                        NaN
3                           NaN                        NaN
4                           NaN                      0.279
...                         ...                        ...
3069                        NaN                      0.089
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                      1.327
3073                      0.005                      0.450

                                                            \

                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.328                      0.025
1                        16.651                      8.716
2                           NaN                        NaN
3                           NaN                        NaN
4                         0.145                        NaN
...                         ...                        ...
3069                      0.052                      0.207
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.832                        NaN
3073                      0.302                        NaN

                                                            \

                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                      6.966
1                         5.621                     24.480
2                           NaN                        NaN
3                           NaN                      3.350
4                           NaN                        NaN
...                         ...                        ...
3069                      0.162                      0.085
3070                        NaN                      0.523
3071                        NaN                        NaN
3072                        NaN                      0.008
3073                        NaN                        NaN

                                                            \

                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         4.423                     12.530
1                        15.143                     10.364
2                           NaN                      1.590
3                         2.184                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.034
3070                      0.289                        NaN
3071                        NaN                      0.011
3072                      0.005                        NaN
3073                        NaN                        NaN

                                Penetration vs YA (Abs Change)  \
                                                  Total Europe
                                           Unnamed: 19_level_2
     Latest 26 Wks - w/e W4 Y26     Latest 52 Wks - w/e W4 Y26
0                         7.331                         -0.216
1                         5.643                          1.210
2                         0.860                          0.016
3                           NaN                         -0.102
4                           NaN                         -0.001
...                         ...                            ...
3069                      0.002                         -0.048
3070                        NaN                         -0.025
3071                      0.002                          0.000
3072                        NaN                         -0.014
3073                        NaN                          0.087

                                                            \

            Unnamed: 20_level_2                     France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                     -0.251000                     -0.136
1                      0.627000                      3.909
2                     -0.001000                     -0.006
3                     -0.071000                        NaN
4                     -0.004000                        NaN
...                         ...                        ...
3069                  -0.004000                        NaN
3070                  -0.031000                        NaN
3071                   0.000071                        NaN
3072                   0.011000                        NaN
3073                   0.059000                      0.005

                                                            \

                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.365                     -0.170
1                         1.383                      1.192
2                        -0.006                        NaN
3                           NaN                        NaN
4                           NaN                     -0.006
...                         ...                        ...
3069                        NaN                      0.035
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                     -0.072
3073                      0.005                      0.450

                                                            \

                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.083                      0.000
1                         0.843                      0.877
2                           NaN                        NaN
3                           NaN                        NaN
4                        -0.022                        NaN
...                         ...                        ...
3069                      0.016                     -0.234
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.058                        NaN
3073                      0.302                        NaN

                                                            \

                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                     -1.439
1                         1.342                      1.566
2                           NaN                        NaN
3                           NaN                      0.180
4                           NaN                        NaN
...                         ...                        ...
3069                     -0.088                      0.053
3070                        NaN                     -0.147
3071                        NaN                        NaN
3072                        NaN                      0.000
3073                        NaN                        NaN

                                                            \

                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.775                      0.306
1                         0.724                     -1.347
2                           NaN                      0.139
3                         0.290                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.008
3070                     -0.185                        NaN
3071                        NaN                     -0.005
3072                     -0.004                        NaN
3073                        NaN                        NaN




     Latest 26 Wks - w/e W4 Y26
0                        -0.282
1                        -1.591
2                        -0.001
3                           NaN
4                           NaN
...                         ...
3069                      0.002
3070                        NaN
3071                     -0.008
3072                        NaN
3073                        NaN

[3074 rows x 31 columns]

In [ ]:
df1

In [ ]:
# Replace Unnamed columns in the 3rd header level (level index 2) after column 7 with 'Total Europe'
if isinstance(df1.columns, pd.MultiIndex):
    cols = list(df1.columns)
    new_cols = []
    for i, col in enumerate(cols):
        col_list = list(col)
        if i >= 7 and len(col_list) > 2 and isinstance(col_list[2], str) and col_list[2].startswith('Unnamed'):
            col_list[2] = col_list[1]
        new_cols.append(tuple(col_list))
    df1.columns = pd.MultiIndex.from_tuples(new_cols)

# display updated dataframe
df1

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
     Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3069       People Group                EUR        Total Panel
3070       People Group                EUR        Total Panel
3071       People Group                EUR        Total Panel
3072       People Group                EUR        Total Panel
3073       People Group                EUR        Total Panel

     Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
     Unnamed: 3_level_1 Unnamed: 4_level_1    Unnamed: 5_level_1
     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3069      Total Outlets     SKIN CLEANSING                WELEDA
3070      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3071      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3072      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3073      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_0                Penetration  \
                   Unnamed: 6_level_1               Total Europe
                   Unnamed: 6_level_2               Total Europe
                                BRAND Latest 52 Wks - w/e W4 Y26
0                        SCOTCH BRITE                      3.912
1                           ALL OTHER                     18.583
2            AJAX (COLGATE PALMOLIVE)                      0.193
3           BRAVO (COLGATE PALMOLIVE)                      0.825
4              MARIGOLD (FREUDENBERG)                      0.054
...                               ...                        ...
3069                           WELEDA                      0.106
3070                           FISSAN                      0.088
3071     PONDS (YELLOW WOOD PARTNERS)                      0.002
3072  ST. IVES (YELLOW WOOD PARTNERS)                      0.256
3073                DAISE (ZURU EDGE)                      0.087

                                                            \

                                                    France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         2.304                      2.819
1                        11.894                     29.041
2                         0.104                        NaN
3                         0.502                        NaN
4                         0.028                        NaN
...                         ...                        ...
3069                      0.078                        NaN
3070                      0.048                        NaN
3071                      0.001                        NaN
3072                      0.160                        NaN
3073                      0.059                      0.005

                                                            \

                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         1.347                      0.578
1                        19.432                     25.447
2                           NaN                        NaN
3                           NaN                        NaN
4                           NaN                      0.279
...                         ...                        ...
3069                        NaN                      0.089
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                      1.327
3073                      0.005                      0.450

                                                            \

                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.328                      0.025
1                        16.651                      8.716
2                           NaN                        NaN
3                           NaN                        NaN
4                         0.145                        NaN
...                         ...                        ...
3069                      0.052                      0.207
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.832                        NaN
3073                      0.302                        NaN

                                                            \

                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                      6.966
1                         5.621                     24.480
2                           NaN                        NaN
3                           NaN                      3.350
4                           NaN                        NaN
...                         ...                        ...
3069                      0.162                      0.085
3070                        NaN                      0.523
3071                        NaN                        NaN
3072                        NaN                      0.008
3073                        NaN                        NaN

                                                            \

                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         4.423                     12.530
1                        15.143                     10.364
2                           NaN                      1.590
3                         2.184                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.034
3070                      0.289                        NaN
3071                        NaN                      0.011
3072                      0.005                        NaN
3073                        NaN                        NaN

                                Penetration vs YA (Abs Change)  \
                                                  Total Europe
                                                  Total Europe
     Latest 26 Wks - w/e W4 Y26     Latest 52 Wks - w/e W4 Y26
0                         7.331                         -0.216
1                         5.643                          1.210
2                         0.860                          0.016
3                           NaN                         -0.102
4                           NaN                         -0.001
...                         ...                            ...
3069                      0.002                         -0.048
3070                        NaN                         -0.025
3071                      0.002                          0.000
3072                        NaN                         -0.014
3073                        NaN                          0.087

                                                            \

                                                    France
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                     -0.251000                     -0.136
1                      0.627000                      3.909
2                     -0.001000                     -0.006
3                     -0.071000                        NaN
4                     -0.004000                        NaN
...                         ...                        ...
3069                  -0.004000                        NaN
3070                  -0.031000                        NaN
3071                   0.000071                        NaN
3072                   0.011000                        NaN
3073                   0.059000                      0.005

                                                            \

                                                        GB
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.365                     -0.170
1                         1.383                      1.192
2                        -0.006                        NaN
3                           NaN                        NaN
4                           NaN                     -0.006
...                         ...                        ...
3069                        NaN                      0.035
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                     -0.072
3073                      0.005                      0.450

                                                            \

                                                   Germany
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.083                      0.000
1                         0.843                      0.877
2                           NaN                        NaN
3                           NaN                        NaN
4                        -0.022                        NaN
...                         ...                        ...
3069                      0.016                     -0.234
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.058                        NaN
3073                      0.302                        NaN

                                                            \

                                                     Italy
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                     -1.439
1                         1.342                      1.566
2                           NaN                        NaN
3                           NaN                      0.180
4                           NaN                        NaN
...                         ...                        ...
3069                     -0.088                      0.053
3070                        NaN                     -0.147
3071                        NaN                        NaN
3072                        NaN                      0.000
3073                        NaN                        NaN

                                                            \

                                                     Spain
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.775                      0.306
1                         0.724                     -1.347
2                           NaN                      0.139
3                         0.290                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.008
3070                     -0.185                        NaN
3071                        NaN                     -0.005
3072                     -0.004                        NaN
3073                        NaN                        NaN




     Latest 26 Wks - w/e W4 Y26
0                        -0.282
1                        -1.591
2                        -0.001
3                           NaN
4                           NaN
...                         ...
3069                      0.002
3070                        NaN
3071                     -0.008
3072                        NaN
3073                        NaN

[3074 rows x 31 columns]

In [16]:
# create a new view of df1 with the first two header rows removed
if isinstance(df1.columns, pd.MultiIndex) and df1.columns.nlevels > 2:
    df1_trimmed = df1.copy()
    df1_trimmed.columns = df1_trimmed.columns.droplevel([0,1])
else:
    df1_trimmed = df1

# display trimmed dataframe
print("Trimmed df1 columns:", df1_trimmed.columns[:10])
df1_trimmed

Trimmed df1 columns: MultiIndex([('Unnamed: 0_level_2',                     'People'),
            ('Unnamed: 1_level_2',                   'Currency'),
            ('Unnamed: 2_level_2',                'Total Panel'),
            ('Unnamed: 3_level_2',              'Total Outlets'),
            ('Unnamed: 4_level_2',                   'CATEGORY'),
            ('Unnamed: 5_level_2',                'BRAND OWNER'),
            ('Unnamed: 6_level_2',                      'BRAND'),
            (      'Total Europe', 'Latest 52 Wks - w/e W4 Y26'),
            (      'Total Europe', 'Latest 26 Wks - w/e W4 Y26'),
            (            'France', 'Latest 52 Wks - w/e W4 Y26')],
           )

     Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2  \
                 People           Currency        Total Panel
0          People Group                EUR        Total Panel
1          People Group                EUR        Total Panel
2          People Group                EUR        Total Panel
3          People Group                EUR        Total Panel
4          People Group                EUR        Total Panel
...                 ...                ...                ...
3069       People Group                EUR        Total Panel
3070       People Group                EUR        Total Panel
3071       People Group                EUR        Total Panel
3072       People Group                EUR        Total Panel
3073       People Group                EUR        Total Panel

     Unnamed: 3_level_2 Unnamed: 4_level_2    Unnamed: 5_level_2  \
          Total Outlets           CATEGORY           BRAND OWNER
0         Total Outlets   ABRASIVE CL PADS                    3M
1         Total Outlets   ABRASIVE CL PADS             ALL OTHER
2         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
3         Total Outlets   ABRASIVE CL PADS     COLGATE PALMOLIVE
4         Total Outlets   ABRASIVE CL PADS           FREUDENBERG
...                 ...                ...                   ...
3069      Total Outlets     SKIN CLEANSING                WELEDA
3070      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3071      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3072      Total Outlets     SKIN CLEANSING  YELLOW WOOD PARTNERS
3073      Total Outlets     SKIN CLEANSING             ZURU EDGE

                   Unnamed: 6_level_2               Total Europe  \
                                BRAND Latest 52 Wks - w/e W4 Y26
0                        SCOTCH BRITE                      3.912
1                           ALL OTHER                     18.583
2            AJAX (COLGATE PALMOLIVE)                      0.193
3           BRAVO (COLGATE PALMOLIVE)                      0.825
4              MARIGOLD (FREUDENBERG)                      0.054
...                               ...                        ...
3069                           WELEDA                      0.106
3070                           FISSAN                      0.088
3071     PONDS (YELLOW WOOD PARTNERS)                      0.002
3072  ST. IVES (YELLOW WOOD PARTNERS)                      0.256
3073                DAISE (ZURU EDGE)                      0.087

                                                    France  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         2.304                      2.819
1                        11.894                     29.041
2                         0.104                        NaN
3                         0.502                        NaN
4                         0.028                        NaN
...                         ...                        ...
3069                      0.078                        NaN
3070                      0.048                        NaN
3071                      0.001                        NaN
3072                      0.160                        NaN
3073                      0.059                      0.005

                                                        GB  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         1.347                      0.578
1                        19.432                     25.447
2                           NaN                        NaN
3                           NaN                        NaN
4                           NaN                      0.279
...                         ...                        ...
3069                        NaN                      0.089
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                      1.327
3073                      0.005                      0.450

                                                   Germany  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.328                      0.025
1                        16.651                      8.716
2                           NaN                        NaN
3                           NaN                        NaN
4                         0.145                        NaN
...                         ...                        ...
3069                      0.052                      0.207
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.832                        NaN
3073                      0.302                        NaN

                                                     Italy  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                      6.966
1                         5.621                     24.480
2                           NaN                        NaN
3                           NaN                      3.350
4                           NaN                        NaN
...                         ...                        ...
3069                      0.162                      0.085
3070                        NaN                      0.523
3071                        NaN                        NaN
3072                        NaN                      0.008
3073                        NaN                        NaN

                                                     Spain  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         4.423                     12.530
1                        15.143                     10.364
2                           NaN                      1.590
3                         2.184                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.034
3070                      0.289                        NaN
3071                        NaN                      0.011
3072                      0.005                        NaN
3073                        NaN                        NaN

                                              Total Europe  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         7.331                     -0.216
1                         5.643                      1.210
2                         0.860                      0.016
3                           NaN                     -0.102
4                           NaN                     -0.001
...                         ...                        ...
3069                      0.002                     -0.048
3070                        NaN                     -0.025
3071                      0.002                      0.000
3072                        NaN                     -0.014
3073                        NaN                      0.087

                                                    France  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                     -0.251000                     -0.136
1                      0.627000                      3.909
2                     -0.001000                     -0.006
3                     -0.071000                        NaN
4                     -0.004000                        NaN
...                         ...                        ...
3069                  -0.004000                        NaN
3070                  -0.031000                        NaN
3071                   0.000071                        NaN
3072                   0.011000                        NaN
3073                   0.059000                      0.005

                                                        GB  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.365                     -0.170
1                         1.383                      1.192
2                        -0.006                        NaN
3                           NaN                        NaN
4                           NaN                     -0.006
...                         ...                        ...
3069                        NaN                      0.035
3070                        NaN                        NaN
3071                        NaN                      0.005
3072                        NaN                     -0.072
3073                      0.005                      0.450

                                                   Germany  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.083                      0.000
1                         0.843                      0.877
2                           NaN                        NaN
3                           NaN                        NaN
4                        -0.022                        NaN
...                         ...                        ...
3069                      0.016                     -0.234
3070                        NaN                        NaN
3071                      0.005                        NaN
3072                      0.058                        NaN
3073                      0.302                        NaN

                                                     Italy  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                         0.025                     -1.439
1                         1.342                      1.566
2                           NaN                        NaN
3                           NaN                      0.180
4                           NaN                        NaN
...                         ...                        ...
3069                     -0.088                      0.053
3070                        NaN                     -0.147
3071                        NaN                        NaN
3072                        NaN                      0.000
3073                        NaN                        NaN

                                                     Spain  \
     Latest 26 Wks - w/e W4 Y26 Latest 52 Wks - w/e W4 Y26
0                        -0.775                      0.306
1                         0.724                     -1.347
2                           NaN                      0.139
3                         0.290                        NaN
4                           NaN                        NaN
...                         ...                        ...
3069                      0.076                      0.008
3070                     -0.185                        NaN
3071                        NaN                     -0.005
3072                     -0.004                        NaN
3073                        NaN                        NaN


     Latest 26 Wks - w/e W4 Y26
0                        -0.282
1                        -1.591
2                        -0.001
3                           NaN
4                           NaN
...                         ...
3069                      0.002
3070                        NaN
3071                     -0.008
3072                        NaN
3073                        NaN

[3074 rows x 31 columns]

In [19]:
df1_trimmed.columns[0:7]

MultiIndex([('Unnamed: 0_level_2',        'People'),
            ('Unnamed: 1_level_2',      'Currency'),
            ('Unnamed: 2_level_2',   'Total Panel'),
            ('Unnamed: 3_level_2', 'Total Outlets'),
            ('Unnamed: 4_level_2',      'CATEGORY'),
            ('Unnamed: 5_level_2',   'BRAND OWNER'),
            ('Unnamed: 6_level_2',         'BRAND')],
           )

In [ ]:
# alternative transformation using melt, treating first 7 columns as metadata
# use df_base from earlier steps
try:
    df_base = df1_trimmed
except NameError:
    df_base = df1

# determine metadata and data columns by position
metadata_cols = list(df_base.columns[:7])
# we'll slice by position for data rather than by labels

data_cols_raw = list(df_base.columns[7:])

print("Metadata cols:", metadata_cols)
print("First few raw data cols:", data_cols_raw[:5])


# slice the “data” portion of df_base once the first seven metadata
# columns have been removed
data_cols_raw = list(df_base.columns[7:])


# modify header2 (metric) names for data columns starting from original position 26 onwards
# original col index = 7 + idx in data_cols_raw
renamed_data = []
for idx, col in enumerate(data_cols_raw):
    c0, c1 = col
    if (7 + idx) >= 25:  # zero-based original
        c1 = f"{c1} vs YA"
    renamed_data.append((c0, c1))

# slice the data portion of df_base and then rename its columns

df_data = df_base.iloc[:, 7:].copy()
df_data.columns = pd.MultiIndex.from_tuples(renamed_data)

# also extract df_meta for later use

df_meta = df_base.iloc[:, :7].copy()

# flatten df_data columns
flat_cols = [f"{c0}|||{c1}" for c0, c1 in renamed_data]
df_flat = df_data.copy()
df_flat.columns = flat_cols

# add meta columns to flat
for col in metadata_cols:
    colname = col[1]
    df_flat[f"meta|||{colname}"] = df_meta[col].squeeze().values

# preserve row identifier
df_flat = df_flat.reset_index(drop=True)
df_flat['row_id'] = df_flat.index

# melt on metric columns
id_vars = ['row_id'] + [f"meta|||{col[1]}" for col in metadata_cols]
df_melt = df_flat.melt(id_vars=id_vars, var_name='combined', value_name='value')

# split combined
split_cols = df_melt['combined'].str.split('\\|\\|\\|', expand=True)
df_melt['country'] = split_cols[0]
df_melt['metric'] = split_cols[1]

# pivot back
df_final = df_melt.pivot_table(
    index=id_vars + ['country'],
    columns='metric',
    values='value',
    aggfunc='first'
).reset_index()

# clean metadata column names
for col in metadata_cols:
    df_final = df_final.rename(columns={f"meta|||{col[1]}": col[1]})

print("Transformed final shape:", df_final.shape)
print(df_final.head())

Metadata cols: [('Unnamed: 0_level_2', 'People'), ('Unnamed: 1_level_2', 'Currency'), ('Unnamed: 2_level_2', 'Total Panel'), ('Unnamed: 3_level_2', 'Total Outlets'), ('Unnamed: 4_level_2', 'CATEGORY'), ('Unnamed: 5_level_2', 'BRAND OWNER'), ('Unnamed: 6_level_2', 'BRAND')]
First few raw data cols: [('Total Europe', 'Latest 52 Wks - w/e W4 Y26'), ('Total Europe', 'Latest 26 Wks - w/e W4 Y26'), ('France', 'Latest 52 Wks - w/e W4 Y26'), ('France', 'Latest 26 Wks - w/e W4 Y26'), ('GB', 'Latest 52 Wks - w/e W4 Y26')]
vs YA should start at data_cols_raw index 12
Transformed final shape: (8339, 13)
metric  row_id        People Currency  Total Panel  Total Outlets  \
0            0  People Group      EUR  Total Panel  Total Outlets
1            0  People Group      EUR  Total Panel  Total Outlets
2            0  People Group      EUR  Total Panel  Total Outlets
3            0  People Group      EUR  Total Panel  Total Outlets
4            0  People Group      EUR  Total Panel  Total Outlets

metric          CATEGORY BRAND OWNER         BRAND  country  \
0       ABRASIVE CL PADS          3M  SCOTCH BRITE   France
1       ABRASIVE CL PADS          3M  SCOTCH BRITE       GB
2       ABRASIVE CL PADS          3M  SCOTCH BRITE  Germany
3       ABRASIVE CL PADS          3M  SCOTCH BRITE    Italy
4       ABRASIVE CL PADS          3M  SCOTCH BRITE    Spain

metric  Latest 26 Wks - w/e W4 Y26  Latest 26 Wks - w/e W4 Y26 vs YA  \
0                            1.347                               NaN
1                            0.328                               NaN
2                            0.025                             0.025
3                            4.423                            -0.775
4                            7.331                            -0.282

metric  Latest 52 Wks - w/e W4 Y26  Latest 52 Wks - w/e W4 Y26 vs YA
0                            2.819                               NaN
1                            0.578                               NaN
2                            0.025                             0.000
3                            6.966                            -1.439
4                           12.530                             0.306

In [39]:

df_final.columns.tolist()[7:24]

['BRAND',
 'country',
 'Latest 26 Wks',
 'Latest 26 Wks vs YA',
 'Latest 52 Wks',
 'Latest 52 Wks vs YA']

In [33]:
df_final.columns=['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country',
       'Latest 26 Wks', 'Latest 26 vs YA',
       'Latest 52 Wks', 'Latest 52 vs YA']

In [13]:
df_final = df_final.fillna(0)

print("NaN values after filling:")
print(df_final.isna().sum())

NaN values after filling:
row_id             0
People             0
Currency           0
Total Panel        0
Total Outlets      0
CATEGORY           0
BRAND OWNER        0
BRAND              0
country            0
Latest 26 Wks      0
Latest 26 vs YA    0
Latest 52 Wks      0
Latest 52 vs YA    0
dtype: int64

# >2pp

In [14]:
df_final['Tangible Brands'] = df_final['Latest 52 Wks'].apply(lambda x: 'Yes' if x > 2 else 'No')

# display a sample
df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,0.000,2.819,0.000,Yes
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,0.000,0.578,0.000,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439,Yes
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000,No
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.000,0.256,0.000,No
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.000,0.005,0.000,No
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.000,0.450,0.000,No
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.000,0.087,0.000,No

In [35]:
df_final.columns

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA'],
      dtype='object')

# Growing penetration, Latest 26w vs year ago should be greater than .2

In [16]:
df_final['Growing Penetration'] = df_final['Latest 26 vs YA'].apply(lambda x: 'Yes' if x > 0.2 else 'No')

df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,0.000,2.819,0.000,Yes,No
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,0.000,0.578,0.000,No,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000,No,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439,Yes,No
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000,No,No
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.000,0.256,0.000,No,No
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.000,0.005,0.000,No,No
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.000,0.450,0.000,No,No
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.000,0.087,0.000,No,No

In [17]:
df_final['Growing Penetration'].value_counts()

Growing Penetration
No     7959
Yes     380
Name: count, dtype: int64

# Accelerating Penetration
- Penetration growth in latest 26 weeks vs YA  is greater than penetration change in latest 52. Consider only YA.

In [19]:
df_final['Accelerating Penetration'] = (df_final['Latest 26 vs YA'] > df_final['Latest 52 vs YA']).apply(lambda x: 'Yes' if x else 'No')

df_final[['BRAND', 'country', 'Latest 26 vs YA', 'Latest 52 vs YA', 'Accelerating Penetration']].head(10)

,BRAND,country,Latest 26 vs YA,Latest 52 vs YA,Accelerating Penetration
0,SCOTCH BRITE,France,0.000,0.000,No
1,SCOTCH BRITE,GB,0.000,0.000,No
2,SCOTCH BRITE,Germany,0.025,0.000,Yes
3,SCOTCH BRITE,Italy,-0.775,-1.439,Yes
4,SCOTCH BRITE,Spain,-0.282,0.306,No
5,SCOTCH BRITE,Total Europe,0.000,0.000,No
6,ALL OTHER,France,0.000,0.000,No
7,ALL OTHER,GB,0.000,0.000,No
8,ALL OTHER,Germany,1.342,0.877,Yes
9,ALL OTHER,Italy,0.724,1.566,No

In [20]:
df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,0.000,2.819,0.000,Yes,No,No
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,0.000,0.578,0.000,No,No,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000,No,No,Yes
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439,Yes,No,Yes
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000,No,No,No
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.000,0.256,0.000,No,No,No
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.000,0.005,0.000,No,No,No
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.000,0.450,0.000,No,No,No
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.000,0.087,0.000,No,No,No

In [21]:
df_final['Top Opportunity'] = (
    (df_final['Tangible Brands'] == 'Yes') & 
    (df_final['Growing Penetration'] == 'Yes') & 
    (df_final['Accelerating Penetration'] == 'Yes')
).apply(lambda x: 'Yes' if x else 'No')

# display sample with all columns
df_final[['BRAND', 'country', 'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration', 'Top Opportunity']].head(10)

,BRAND,country,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity
0,SCOTCH BRITE,France,Yes,No,No,No
1,SCOTCH BRITE,GB,No,No,No,No
2,SCOTCH BRITE,Germany,No,No,Yes,No
3,SCOTCH BRITE,Italy,Yes,No,Yes,No
4,SCOTCH BRITE,Spain,Yes,No,No,No
5,SCOTCH BRITE,Total Europe,Yes,No,No,No
6,ALL OTHER,France,Yes,No,No,No
7,ALL OTHER,GB,Yes,No,No,No
8,ALL OTHER,Germany,Yes,Yes,Yes,Yes
9,ALL OTHER,Italy,Yes,Yes,No,No

In [22]:
Top_Oppurtunity=df_final[df_final['Top Opportunity']=='Yes']
Top_Oppurtunity

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity
8,1,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,Germany,5.621,1.342,8.716,0.877,Yes,Yes,Yes,Yes
15,3,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,COLGATE PALMOLIVE,BRAVO (COLGATE PALMOLIVE),Italy,2.184,0.290,3.350,0.180,Yes,Yes,Yes,Yes
21,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,4.371,0.630,6.745,0.319,Yes,Yes,Yes,Yes
30,7,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,Italy,11.639,1.371,17.913,0.985,Yes,Yes,Yes,Yes
62,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),Germany,6.692,1.132,8.908,1.125,Yes,Yes,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7622,2809,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,PRIVATE LABEL,PRIVATE LABEL,Spain,26.097,0.383,34.669,-0.001,Yes,Yes,Yes,Yes
7632,2812,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,PROCTER & GAMBLE,ORAL B,Italy,6.017,0.406,9.094,0.281,Yes,Yes,Yes,Yes
7695,2832,People Group,EUR,Total Panel,Total Outlets,VITAMIN SUPPLEMENTS,ALL OTHER,ALL OTHER,Germany,14.466,2.155,19.098,1.344,Yes,Yes,Yes,Yes
7866,2903,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,BOLTON GROUP,ACQUA ALLE ROSE,Italy,1.817,0.391,3.015,0.164,Yes,Yes,Yes,Yes
8055,2974,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,KIMBERLY CLARK,HUGGIES,Italy,1.356,0.337,2.063,0.259,Yes,Yes,Yes,Yes

# df2

In [23]:
# Process df2: Keep MultiIndex to properly extract header0 and header1
df2_copy = df2.copy()

print("df2 original columns (first 12):", df2_copy.columns[:12].tolist())
print("df2 MultiIndex nlevels:", df2_copy.columns.nlevels)

# Identify metadata columns (first 8 by position)
metadata_cols = list(df2_copy.columns[:8])
data_cols = list(df2_copy.columns[8:])

print("\nMetadata columns:", metadata_cols)
print("Data columns count:", len(data_cols))
print("Data columns sample (tuples):", data_cols[:5])

# Process the data columns: extract header0 (time period) + header1 (metric)
renamed_cols = []

for col in data_cols:
    h0, h1 = col[0], col[1]  # col is a tuple (header0, header1)
    
    # Split header0 at '-' and take the first part
    time_period = h0.split('-')[0].strip()
    
    # Combine metric + time period
    new_col = f"{h1} {time_period}"
    renamed_cols.append(new_col)

print("\nRenamed data columns (first 10):", renamed_cols[:10])

# Create new dataframe with renamed columns
df2_meta = df2_copy.iloc[:, :8].copy()
df2_data = df2_copy.iloc[:, 8:].copy()

# Flatten column names to single level
df2_meta.columns = [col[1] for col in df2_meta.columns]
df2_data.columns = renamed_cols

# Concatenate metadata and data
df2_processed = pd.concat([df2_meta, df2_data], axis=1)

print("\ndf2_processed shape:", df2_processed.shape)
print("df2_processed columns:", df2_processed.columns.tolist())
print("\nSample of df2_processed:")
df2_processed

df2 original columns (first 12): [('Unnamed: 0_level_0', 'People'), ('Unnamed: 1_level_0', 'Currency'), ('Unnamed: 2_level_0', 'Total Panel'), ('Unnamed: 3_level_0', 'Total Outlets'), ('Unnamed: 4_level_0', 'Countries'), ('Unnamed: 5_level_0', 'CATEGORY'), ('Unnamed: 6_level_0', 'BRAND OWNER'), ('Unnamed: 7_level_0', 'BRAND'), ('Latest 52 Wks - w/e W4 Y26', 'Penetration'), ('Latest 52 Wks - w/e W4 Y26', 'Value vs YA (Abs Change)'), ('Latest 52 Wks - w/e W4 Y26', 'Value due to Buyers YA'), ('Latest 52 Wks - w/e W4 Y26', 'Value due to Occasions per Buyer YA')]
df2 MultiIndex nlevels: 2

Metadata columns: [('Unnamed: 0_level_0', 'People'), ('Unnamed: 1_level_0', 'Currency'), ('Unnamed: 2_level_0', 'Total Panel'), ('Unnamed: 3_level_0', 'Total Outlets'), ('Unnamed: 4_level_0', 'Countries'), ('Unnamed: 5_level_0', 'CATEGORY'), ('Unnamed: 6_level_0', 'BRAND OWNER'), ('Unnamed: 7_level_0', 'BRAND')]
Data columns count: 10
Data columns sample (tuples): [('Latest 52 Wks - w/e W4 Y26', 'Penetration'), ('Latest 52 Wks - w/e W4 Y26', 'Value vs YA (Abs Change)'), ('Latest 52 Wks - w/e W4 Y26', 'Value due to Buyers YA'), ('Latest 52 Wks - w/e W4 Y26', 'Value due to Occasions per Buyer YA'), ('Latest 52 Wks - w/e W4 Y26', 'Value due to Value per Occasion YA')]

Renamed data columns (first 10): ['Penetration Latest 52 Wks', 'Value vs YA (Abs Change) Latest 52 Wks', 'Value due to Buyers YA Latest 52 Wks', 'Value due to Occasions per Buyer YA Latest 52 Wks', 'Value due to Value per Occasion YA Latest 52 Wks', 'Penetration Latest 26 Wks', 'Value vs YA (Abs Change) Latest 26 Wks', 'Value due to Buyers YA Latest 26 Wks', 'Value due to Occasions per Buyer YA Latest 26 Wks', 'Value due to Value per Occasion YA Latest 26 Wks']

df2_processed shape: (5265, 18)
df2_processed columns: ['People', 'Currency', 'Total Panel', 'Total Outlets', 'Countries', 'CATEGORY', 'BRAND OWNER', 'BRAND', 'Penetration Latest 52 Wks', 'Value vs YA (Abs Change) Latest 52 Wks', 'Value due to Buyers YA Latest 52 Wks', 'Value due to Occasions per Buyer YA Latest 52 Wks', 'Value due to Value per Occasion YA Latest 52 Wks', 'Penetration Latest 26 Wks', 'Value vs YA (Abs Change) Latest 26 Wks', 'Value due to Buyers YA Latest 26 Wks', 'Value due to Occasions per Buyer YA Latest 26 Wks', 'Value due to Value per Occasion YA Latest 26 Wks']

Sample of df2_processed:

,People,Currency,Total Panel,Total Outlets,Countries,CATEGORY,BRAND OWNER,BRAND,Penetration Latest 52 Wks,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Penetration Latest 26 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks
0,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,3M,SCOTCH BRITE,2.819,-2.816270e+05,-125211.791,-6940.783,-149477.240,1.347,-467747.807,-387638.647,92471.589,-172577.218
1,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,29.041,1.402825e+07,5187110.253,4381444.346,4459689.949,19.432,5185968.980,1594138.737,1249741.075,2342089.327
2,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,COLGATE PALMOLIVE,AJAX (COLGATE PALMOLIVE),NaN,-4.565028e+03,NaN,NaN,NaN,NaN,-4565.028,NaN,NaN,NaN
3,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,FREUDENBERG,VILEDA,0.488,2.342170e+05,310890.571,-2794.563,-73880.617,0.300,75419.427,91236.705,-150.418,-15666.805
4,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,37.546,1.144235e+06,-231956.527,-777751.959,2153942.130,26.582,362865.133,-515417.269,-508856.667,1387139.758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5260,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,SODALIS,VITESSE (SODALIS),1.049,-2.577675e+05,-654667.168,373307.212,23593.632,0.864,-63081.555,92476.682,-167001.323,11444.334
5261,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,DOVE (UNILEVER / UNILEVER),NaN,-2.836982e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5262,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,REN (UNILEVER / UNILEVER),0.005,1.886498e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5263,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,WELEDA,WELEDA,0.034,1.966220e+04,19322.068,161.330,181.241,0.002,4269.966,NaN,NaN,NaN
5264,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,YELLOW WOOD PARTNERS,PONDS (YELLOW WOOD PARTNERS),0.011,-2.534527e+03,-3278.416,0.000,745.103,0.002,-4066.432,-4573.227,44.810,466.165

In [24]:
df2_processed=df2_processed.fillna(0)
df2_processed

,People,Currency,Total Panel,Total Outlets,Countries,CATEGORY,BRAND OWNER,BRAND,Penetration Latest 52 Wks,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Penetration Latest 26 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks
0,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,3M,SCOTCH BRITE,2.819,-2.816270e+05,-125211.791,-6940.783,-149477.240,1.347,-467747.807,-387638.647,92471.589,-172577.218
1,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,29.041,1.402825e+07,5187110.253,4381444.346,4459689.949,19.432,5185968.980,1594138.737,1249741.075,2342089.327
2,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,COLGATE PALMOLIVE,AJAX (COLGATE PALMOLIVE),0.000,-4.565028e+03,0.000,0.000,0.000,0.000,-4565.028,0.000,0.000,0.000
3,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,FREUDENBERG,VILEDA,0.488,2.342170e+05,310890.571,-2794.563,-73880.617,0.300,75419.427,91236.705,-150.418,-15666.805
4,People Group,EUR,Total Panel,Total Outlets,France,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,37.546,1.144235e+06,-231956.527,-777751.959,2153942.130,26.582,362865.133,-515417.269,-508856.667,1387139.758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5260,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,SODALIS,VITESSE (SODALIS),1.049,-2.577675e+05,-654667.168,373307.212,23593.632,0.864,-63081.555,92476.682,-167001.323,11444.334
5261,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,DOVE (UNILEVER / UNILEVER),0.000,-2.836982e+04,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5262,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,UNILEVER,REN (UNILEVER / UNILEVER),0.005,1.886498e+04,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5263,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,WELEDA,WELEDA,0.034,1.966220e+04,19322.068,161.330,181.241,0.002,4269.966,0.000,0.000,0.000
5264,People Group,EUR,Total Panel,Total Outlets,Spain,SKIN CLEANSING,YELLOW WOOD PARTNERS,PONDS (YELLOW WOOD PARTNERS),0.011,-2.534527e+03,-3278.416,0.000,745.103,0.002,-4066.432,-4573.227,44.810,466.165

In [25]:
df2_processed.columns

Index(['People', 'Currency', 'Total Panel', 'Total Outlets', 'Countries',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'Penetration Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Penetration Latest 26 Wks', 'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks'],
      dtype='object')

In [26]:
Top_Oppurtunity

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity
8,1,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,Germany,5.621,1.342,8.716,0.877,Yes,Yes,Yes,Yes
15,3,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,COLGATE PALMOLIVE,BRAVO (COLGATE PALMOLIVE),Italy,2.184,0.290,3.350,0.180,Yes,Yes,Yes,Yes
21,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,4.371,0.630,6.745,0.319,Yes,Yes,Yes,Yes
30,7,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,Italy,11.639,1.371,17.913,0.985,Yes,Yes,Yes,Yes
62,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),Germany,6.692,1.132,8.908,1.125,Yes,Yes,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7622,2809,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,PRIVATE LABEL,PRIVATE LABEL,Spain,26.097,0.383,34.669,-0.001,Yes,Yes,Yes,Yes
7632,2812,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,PROCTER & GAMBLE,ORAL B,Italy,6.017,0.406,9.094,0.281,Yes,Yes,Yes,Yes
7695,2832,People Group,EUR,Total Panel,Total Outlets,VITAMIN SUPPLEMENTS,ALL OTHER,ALL OTHER,Germany,14.466,2.155,19.098,1.344,Yes,Yes,Yes,Yes
7866,2903,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,BOLTON GROUP,ACQUA ALLE ROSE,Italy,1.817,0.391,3.015,0.164,Yes,Yes,Yes,Yes
8055,2974,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,KIMBERLY CLARK,HUGGIES,Italy,1.356,0.337,2.063,0.259,Yes,Yes,Yes,Yes

In [27]:
# merge procedure between Top_Oppurtunity (from df_final) and df2_processed
# assume df_final and df2_processed exist

# select necessary columns from df2_processed
right_cols = [
    'Countries','CATEGORY','BRAND',
    'Value vs YA (Abs Change) Latest 52 Wks',
    'Value due to Buyers YA Latest 52 Wks',
    'Value due to Occasions per Buyer YA Latest 52 Wks',
    'Value due to Value per Occasion YA Latest 52 Wks',
    'Value vs YA (Abs Change) Latest 26 Wks',
    'Value due to Buyers YA Latest 26 Wks',
    'Value due to Occasions per Buyer YA Latest 26 Wks',
    'Value due to Value per Occasion YA Latest 26 Wks',
]

# build small right table
df2_small = df2_processed[right_cols].copy()

# perform left merge
Top_Oppurtunity = df_final[df_final['Top Opportunity']=='Yes']

df_merged = Top_Oppurtunity.merge(
    df2_small,
    left_on=['country','CATEGORY','BRAND'],
    right_on=['Countries','CATEGORY','BRAND'],
    how='left'
)

# drop auxiliary column
if 'Countries' in df_merged.columns:
    df_merged = df_merged.drop(columns=['Countries'])

# show result
print(df_merged.columns)
df_merged.head()

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks'],
      dtype='object')

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks
0,1,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,Germany,5.621,1.342,8.716,0.877,Yes,Yes,Yes,Yes,791926.913,1.110129e+06,260424.394,-578625.594,446782.207,1.470200e+06,168429.175,-1191849.092
1,3,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,COLGATE PALMOLIVE,BRAVO (COLGATE PALMOLIVE),Italy,2.184,0.290,3.350,0.180,Yes,Yes,Yes,Yes,-42369.452,1.086605e+05,-68570.221,-82461.060,78686.554,1.437160e+05,-18118.708,-46911.006
2,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,4.371,0.630,6.745,0.319,Yes,Yes,Yes,Yes,853160.781,4.443390e+05,-420833.153,829654.867,609011.228,7.507220e+05,-410890.572,269179.707
3,7,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,Italy,11.639,1.371,17.913,0.985,Yes,Yes,Yes,Yes,1242617.725,6.870830e+05,413898.999,141636.099,978145.473,7.783581e+05,-47557.527,247345.390
4,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),Germany,6.692,1.132,8.908,1.125,Yes,Yes,Yes,Yes,6461534.656,1.643899e+07,-7256988.559,-2720452.272,4688767.982,1.146098e+07,-4419524.947,-2352686.459

In [28]:
df_merged.columns

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks'],
      dtype='object')

In [29]:
# calculate contribution percentages for each value component and week
weeks = ['52','26']
components = ['Value due to Buyers YA','Value due to Occasions per Buyer YA','Value due to Value per Occasion YA']

for wk in weeks:
    denom_col = f'Value vs YA (Abs Change) Latest {wk} Wks'
    for comp in components:
        num_col = f'{comp} Latest {wk} Wks'
        new_col = f'Contribution {comp} Latest {wk} Wks'
        df_merged[new_col] = df_merged[num_col] / df_merged[denom_col] * 100

# inspect new columns
df_merged.columns

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks',
       'Contribution Value due to Buyers YA Latest 52 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 52 Wks',
       'Contribution Value due to Value per Occasion YA Latest 52 Wks',
       'Contribution Value due to Buyers YA Latest 26 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 26 Wks',
       'Contribution Value due to Value per Occasion YA Latest 26 Wks'],
      dtype='object')

In [30]:
df_merged

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks,Contribution Value due to Buyers YA Latest 52 Wks,Contribution Value due to Occasions per Buyer YA Latest 52 Wks,Contribution Value due to Value per Occasion YA Latest 52 Wks,Contribution Value due to Buyers YA Latest 26 Wks,Contribution Value due to Occasions per Buyer YA Latest 26 Wks,Contribution Value due to Value per Occasion YA Latest 26 Wks
0,1,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,ALL OTHER,ALL OTHER,Germany,5.621,1.342,8.716,0.877,Yes,Yes,Yes,Yes,791926.913,1.110129e+06,260424.394,-578625.594,4.467822e+05,1.470200e+06,168429.175,-1191849.092,140.180709,32.884903,-73.065530,329.064162,37.698273,-266.762882
1,3,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,COLGATE PALMOLIVE,BRAVO (COLGATE PALMOLIVE),Italy,2.184,0.290,3.350,0.180,Yes,Yes,Yes,Yes,-42369.452,1.086605e+05,-68570.221,-82461.060,7.868655e+04,1.437160e+05,-18118.708,-46911.006,-256.459477,161.838820,194.623853,182.643656,-23.026435,-59.617563
2,5,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,FREUDENBERG,VILEDA,Germany,4.371,0.630,6.745,0.319,Yes,Yes,Yes,Yes,853160.781,4.443390e+05,-420833.153,829654.867,6.090112e+05,7.507220e+05,-410890.572,269179.707,52.081504,-49.326359,97.244844,123.268986,-67.468472,44.199465
3,7,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,NEWELL BRANDS,SPONTEX,Italy,11.639,1.371,17.913,0.985,Yes,Yes,Yes,Yes,1242617.725,6.870830e+05,413898.999,141636.099,9.781455e+05,7.783581e+05,-47557.527,247345.390,55.293192,33.308635,11.398204,79.574886,-4.862010,25.287178
4,18,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,ESSITY,TENA (ESSITY),Germany,6.692,1.132,8.908,1.125,Yes,Yes,Yes,Yes,6461534.656,1.643899e+07,-7256988.559,-2720452.272,4.688768e+06,1.146098e+07,-4419524.947,-2352686.459,254.413105,-112.310603,-42.102262,244.434825,-94.257702,-50.177071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,2809,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,PRIVATE LABEL,PRIVATE LABEL,Spain,26.097,0.383,34.669,-0.001,Yes,Yes,Yes,Yes,292440.626,2.631219e+05,159853.843,-130532.641,2.008156e+05,3.808380e+05,-132024.757,-47996.443,89.974453,54.661982,-44.635604,189.645577,-65.744258,-23.900749
108,2812,People Group,EUR,Total Panel,Total Outlets,TOOTHPASTE,PROCTER & GAMBLE,ORAL B,Italy,6.017,0.406,9.094,0.281,Yes,Yes,Yes,Yes,1981101.690,6.255443e+05,-305772.939,1661329.651,2.206531e+06,7.431629e+05,283741.985,1179629.130,31.575577,-15.434490,83.858878,33.680142,12.859187,53.460792
109,2832,People Group,EUR,Total Panel,Total Outlets,VITAMIN SUPPLEMENTS,ALL OTHER,ALL OTHER,Germany,14.466,2.155,19.098,1.344,Yes,Yes,Yes,Yes,8623708.885,1.080711e+07,3044559.870,-5227967.820,1.123335e+07,1.237497e+07,-957854.403,-183771.025,125.318534,35.304530,-60.623195,110.162817,-8.526882,-1.635942
110,2903,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,BOLTON GROUP,ACQUA ALLE ROSE,Italy,1.817,0.391,3.015,0.164,Yes,Yes,Yes,Yes,119001.492,3.545233e+05,-42314.824,-193212.866,5.501768e+05,7.255667e+05,72770.081,-248162.122,297.915032,-35.558230,-162.361717,131.878814,13.226671,-45.105883
111,2974,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,KIMBERLY CLARK,HUGGIES,Italy,1.356,0.337,2.063,0.259,Yes,Yes,Yes,Yes,-3092.676,4.627969e+05,159714.843,-625604.424,1.199248e+05,4.884227e+05,-277301.933,-91199.930,-14964.288112,-5164.292768,20228.579521,407.274097,-231.229829,-76.047592

In [31]:
# Sort df_merged by Value vs YA (Abs Change) Latest 13 Wks in descending order
df_priority = df_merged.sort_values(
    by='Value vs YA (Abs Change) Latest 26 Wks',
    ascending=False
).reset_index(drop=True)

df_priority

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,Value vs YA (Abs Change) Latest 52 Wks,Value due to Buyers YA Latest 52 Wks,Value due to Occasions per Buyer YA Latest 52 Wks,Value due to Value per Occasion YA Latest 52 Wks,Value vs YA (Abs Change) Latest 26 Wks,Value due to Buyers YA Latest 26 Wks,Value due to Occasions per Buyer YA Latest 26 Wks,Value due to Value per Occasion YA Latest 26 Wks,Contribution Value due to Buyers YA Latest 52 Wks,Contribution Value due to Occasions per Buyer YA Latest 52 Wks,Contribution Value due to Value per Occasion YA Latest 52 Wks,Contribution Value due to Buyers YA Latest 26 Wks,Contribution Value due to Occasions per Buyer YA Latest 26 Wks,Contribution Value due to Value per Occasion YA Latest 26 Wks
0,2832,People Group,EUR,Total Panel,Total Outlets,VITAMIN SUPPLEMENTS,ALL OTHER,ALL OTHER,Germany,14.466,2.155,19.098,1.344,Yes,Yes,Yes,Yes,8.623709e+06,1.080711e+07,3.044560e+06,-5.227968e+06,1.123335e+07,1.237497e+07,-9.578544e+05,-183771.025,125.318534,35.304530,-60.623195,110.162817,-8.526882,-1.635942
1,920,People Group,EUR,Total Panel,Total Outlets,FABRIC SOFT,PRIVATE LABEL,PRIVATE LABEL,Spain,55.363,0.493,63.894,0.339,Yes,Yes,Yes,Yes,1.675381e+07,2.521797e+06,1.522746e+07,-9.954505e+05,1.028623e+07,1.631086e+06,1.135142e+07,-2696273.492,15.052075,90.889486,-5.941635,15.856980,110.355447,-26.212446
2,2699,People Group,EUR,Total Panel,Total Outlets,TOILET PAPER,ESSITY,ZEWA,Germany,11.586,1.591,16.281,1.298,Yes,Yes,Yes,Yes,6.528892e+06,9.307322e+06,-8.080408e+06,5.301964e+06,9.308653e+06,8.524028e+06,-2.425330e+06,3209951.565,142.555909,-123.763842,81.207707,91.571016,-26.054576,34.483524
3,1919,People Group,EUR,Total Panel,Total Outlets,LAUNDRY DET,HENKEL,WEISSER RIESE,Germany,6.458,1.157,9.347,-0.295,Yes,Yes,Yes,Yes,9.321929e+05,-2.031968e+06,-5.671527e+04,3.020884e+06,8.096343e+06,6.159855e+06,2.369565e+05,1699532.092,-217.977258,-6.084071,324.062098,76.081943,2.926710,20.991354
4,1711,People Group,EUR,Total Panel,Total Outlets,HH CLEANERS,PRIVATE LABEL,PRIVATE LABEL,Germany,50.808,1.994,64.247,0.263,Yes,Yes,Yes,Yes,7.358688e+06,8.157162e+05,4.329485e+06,2.213481e+06,6.751289e+06,3.765824e+06,1.125157e+06,1860310.712,11.085076,58.835005,30.079838,55.779338,16.665802,27.554895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,789,People Group,EUR,Total Panel,Total Outlets,DEPILATORIES,ALL OTHER,ALL OTHER,Italy,3.367,0.345,5.501,0.280,Yes,Yes,Yes,Yes,-1.548413e+06,4.518025e+05,-1.224573e+06,-7.756459e+05,-5.181834e+05,4.134671e+05,-3.254312e+05,-606219.073,-29.178424,79.085721,50.092963,-79.791661,62.802325,116.989289
108,924,People Group,EUR,Total Panel,Total Outlets,FABRIC SOFT,RECKITT BENCKISER,FLOR (RECKITT),Spain,7.556,0.471,10.968,-0.007,Yes,Yes,Yes,Yes,-1.264538e+06,1.617431e+05,-5.642667e+05,-8.620189e+05,-7.638931e+05,7.735781e+05,-9.476240e+05,-589846.318,-12.790683,44.622348,68.168670,-101.267852,124.051915,77.215824
109,261,People Group,EUR,Total Panel,Total Outlets,BATH/SHOWER,ALL OTHER,ALL OTHER,Germany,22.968,1.195,29.967,0.571,Yes,Yes,Yes,Yes,2.320751e+05,3.347936e+06,-3.753642e+05,-2.740487e+06,-3.035290e+06,5.140223e+06,9.217945e+04,-8267696.334,1442.609042,-161.742549,-1180.862031,-169.348673,-3.036924,272.385734
110,2350,People Group,EUR,Total Panel,Total Outlets,SKIN CARE,BEIERSDORF,NIVEA,Germany,18.148,0.404,25.663,-0.404,Yes,Yes,Yes,Yes,-4.185241e+07,-3.663586e+06,-8.033894e+06,-3.015494e+07,-4.139213e+06,2.562406e+06,-2.545820e+06,-4155793.480,8.753583,19.195771,72.050647,-61.905636,61.504925,100.400580
111,1939,People Group,EUR,Total Panel,Total Outlets,LAUNDRY DET,PRIVATE LABEL,PRIVATE LABEL,Italy,38.563,0.410,50.380,-0.132,Yes,Yes,Yes,Yes,-8.959337e+06,-1.553815e+05,-1.132845e+07,2.524501e+06,-4.986660e+06,1.230215e+06,-7.298662e+06,1081786.450,1.734297,126.442970,-28.177316,-24.670119,146.363737,-21.693607

# pg risk

In [32]:
# define a helper that applies the two rules only for P&G brands
def calculate_pg_risk(row):
    if row['BRAND OWNER'] != 'PROCTER & GAMBLE':
        return 'No'                       # keep others as “No”
    l52 = row['Latest 52 vs YA']
    l26 = row['Latest 26 vs YA']

    # declining‑growth
    if l52 > 0 and l26 < l52 :
        return 'Growth Deceleration'
    # declining‑deceleration
    if l52 < 0 and l26 < l52:
        return 'Decline Acceleration'
    return 'No'

# assign the column
df_final['P&G risk'] = df_final.apply(calculate_pg_risk, axis=1)

# quick check
print(df_final['P&G risk'].value_counts())
print(df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE'][['BRAND','country',
      'Latest 52 vs YA','Latest 26 vs YA','P&G risk']].head())

P&G risk
No                      8227
Growth Deceleration       68
Decline Acceleration      44
Name: count, dtype: int64
                                            BRAND       country  \
39                                     DON LIMPIO         Spain
40                                     DON LIMPIO  Total Europe
41    FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE)            GB
42    FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE)  Total Europe
116  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE)        France

     Latest 52 vs YA  Latest 26 vs YA P&G risk
39            -0.096           -0.078       No
40             0.000            0.000       No
41             0.000            0.000       No
42             0.000            0.000       No
116            0.000            0.000       No

In [33]:
# RECHECK: Full verification of P&G risk logic starting with P&G data
print("="*80)
print("FULL RECHECK: LOGIC VERIFICATION")
print("="*80)

# Step 1: Filter for PROCTER & GAMBLE brands
pg_brands = df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE'].copy()
print(f"\n✓ Total P&G rows in df_final: {len(pg_brands)}")
print(f"✓ Total rows in df_final: {len(df_final)}")

# Step 2: Check P&G risk column exists
if 'P&G risk' in df_final.columns:
    print(f"✓ P&G risk column exists in df_final")
else:
    print("✗ ERROR: P&G risk column NOT found in df_final")

# Step 3: Verify logic for each risk category
print("\n" + "="*80)
print("RISK CATEGORY VERIFICATION")
print("="*80)

# Declining growth: Latest 52 > 0 AND (Latest 26 < Latest 52 OR Latest 13 < Latest 52)
declining_growth = pg_brands[
    (pg_brands['Latest 52 vs YA'] > 0) & 
    (pg_brands['Latest 26 vs YA'] < pg_brands['Latest 52 vs YA']) 
]

declining_growth_marked = pg_brands[pg_brands['P&G risk'] == 'Growth Deceleration']

print(f"\n1. DECLINING GROWTH:")
print(f"   Expected logic count: {len(declining_growth)}")
print(f"   Marked as 'Declining growth': {len(declining_growth_marked)}")
print(f"   Match: {'✓ YES' if len(declining_growth) == len(declining_growth_marked) else '✗ NO'}")

# Declining Deceleration: Latest 52 < 0 AND (Latest 26 > Latest 52 OR Latest 13 > Latest 52)
declining_deceleration = pg_brands[
    (pg_brands['Latest 52 vs YA'] < 0) & 
    (pg_brands['Latest 26 vs YA'] < pg_brands['Latest 52 vs YA']) 
]

declining_deceleration_marked = pg_brands[pg_brands['P&G risk'] == 'Decline Acceleration']

print(f"\n2. DECLINING DECELERATION:")
print(f"   Expected logic count: {len(declining_deceleration)}")
print(f"   Marked as 'Declining Deceleration': {len(declining_deceleration_marked)}")
print(f"   Match: {'✓ YES' if len(declining_deceleration) == len(declining_deceleration_marked) else '✗ NO'}")

# No risk: Everything else (including non-P&G)
no_risk_pg = pg_brands[pg_brands['P&G risk'] == 'No']
print(f"\n3. NO RISK (P&G brands only):")
print(f"   Count: {len(no_risk_pg)}")

# Step 4: Overall distribution
print("\n" + "="*80)
print("OVERALL P&G RISK DISTRIBUTION")
print("="*80)
print(df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE']['P&G risk'].value_counts())

print("\n" + "="*80)
print("NON-P&G BRANDS - SHOULD ALL BE 'No'")
print("="*80)
non_pg = df_final[df_final['BRAND OWNER']!='PROCTER & GAMBLE']
non_pg_risk_dist = non_pg['P&G risk'].value_counts()
print(non_pg_risk_dist)
if len(non_pg_risk_dist) == 1 and non_pg_risk_dist.index[0] == 'No':
    print("✓ All non-P&G brands correctly marked as 'No'")
else:
    print("✗ ERROR: Some non-P&G brands have risk values other than 'No'")

# Step 5: Sample verification rows
print("\n" + "="*80)
print("SAMPLE ROWS - DETAILED VERIFICATION")
print("="*80)

print("\nSample DECLINING GROWTH rows:")
declining_growth_sample = declining_growth_marked[['BRAND', 'country', 'Latest 52 vs YA', 'Latest 26 vs YA',  'P&G risk']].head(5)
print(declining_growth_sample)
print("Logic check (for each row, Latest 52 > 0 and min(26,13) < 52):")
for idx, row in declining_growth_sample.iterrows():
    l52 = row['Latest 52 vs YA']
    l26 = row['Latest 26 vs YA']

    print(f"  {row['BRAND']}: 52={l52:.3f} (>0?{l52>0}), 26={l26:.3f}(<52?{l26<l52})")

print("\nSample DECLINING DECELERATION rows:")
declining_deceleration_sample = declining_deceleration_marked[['BRAND', 'country', 'Latest 52 vs YA', 'Latest 26 vs YA', 'P&G risk']].head(5)
print(declining_deceleration_sample)
print("Logic check (for each row, Latest 52 < 0 and max(26,13) > 52):")
for idx, row in declining_deceleration_sample.iterrows():
    l52 = row['Latest 52 vs YA']
    l26 = row['Latest 26 vs YA']
    print(f"  {row['BRAND']}: 52={l52:.3f} (<0?{l52<0}), 26={l26:.3f}(>52?{l26>l52})")

print("\n" + "="*80)
print("VERIFICATION COMPLETE")
print("="*80)

================================================================================
FULL RECHECK: LOGIC VERIFICATION
================================================================================

✓ Total P&G rows in df_final: 653
✓ Total rows in df_final: 8339
✓ P&G risk column exists in df_final

================================================================================
RISK CATEGORY VERIFICATION
================================================================================

1. DECLINING GROWTH:
   Expected logic count: 68
   Marked as 'Declining growth': 68
   Match: ✓ YES

2. DECLINING DECELERATION:
   Expected logic count: 44
   Marked as 'Declining Deceleration': 44
   Match: ✓ YES

3. NO RISK (P&G brands only):
   Count: 541

================================================================================
OVERALL P&G RISK DISTRIBUTION
================================================================================
P&G risk
No                      541
Growth Deceleration      68
Decline Acceleration     44
Name: count, dtype: int64

================================================================================
NON-P&G BRANDS - SHOULD ALL BE 'No'
================================================================================
P&G risk
No    7686
Name: count, dtype: int64
✓ All non-P&G brands correctly marked as 'No'

================================================================================
SAMPLE ROWS - DETAILED VERIFICATION
================================================================================

Sample DECLINING GROWTH rows:
                                                BRAND  country  \
118      ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE)  Germany
166       FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE)  Germany
168       FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE)    Spain
554                                           FEBREZE  Germany
1105  OLD SPICE (PROCTER & GAMBLE / PROCTER & GAMBLE)  Germany

      Latest 52 vs YA  Latest 26 vs YA             P&G risk
118             0.112           -0.333  Growth Deceleration
166             0.024           -0.016  Growth Deceleration
168             3.325            0.875  Growth Deceleration
554             1.794           -0.433  Growth Deceleration
1105            0.750            0.447  Growth Deceleration
Logic check (for each row, Latest 52 > 0 and min(26,13) < 52):
  ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=0.112 (>0?True), 26=-0.333(<52?True)
  FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=0.024 (>0?True), 26=-0.016(<52?True)
  FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=3.325 (>0?True), 26=0.875(<52?True)
  FEBREZE: 52=1.794 (>0?True), 26=-0.433(<52?True)
  OLD SPICE (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=0.750 (>0?True), 26=0.447(<52?True)

Sample DECLINING DECELERATION rows:
                                                BRAND  country  \
347            GILLETTE (PROCTER & GAMBLE / GILLETTE)    Italy
353                                   GILLETTE SERIES    Spain
356   OLD SPICE (PROCTER & GAMBLE / PROCTER & GAMBLE)  Germany
1318                                          SWIFFER  Germany
1319                                          SWIFFER    Italy

      Latest 52 vs YA  Latest 26 vs YA              P&G risk
347            -0.086           -0.104  Decline Acceleration
353            -0.019           -0.063  Decline Acceleration
356            -0.154           -0.172  Decline Acceleration
1318           -1.202           -2.072  Decline Acceleration
1319           -0.602           -0.637  Decline Acceleration
Logic check (for each row, Latest 52 < 0 and max(26,13) > 52):
  GILLETTE (PROCTER & GAMBLE / GILLETTE): 52=-0.086 (<0?True), 26=-0.104(>52?False)
  GILLETTE SERIES: 52=-0.019 (<0?True), 26=-0.063(>52?False)
  OLD SPICE (PROCTER & GAMBLE / PROCTER & GAMBLE): 52=-0.154 (<0?True), 26=-0.172(>52?False)
  SWIFFER: 52=-1.202 (<0?True), 26=-2.072(>52?False)
  SWIFFER: 52=-0.602 (<0?True), 26=-0.637(>52?False)

================================================================================
VERIFICATION COMPLETE
================================================================================

In [34]:
df_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,P&G risk
0,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,France,1.347,0.000,2.819,0.000,Yes,No,No,No,No
1,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,GB,0.328,0.000,0.578,0.000,No,No,No,No,No
2,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Germany,0.025,0.025,0.025,0.000,No,No,Yes,No,No
3,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Italy,4.423,-0.775,6.966,-1.439,Yes,No,Yes,No,No
4,0,People Group,EUR,Total Panel,Total Outlets,ABRASIVE CL PADS,3M,SCOTCH BRITE,Spain,7.331,-0.282,12.530,0.306,Yes,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8334,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Italy,0.005,-0.004,0.008,0.000,No,No,No,No,No
8335,3072,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,YELLOW WOOD PARTNERS,ST. IVES (YELLOW WOOD PARTNERS),Total Europe,0.160,0.000,0.256,0.000,No,No,No,No,No
8336,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),France,0.005,0.000,0.005,0.000,No,No,No,No,No
8337,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),GB,0.302,0.000,0.450,0.000,No,No,No,No,No
8338,3073,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,ZURU EDGE,DAISE (ZURU EDGE),Total Europe,0.059,0.000,0.087,0.000,No,No,No,No,No

In [35]:
df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE']['P&G risk'].value_counts()

P&G risk
No                      541
Growth Deceleration      68
Decline Acceleration     44
Name: count, dtype: int64

In [36]:
pg_risk_final=df_final[df_final['P&G risk']!='No']
pg_risk_final

,row_id,People,Currency,Total Panel,Total Outlets,CATEGORY,BRAND OWNER,BRAND,country,Latest 26 Wks,Latest 26 vs YA,Latest 52 Wks,Latest 52 vs YA,Tangible Brands,Growing Penetration,Accelerating Penetration,Top Opportunity,P&G risk
118,35,People Group,EUR,Total Panel,Total Outlets,ADULT INCONT,PROCTER & GAMBLE,ALWAYS (PROCTER & GAMBLE / PROCTER & GAMBLE),Germany,3.480,-0.333,5.970,0.112,Yes,No,No,No,Growth Deceleration
166,52,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),Germany,0.006,-0.016,0.050,0.024,No,No,No,No,Growth Deceleration
168,52,People Group,EUR,Total Panel,Total Outlets,ADW DETERGENT,PROCTER & GAMBLE,FAIRY (PROCTER & GAMBLE / PROCTER & GAMBLE),Spain,11.064,0.875,18.017,3.325,Yes,Yes,No,No,Growth Deceleration
347,117,People Group,EUR,Total Panel,Total Outlets,AFTER SHAVE,PROCTER & GAMBLE,GILLETTE (PROCTER & GAMBLE / GILLETTE),Italy,0.020,-0.104,0.092,-0.086,No,No,No,No,Decline Acceleration
353,119,People Group,EUR,Total Panel,Total Outlets,AFTER SHAVE,PROCTER & GAMBLE,GILLETTE SERIES,Spain,0.000,-0.063,0.061,-0.019,No,No,No,No,Decline Acceleration
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7786,2873,People Group,EUR,Total Panel,Total Outlets,VITAMIN SUPPLEMENTS,PROCTER & GAMBLE,VIGANTOLVIT,Germany,0.281,0.024,0.446,0.094,No,No,No,No,Growth Deceleration
8221,3030,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,GILLETTE SATIN CARE,Italy,0.059,0.059,0.329,0.329,No,No,No,No,Growth Deceleration
8222,3030,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,GILLETTE SATIN CARE,Spain,0.071,0.056,0.177,0.135,No,No,No,No,Growth Deceleration
8231,3033,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,KING C. GILLETTE,Italy,0.000,-0.026,0.024,-0.002,No,No,No,No,Decline Acceleration
8244,3037,People Group,EUR,Total Panel,Total Outlets,SKIN CLEANSING,PROCTER & GAMBLE,PAMPERS,Germany,1.214,-0.398,2.165,0.022,Yes,No,No,No,Growth Deceleration

In [37]:
df_final[df_final['BRAND OWNER']=='PROCTER & GAMBLE'].shape

(653, 18)

In [38]:
df_final['P&G risk'].value_counts()

P&G risk
No                      8227
Growth Deceleration       68
Decline Acceleration      44
Name: count, dtype: int64

In [39]:
pg_risk_final.to_excel('pg_risk3.xlsx')

In [41]:
pg_risk_final.columns

Index(['row_id', 'People', 'Currency', 'Total Panel', 'Total Outlets',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'P&G risk'],
      dtype='object')

In [48]:
pg_risk_final1=pg_risk_final[[ 'Currency',
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'P&G risk']]
pg_risk_final1.to_excel('pg_risk_output.xlsx',index=False)

In [47]:
df_priority1=df_priority[[ 'Currency', 
       'CATEGORY', 'BRAND OWNER', 'BRAND', 'country', 'Latest 26 Wks',
       'Latest 26 vs YA', 'Latest 52 Wks', 'Latest 52 vs YA',
       'Tangible Brands', 'Growing Penetration', 'Accelerating Penetration',
       'Top Opportunity', 'Value vs YA (Abs Change) Latest 52 Wks',
       'Value due to Buyers YA Latest 52 Wks',
       'Value due to Occasions per Buyer YA Latest 52 Wks',
       'Value due to Value per Occasion YA Latest 52 Wks',
       'Value vs YA (Abs Change) Latest 26 Wks',
       'Value due to Buyers YA Latest 26 Wks',
       'Value due to Occasions per Buyer YA Latest 26 Wks',
       'Value due to Value per Occasion YA Latest 26 Wks',
       'Contribution Value due to Buyers YA Latest 52 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 52 Wks',
       'Contribution Value due to Value per Occasion YA Latest 52 Wks',
       'Contribution Value due to Buyers YA Latest 26 Wks',
       'Contribution Value due to Occasions per Buyer YA Latest 26 Wks',
       'Contribution Value due to Value per Occasion YA Latest 26 Wks']]

df_priority1.to_excel('priority_brands_output.xlsx', index=False)